# scripts/catalog_education.py

def get_schemes():
    return [
        {
            'id': 'pre-matric-sc-104',
            'code': 'PRE-MATRIC-SC',
            'name': 'Pre-Matric Scholarship Scheme for SC and Other Categories',
            'short_name': 'Pre-Matric SC Scholarship (Class 9-10)',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'sc'],
            'desc': 'Annual academic allowance of ₹3,500 for day scholars and ₹7,000 for hostellers studying in classes 9 and 10.',
            'benefit': '₹3,500 (Day Scholar) to ₹7,000 (Hosteller) per year direct bank transfer',
            'quantum': '₹7,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['sc'], 'label': 'Scheduled Caste (SC) Category', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Regular Student in Class IX or X', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Family Income ≤ ₹2.5 Lakh/yr', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'occupation': ['student'], 'income_limit': 250000},
            'docs': ['Aadhaar Card', 'SC Caste Certificate', 'Income Certificate', 'Class 9/10 School Bonafide Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pre-matric-obc-105',
            'code': 'PRE-MATRIC-OBC',
            'name': 'Pre-Matric Scholarship for OBC, EBC and DNT Students',
            'short_name': 'PM-YASASVI Pre-Matric OBC',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'obc', 'ebc'],
            'desc': 'Financial assistance of ₹4,000 per annum for OBC/EBC/DNT students studying in classes 9 and 10.',
            'benefit': '₹4,000 / year academic stipend directly into student bank account',
            'quantum': '₹4,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['obc', 'ews'], 'label': 'OBC / EBC / DNT Category', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Active Student in Class 9-10', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Family Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['obc', 'ews'], 'occupation': ['student'], 'income_limit': 250000},
            'docs': ['Aadhaar Card', 'OBC/EBC Certificate', 'Income Certificate', 'Fee Receipt / Bonafide'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'nmmss-merit-106',
            'code': 'NMMSS',
            'name': 'National Means-cum-Merit Scholarship Scheme',
            'short_name': 'NMMSS ₹12,000 Scholarship (Class 9-12)',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'merit_poor'],
            'desc': '₹12,000 per annum (₹1,000/month) for meritorious students from class 9 to 12 to prevent secondary school dropouts.',
            'benefit': '₹12,000 / year (Total ₹48,000 across 4 years from Class IX to XII)',
            'quantum': '₹12,000 / year',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Govt / Local Body School', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 350000, 'label': 'Parental Income ≤ ₹3.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 350000},
            'docs': ['Aadhaar Card', 'NMMSS Selection Exam Merit Roll Number', 'Class 7/8 Marksheet (Min 55%)', 'Income Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-yasasvi-top-107',
            'code': 'PM-YASASVI-TOP',
            'name': 'PM-YASASVI Top Class School Education for OBC, EBC & DNT',
            'short_name': 'PM-YASASVI Top Class Schooling',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'obc', 'ebc'],
            'desc': 'Full tuition fee, hostel fee, and books allowance up to ₹75,000 (Class 9-10) and ₹1,25,000 (Class 11-12) at designated Top Schools.',
            'benefit': '100% Tuition & Boarding Fees covered up to ₹1,25,000 per year',
            'quantum': '₹1,25,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['obc', 'ews'], 'label': 'OBC / EBC / DNT Category', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Annual Family Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['obc', 'ews'], 'income_limit': 250000},
            'docs': ['Aadhaar Card', 'Caste Certificate', 'Top Class School Bonafide Certificate', 'Income Certificate'],
            'url': 'https://yet.nta.ac.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'central-sector-scholarship-108',
            'code': 'CSSS-COLLEGE',
            'name': 'Central Sector Scheme of Scholarship for College and University Students',
            'short_name': 'Central Sector College Scholarship',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'undergraduate', 'postgraduate'],
            'desc': '₹12,000 per year for 3 undergraduate years and ₹20,000 per year for postgraduate studies for students above 80th percentile in Class XII board.',
            'benefit': '₹12,000 / yr for UG and ₹20,000 / yr for PG (Total ₹76,000 over 5 years)',
            'quantum': '₹12,000 - ₹20,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Pursuing Regular Degree Course', 'impact': 'critical'},
                {'field': 'citizen.education', 'op': 'IN', 'value': ['higher_secondary', 'graduate'], 'label': 'Class 12th Pass (Above 80th Percentile)', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 450000, 'label': 'Annual Household Income ≤ ₹4.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'education': ['higher_secondary', 'graduate'], 'income_limit': 450000},
            'docs': ['Aadhaar Card', 'Class 12th Board Marksheet', 'College Admission & Fee Receipt', 'Income Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'aicte-pragati-109',
            'code': 'AICTE-PRAGATI',
            'name': 'AICTE Pragati Scholarship for Girl Students (Technical Degree/Diploma)',
            'short_name': 'AICTE Pragati ₹50,000 for Girls',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'women'],
            'desc': '₹50,000 per annum for tuition fees, computer, books and equipment for girl students admitted to AICTE approved technical degree or diploma courses.',
            'benefit': '₹50,000 / year lump sum grant throughout entire engineering/diploma duration',
            'quantum': '₹50,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Student (Max 2 girls per family)', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'First Year Tech Degree/Diploma Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student'], 'income_limit': 800000},
            'docs': ['Aadhaar Card', 'Class 10/12 Marksheet', 'Centralized Admission Allotment Letter', 'Family Income Certificate'],
            'url': 'https://www.aicte-pragati-saksham-gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'aicte-saksham-110',
            'code': 'AICTE-SAKSHAM',
            'name': 'AICTE Saksham Scholarship for Specially Abled Students',
            'short_name': 'AICTE Saksham ₹50,000 Disability Aid',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'disability'],
            'desc': '₹50,000 per annum for specially-abled students with disability not less than 40% admitted to AICTE approved technical colleges.',
            'benefit': '₹50,000 / year scholarship grant for assistive devices and college fees',
            'quantum': '₹50,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.disability', 'op': 'IN', 'value': ['physical', 'visual', 'hearing', 'intellectual', 'multiple'], 'label': 'Disability ≥ 40% certified by Govt Medical Board', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in AICTE Technical College', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 800000},
            'docs': ['Aadhaar Card', 'UDID / Disability Certificate (40%+)', 'College Bonafide Certificate', 'Income Certificate'],
            'url': 'https://www.aicte-pragati-saksham-gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'aicte-swanath-111',
            'code': 'AICTE-SWANATH',
            'name': 'AICTE Swanath Scholarship (Orphans & Wards of Armed Forces)',
            'short_name': 'AICTE Swanath Scheme',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'orphan'],
            'desc': '₹50,000 per annum scholarship for orphan children, wards of armed forces/paramilitary martyred in action pursuing technical education.',
            'benefit': '₹50,000 / year grant for tuition fees and hostel charges',
            'quantum': '₹50,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Technical Degree/Diploma Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 800000},
            'docs': ['Aadhaar Card', 'Death Certificate of Parents / Armed Forces Martyr Proof', 'College Admission Proof'],
            'url': 'https://www.aicte-india.org',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'national-overseas-sc-112',
            'code': 'NOS-SC',
            'name': 'National Overseas Scholarship for SC, DNT and Landless Agricultural Labourers',
            'short_name': 'National Overseas Scholarship SC (Abroad)',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'sc'],
            'desc': '100% full tuition fee coverage, living allowance ($15,400 / £9,900 per year), health insurance and airfare to pursue Master\'s and Ph.D. abroad.',
            'benefit': 'Full foreign university tuition + $15,400/year living stipend + Airfare',
            'quantum': 'Complete Overseas Funding (Up to ₹80 Lakh)',
            'type': 'direct_benefit',
            'days': 60,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['sc'], 'label': 'Scheduled Caste (SC) Category', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 35, 'label': 'Age below 35 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'max_age': 35, 'income_limit': 800000},
            'docs': ['Aadhaar Card', 'SC Certificate', 'Unconditional Offer Letter from Top 500 QS Ranked University', 'Bachelor/Master Degree Marksheet'],
            'url': 'https://nosmsje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'ishan-uday-ne-113',
            'code': 'ISHAN-UDAY',
            'name': 'Ishan Uday Special Scholarship Scheme for North Eastern Region',
            'short_name': 'Ishan Uday NE Degree Scholarship',
            'ministry': 'Ministry of Education',
            'state': 'North Eastern States',
            'category': 'education',
            'beneficiary_types': ['student'],
            'desc': '₹5,400 per month for General degree courses and ₹7,800 per month for Technical/Professional degree courses for North East domicile students.',
            'benefit': '₹5,400 - ₹7,800 / month direct bank transfer for duration of graduation',
            'quantum': '₹7,800 / month',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': '1st Year Undergraduate Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 450000, 'label': 'Family Annual Income ≤ ₹4.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 450000},
            'docs': ['Aadhaar Card', 'Permanent Resident Certificate (PRC) of NE State', 'College Admission Proof', 'Income Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'begum-hazrat-mahal-114',
            'code': 'BHM-SCHOLARSHIP',
            'name': 'Begum Hazrat Mahal National Scholarship for Minority Girls',
            'short_name': 'Begum Hazrat Mahal Scholarship (Girls 9-12)',
            'ministry': 'Ministry of Minority Affairs',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'minority', 'women'],
            'desc': '₹5,000 (Class 9-10) and ₹6,000 (Class 11-12) per annum for meritorious girl students belonging to notified minority communities.',
            'benefit': '₹5,000 - ₹6,000 / year direct bank transfer to student',
            'quantum': '₹6,000 / year',
            'type': 'direct_benefit',
            'days': 25,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Student', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Class 9 to 12 Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 200000, 'label': 'Family Annual Income ≤ ₹2 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student'], 'income_limit': 200000},
            'docs': ['Aadhaar Card', 'Minority Community Self-Declaration', 'Marksheet with ≥ 50% Marks', 'Income Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pmrf-research-fellowship-115',
            'code': 'PMRF',
            'name': 'Prime Minister\'s Research Fellowship (Doctoral Ph.D. Excellence)',
            'short_name': 'PMRF ₹70,000 - ₹80,000 / Month Fellowship',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'researcher'],
            'desc': 'Prestigious fellowship of ₹70,000/month (1st-2nd yr), ₹75,000/month (3rd yr), ₹80,000/month (4th-5th yr) + ₹2 Lakh/yr research contingency grant for Ph.D. at IISc, IITs, and IISERs.',
            'benefit': 'Monthly stipend of ₹70,000 - ₹80,000 + ₹2 Lakh annual research contingency grant',
            'quantum': '₹80,000 / month + ₹2 Lakh/yr',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Admitted in Direct Ph.D. at PMRF Granting Institute', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student']},
            'docs': ['Aadhaar Card', 'GATE/NET Scorecard or CGPA ≥ 8.0 Transcript', 'Research Proposal'],
            'url': 'https://www.pmrf.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pmss-capf-116',
            'code': 'PMSS-WAR',
            'name': 'Prime Minister\'s Scholarship Scheme for Wards of CAPFs and Assam Rifles',
            'short_name': 'PMSS CAPF ₹3,000/Month Scholarship',
            'ministry': 'Ministry of Home Affairs',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'police_wards'],
            'desc': '₹3,000 per month for girls and ₹2,500 per month for boys for professional degree courses (Engineering, Medical, MBA, MCA) for wards of CAPF personnel.',
            'benefit': '₹30,000 (Boys) / ₹36,000 (Girls) annual cash scholarship for degree duration',
            'quantum': '₹36,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Professional Degree (BE/MBBS/BBA/BCA)', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student']},
            'docs': ['Aadhaar Card', 'Service Certificate / PPO of Parent (CAPF/Assam Rifles)', '12th Marksheet ≥ 60%'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'inspire-scholarship-she-117',
            'code': 'DST-INSPIRE',
            'name': 'INSPIRE Scholarship for Higher Education (SHE)',
            'short_name': 'DST INSPIRE ₹80,000 Annual Grant',
            'ministry': 'Ministry of Science and Technology',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student'],
            'desc': '₹80,000 per annum (₹60,000 scholarship + ₹20,000 summer mentorship project grant) for students in top 1% of 12th board pursuing Natural/Basic Sciences (B.Sc/M.Sc).',
            'benefit': '₹80,000 per year for 5 years of B.Sc. / B.S. / M.Sc. basic science studies',
            'quantum': '₹80,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'BETWEEN', 'value': [17, 22], 'label': 'Age 17 to 22 Years', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in B.Sc./M.Sc. Natural Sciences', 'impact': 'critical'}
            ],
            'flatRules': {'min_age': 17, 'max_age': 22, 'occupation': ['student']},
            'docs': ['Aadhaar Card', 'Class 12th Board Top 1% Advisory Note', 'College Bonafide Certificate'],
            'url': 'https://online-inspire.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'national-fellowship-obc-118',
            'code': 'NFOBC',
            'name': 'National Fellowship for Other Backward Classes (NFOBC)',
            'short_name': 'NFOBC Junior Research Fellowship',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'obc', 'researcher'],
            'desc': 'UGC-equivalent fellowship of ₹37,000/month for JRF and ₹42,000/month for SRF + HRA + contingency for OBC students pursuing regular M.Phil and Ph.D.',
            'benefit': 'Monthly fellowship of ₹37,000 to ₹42,000 + Full HRA and annual contingency',
            'quantum': '₹42,000 / month + HRA',
            'type': 'direct_benefit',
            'days': 40,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['obc'], 'label': 'Other Backward Class (OBC) Category', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Regular Ph.D. Programme', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['obc'], 'occupation': ['student'], 'income_limit': 800000},
            'docs': ['Aadhaar Card', 'OBC Certificate (Non-Creamy Layer)', 'UGC-NET/CSIR-NET Qualified Slip', 'Ph.D. Registration Certificate'],
            'url': 'https://ugcnetonline.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'cbse-udaan-girls-119',
            'code': 'CBSE-UDAAN',
            'name': 'CBSE Udaan Mentorship for Girl Students (Engineering Entrance)',
            'short_name': 'CBSE Udaan Free JEE Coaching for Girls',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'women'],
            'desc': 'Free virtual coaching classes, tablet, study material, and student mentorship for girl students in classes 11-12 preparing for JEE Main/Advanced.',
            'benefit': '100% Free JEE Engineering Entrance Virtual Coaching + Free Tablet & Test Series',
            'quantum': 'Free Academic Coaching (Saves ₹1 - ₹2 Lakh)',
            'type': 'in_kind',
            'days': 20,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Student in Class XI (PCM stream)', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 600000, 'label': 'Family Annual Income ≤ ₹6 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'income_limit': 600000},
            'docs': ['Aadhaar Card', 'Class 10th Marksheet (Min 70% overall, 80% Math/Science)', 'Income Certificate'],
            'url': 'https://www.cbse.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'samagra-shiksha-uniform-120',
            'code': 'SAMAGRA-UNIFORM',
            'name': 'Samagra Shiksha Free Textbooks and School Uniforms Grant',
            'short_name': 'Free School Books & Uniforms (Class 1-8)',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'children'],
            'desc': 'Statutory provision of two free sets of school uniforms (₹600) and 100% free school textbooks for all children in classes 1-8 in government schools.',
            'benefit': 'Two sets of free school uniforms + Complete NCERT/SCERT textbook sets annually',
            'quantum': 'Free Books & Uniforms Kit',
            'type': 'in_kind',
            'days': 7,
            'rules': [
                {'field': 'citizen.age', 'op': 'BETWEEN', 'value': [6, 14], 'label': 'Age 6 to 14 Years (Elementary Education)', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Government / Local Body School', 'impact': 'critical'}
            ],
            'flatRules': {'min_age': 6, 'max_age': 14, 'occupation': ['student']},
            'docs': ['Aadhaar Card of Child', 'School Enrollment U-DISE Code'],
            'url': 'https://samagra.education.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-poshan-midday-121',
            'code': 'PM-POSHAN',
            'name': 'Pradhan Mantri POSHAN (Mid-Day Meal Scheme)',
            'short_name': 'PM POSHAN Daily Hot Cooked Meal',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'children'],
            'desc': 'Hot cooked nutritious lunch meal providing 450-700 calories and 12-20g protein on all school days for children in primary and upper-primary classes.',
            'benefit': 'Free Daily Hot Cooked Nutritious School Meal + Supplementary Nutritional Eggs/Milk',
            'quantum': 'Daily Nutritional Lunch (220 Days/yr)',
            'type': 'in_kind',
            'days': 1,
            'rules': [
                {'field': 'citizen.age', 'op': 'BETWEEN', 'value': [5, 14], 'label': 'School Child Age 5-14', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Government / Govt-Aided School Student', 'impact': 'critical'}
            ],
            'flatRules': {'min_age': 5, 'max_age': 14, 'occupation': ['student']},
            'docs': ['School Enrollment Record'],
            'url': 'https://pmposhan.education.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'vidyasaarathi-csr-122',
            'code': 'VIDYASAARATHI',
            'name': 'Vidyasaarathi NSDL Corporate Education Grants Portal',
            'short_name': 'Vidyasaarathi Direct CSR Grants',
            'ministry': 'Ministry of Finance',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'undergraduate', 'diploma'],
            'desc': 'Direct corporate social responsibility education sponsorships of ₹10,000 to ₹50,000 per year for students from low-income families.',
            'benefit': 'Direct non-repayable education grant of ₹10,000 - ₹50,000 for college fee waiver',
            'quantum': '₹50,000 / year grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Active College / ITI / Diploma Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 500000, 'label': 'Annual Household Income ≤ ₹5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 500000},
            'docs': ['Aadhaar Card', 'Class 10/12 Marksheet (Min 60%)', 'College Fee Structure', 'Income Certificate'],
            'url': 'https://www.vidyasaarathi.co.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-evidya-free-123',
            'code': 'PM-EVIDYA',
            'name': 'PM eVIDYA Digital Education Multi-Mode Access Platform',
            'short_name': 'PM eVIDYA Free DTH & DIKSHA Content',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student'],
            'desc': 'One Nation, One Digital Platform giving free access to 200 dedicated DTH TV channels for classes 1-12 and DIKSHA QR-coded digital textbook repository.',
            'benefit': '100% Free Curriculum-Aligned Video Lessons & Audiobooks in 33 Indian Languages',
            'quantum': 'Free Digital Learning Access',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Student or Educator', 'impact': 'moderate'}],
            'flatRules': {'occupation': ['student']},
            'docs': [],
            'url': 'https://diksha.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'shreyas-apprenticeship-124',
            'code': 'SHREYAS-HE',
            'name': 'Scheme for Higher Education Youth in Apprenticeship and Skills',
            'short_name': 'SHREYAS Graduate Apprenticeship Stipend',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student', 'youth', 'graduate'],
            'desc': 'On-the-job apprenticeship stipend subsidy of ₹6,000 to ₹9,000 per month for non-technical general graduates (BA, B.Sc, B.Com).',
            'benefit': 'Monthly stipend of ₹6,000 to ₹9,000 for 12 months with industrial certification',
            'quantum': '₹9,000 / month',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [
                {'field': 'citizen.education', 'op': 'IN', 'value': ['graduate', 'post_graduate'], 'label': 'Graduated with BA, B.Sc, B.Com degree', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'BETWEEN', 'value': [18, 30], 'label': 'Age 18 to 30 Years', 'impact': 'critical'}
            ],
            'flatRules': {'education': ['graduate', 'post_graduate'], 'min_age': 18, 'max_age': 30},
            'docs': ['Aadhaar Card', 'Degree Passing Certificate', 'Bank Passbook'],
            'url': 'https://www.apprenticeshipindia.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-vidyalakshmi-loan-125',
            'code': 'VIDYALAKSHMI',
            'name': 'PM Vidya Lakshmi Single Window Education Loan Portal',
            'short_name': 'Vidya Lakshmi Concessional Education Loan',
            'ministry': 'Ministry of Finance',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['student'],
            'desc': 'Single window portal connecting students to 40+ banks for education loans up to ₹7.5 Lakh without collateral and full interest subsidy during moratorium.',
            'benefit': 'Collateral-free education loan up to ₹7.5 Lakh with central interest subsidy during study',
            'quantum': 'Up to ₹7,50,000 collateral-free loan',
            'type': 'loan',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Secured Admission to Higher Education Institute', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 450000, 'label': 'Family Income ≤ ₹4.5 Lakh for 100% Interest Subsidy (CSIS)', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['student']},
            'docs': ['Aadhaar Card', 'Admission Allotment Letter', 'Prospectus / Fee Schedule', 'Income Certificate'],
            'url': 'https://www.vidyalakshmi.co.in',
            'completeness': 'VERIFIED'
        }
    ]
