# scripts/catalog_women_child.py

def get_schemes():
    return [
        {
            'id': 'wcd-bbbp-120',
            'code': 'BBBP',
            'name': 'Beti Bachao Beti Padhao',
            'short_name': 'Beti Bachao Beti Padhao',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['women', 'girl_child', 'parents'],
            'desc': 'National flagship initiative to address declining child sex ratio, promote girl child education, and prevent gender-biased sex selection.',
            'benefit': 'Comprehensive educational, health, and institutional convergence support for girl children',
            'quantum': 'Direct Institutional Support & Grants',
            'type': 'in_kind_and_services',
            'days': 15,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Citizen or Girl Child Beneficiary', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Birth Certificate of Girl Child', 'Parent Aadhaar Card', 'Address Proof'],
            'url': 'https://wcd.nic.in/bbbp-schemes',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-vatsalya-121',
            'code': 'MISSION-VATSALYA',
            'name': 'Mission Vatsalya (Child Protection Services)',
            'short_name': 'Mission Vatsalya',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['children', 'orphan', 'vulnerable_children'],
            'desc': 'Statutory child protection scheme providing foster care, sponsorship support (₹4,000/month per child), institutional care, and rehabilitation for children in difficult circumstances.',
            'benefit': '₹4,000 monthly sponsorship assistance and institutional protection',
            'quantum': '₹4,000 / month',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'LT', 'value': 18, 'label': 'Age Under 18 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 72000, 'label': 'Rural Income ≤ ₹72,000 / Urban ≤ ₹96,000', 'impact': 'critical'}
            ],
            'flatRules': {'age_max': 18, 'income_limit': 72000},
            'docs': ['Birth Certificate', 'Income Certificate', 'Guardian Aadhaar Card', 'CWC Recommendation'],
            'url': 'https://cara.wcd.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-shakti-sambal-122',
            'code': 'SHAKTI-SAMBAL',
            'name': 'Mission Shakti - SAMBAL (Safety & Security for Women)',
            'short_name': 'Sambal One Stop Centres',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['women', 'distressed_women'],
            'desc': 'Integrated 24/7 emergency response, legal aid, medical assistance, psycho-social counselling, and temporary shelter for women facing violence through One Stop Centres (Sakhi) and 181 Helpline.',
            'benefit': 'Free integrated emergency rescue, shelter, medical & legal aid',
            'quantum': '100% Free Government Service',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Woman Beneficiary in Distress', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card (Optional for emergency shelter)', 'Self Declaration'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-shakti-samarthya-123',
            'code': 'SHAKTI-SAMARTHYA',
            'name': 'Mission Shakti - SAMARTHYA (Empowerment of Women)',
            'short_name': 'Samarthya Women Empowerment',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['women', 'working_women', 'destitute_women'],
            'desc': 'Empowerment umbrella incorporating Shakti Sadan (shelter, clothing, food, skill development for destitute women) and Sakhi Niwas (safe working women hostels with day-care facilities).',
            'benefit': 'Free institutional shelter, vocational training, or subsidized safe working hostel',
            'quantum': 'Institutional Accommodation & Training Subsidy',
            'type': 'in_kind_and_services',
            'days': 14,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Citizen', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card', 'Employment Proof or Distress Verification by Local Authority'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-poshan-abhiyaan-124',
            'code': 'POSHAN-ABHIYAAN',
            'name': 'Poshan Abhiyaan (National Nutrition Mission 2.0)',
            'short_name': 'Poshan 2.0',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'food_nutrition',
            'beneficiary_types': ['pregnant_women', 'lactating_mothers', 'children'],
            'desc': 'Holistic nutrition intervention providing Take Home Rations (THR), Hot Cooked Meals (HCM), micronutrient supplementation, and growth monitoring across 14 lakh Anganwadis.',
            'benefit': 'Free supplementary nutrition rations, micronutrients, and maternal care',
            'quantum': 'Take-Home Ration & Nutritional Feed',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Pregnant/Lactating Mother or Child 0-6 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Mother and Child Protection (MCP) Card', 'Aadhaar Card'],
            'url': 'https://poshanabhiyaan.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-icds-anganwadi-125',
            'code': 'ICDS-ANGANWADI',
            'name': 'Anganwadi Services Scheme (ICDS)',
            'short_name': 'Anganwadi Child Care',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['children', 'pregnant_women', 'lactating_mothers'],
            'desc': 'Supplementary nutrition, pre-school non-formal education, immunization, health check-up, and referral services for children aged 0-6 years and mothers.',
            'benefit': 'Free daily nutrition food packages, pre-school learning kits, and immunization',
            'quantum': 'Daily Nutritional Feeding & Early Education',
            'type': 'in_kind_and_services',
            'days': 5,
            'rules': [
                {'field': 'citizen.age', 'op': 'LTE', 'value': 6, 'label': 'Children Aged 0-6 Years or Expectant Mothers', 'impact': 'critical'}
            ],
            'flatRules': {'age_max': 6},
            'docs': ['Aadhaar of Mother/Child', 'Birth Certificate'],
            'url': 'https://wcd.nic.in/schemes/integrated-child-development-services-icds-scheme',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-palna-creche-126',
            'code': 'PALNA-CRECHE',
            'name': 'Palna - National Creche Scheme for Children of Working Mothers',
            'short_name': 'Palna Creche Scheme',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['working_women', 'children'],
            'desc': 'Daycare creche facilities for children aged 6 months to 6 years of working women for 7.5 hours per day, including nutrition, sleep facilities, and early stimulation.',
            'benefit': 'Free/subsidized community daycare and nutrition for working mother families',
            'quantum': 'Full Daycare & Feeding Facilities',
            'type': 'in_kind_and_services',
            'days': 10,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'daily_wage', 'unorganized_worker', 'self_employed'], 'label': 'Employed or Daily Wage Mother', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 144000, 'label': 'Household Income ≤ ₹1.44 Lakh for zero fee tier', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['employed', 'daily_wage', 'unorganized_worker', 'self_employed'], 'income_limit': 144000},
            'docs': ['Aadhaar of Parents', 'Proof of Mother Employment', 'Child Birth Certificate'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-sag-kishori-127',
            'code': 'SAG-KISHORI',
            'name': 'Scheme for Adolescent Girls (Kishori Shakti)',
            'short_name': 'Kishori SAG Scheme',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['adolescent_girls', 'students'],
            'desc': 'Nutrition support of 600 calories and 18-20g protein per day, IFA supplementation, life skills education, and vocational training for out-of-school girls aged 11-14 years.',
            'benefit': 'Daily nutrition supplement rations and vocational skill guidance',
            'quantum': 'Nutritional Ration & Health Kits',
            'type': 'in_kind_and_services',
            'days': 14,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Adolescent', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 11, 'label': 'Age Between 11 and 18', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 18, 'label': 'Age ≤ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 11, 'age_max': 18},
            'docs': ['Aadhaar Card', 'Anganwadi Enrollment Record'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-pmmsk-kendra-128',
            'code': 'PMMSK',
            'name': 'Pradhan Mantri Mahila Shakti Kendra',
            'short_name': 'Mahila Shakti Kendra',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['rural_women', 'women'],
            'desc': 'Community-level empowerment of rural women through student volunteers at Gram Panchayat level, providing awareness of entitlements, literacy, and skill access.',
            'benefit': 'Free doorstep government entitlements facilitation and training',
            'quantum': 'Empowerment & Linkage Service',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Resident', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card', 'Residence Proof'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-step-training-129',
            'code': 'STEP-WOMEN',
            'name': 'Support to Training and Employment Programme for Women (STEP)',
            'short_name': 'STEP Training for Women',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['women', 'unemployed_women', 'artisans'],
            'desc': 'Skill upgradation in traditional and modern sectors (agriculture, handicrafts, textiles, IT, food processing) enabling self-employment for women aged 16 and above.',
            'benefit': 'Free sector-specific certified vocational training with stipend during course',
            'quantum': 'Free Certified Skill Training & Toolkits',
            'type': 'in_kind_and_services',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Candidate', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 16, 'label': 'Age 16 Years and Above', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 16},
            'docs': ['Aadhaar Card', 'Educational Certificate', 'Passport Photo'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-swadhar-greh-130',
            'code': 'SWADHAR-GREH',
            'name': 'Swadhar Greh (Shelter for Women in Difficult Circumstances)',
            'short_name': 'Swadhar Greh Shelter',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['destitute_women', 'widow', 'deserted_women'],
            'desc': 'Temporary residential shelter, food, clothing, medical care, and economic rehabilitation for deserted, widowed, or rescued women without social or economic support.',
            'benefit': 'Complete institutional shelter, boarding, healthcare, and livelihood retraining',
            'quantum': 'Free Residential Shelter & Living Allowance',
            'type': 'in_kind_and_services',
            'days': 3,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Woman in Distressed Situation', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Adult Woman (18+)', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 18},
            'docs': ['Aadhaar Card (if available)', 'Local Magistrate / Police Reference'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-ujjawala-anti-trafficking-131',
            'code': 'UJJAWALA-SCHEME',
            'name': 'Ujjawala Comprehensive Scheme for Combating Trafficking',
            'short_name': 'Ujjawala Rescue & Reintegration',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['women', 'trafficking_victims'],
            'desc': 'Prevention of trafficking, rescue, rehabilitation, and reintegration of women and children victims of commercial sexual exploitation.',
            'benefit': 'Protective home shelter, legal assistance, vocational training, and repatriation',
            'quantum': '100% Comprehensive Institutional Support',
            'type': 'in_kind_and_services',
            'days': 2,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Victim or Vulnerable Individual', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['First Information Report (FIR) / Police Rescue Memo / Child Welfare Committee Order'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-bsy-balika-132',
            'code': 'BSY-BALIKA',
            'name': 'Balika Samridhi Yojana (BSY)',
            'short_name': 'Balika Samridhi Yojana',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['girl_child', 'bpl'],
            'desc': 'Post-birth cash grant of ₹500 plus annual educational scholarship from Class 1 to 10 for girl children born in BPL families.',
            'benefit': '₹500 post-birth grant + ₹300-₹1,000 annual school scholarships accumulating interest until age 18',
            'quantum': '₹500 Grant + Cumulative Scholarships',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Child Beneficiary', 'impact': 'critical'},
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Family Status', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'bpl_required': True},
            'docs': ['Girl Child Birth Certificate', 'BPL Ration Card', 'Bank Account in Girl Name'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-pm-poshan-school-133',
            'code': 'PM-POSHAN-MIDDAY',
            'name': 'PM POSHAN Shakti Nirman (National Mid-Day Meal Scheme)',
            'short_name': 'PM POSHAN Mid-Day Meal',
            'ministry': 'Ministry of Education',
            'state': 'All-India',
            'category': 'food_nutrition',
            'beneficiary_types': ['students', 'children'],
            'desc': 'Provides one freshly cooked nutritious hot lunch to every enrolled child studying in Classes 1 to 8 in government and government-aided schools (over 11.8 crore students).',
            'benefit': 'Free daily nutritious meal meeting 450-700 calories and 12-20g protein',
            'quantum': 'Free Daily Hot-Cooked School Meal',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Classes 1st to 8th in Government/Aided School', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 14, 'label': 'Age ≤ 14 Years', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'age_max': 14},
            'docs': ['School Enrollment ID / Admission Number'],
            'url': 'https://pmposhan.education.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-mahila-coir-134',
            'code': 'MAHILA-COIR-YOJANA',
            'name': 'Mahila Coir Yojana (MCY)',
            'short_name': 'Mahila Coir Yojana',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['women', 'rural_women', 'artisans'],
            'desc': '75% subsidy on the cost of motorized coir spinning ratt / motorized traditional ratt to trained rural women artisans in coir producing regions.',
            'benefit': '75% Government Capital Subsidy on Coir Spinning Equipment',
            'quantum': '75% Machine Cost Subsidy',
            'type': 'capital_subsidy',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Artisan', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age 18 Years and Above', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 18},
            'docs': ['Aadhaar Card', 'Coir Board Training Certificate', 'Bank Passbook'],
            'url': 'https://coirboard.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-tread-women-135',
            'code': 'TREAD-WOMEN',
            'name': 'Trade Related Entrepreneurship Assistance and Development (TREAD)',
            'short_name': 'TREAD Women Entrepreneurs',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'entrepreneurship',
            'beneficiary_types': ['women', 'entrepreneurs'],
            'desc': 'Government grant up to 30% of total project cost through lending institutions for women entrepreneurs taking up non-farm business ventures.',
            'benefit': '30% Capital Grant on Bank-Financed Micro-Enterprises (Up to ₹30 Lakh)',
            'quantum': '30% Capital Grant Subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Entrepreneur', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['self_employed', 'business', 'artisan'], 'label': 'Self-Employed / Business Owner', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['self_employed', 'business', 'artisan']},
            'docs': ['Aadhaar Card', 'Detailed Project Proposal', 'Bank In-Principle Loan Sanction Letter'],
            'url': 'https://msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-widow-distress-136',
            'code': 'WIDOW-REHAB-AID',
            'name': 'Scheme for Financial Assistance to Destitute Widows',
            'short_name': 'Destitute Widow Financial Relief',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['widow', 'women'],
            'desc': 'Monthly maintenance allowance and rehabilitation grants for young and destitute widows to achieve economic self-reliance.',
            'benefit': '₹1,500 - ₹2,500 monthly sustenance pension + self-employment toolkit grant',
            'quantum': '₹2,000 / month',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Widowed Female Citizen', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 100000, 'label': 'Annual Household Income ≤ ₹1,00,000', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'income_limit': 100000},
            'docs': ['Husband Death Certificate', 'Aadhaar Card', 'Income Certificate', 'Bank Passbook'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-poshan-vatika-137',
            'code': 'POSHAN-VATIKA',
            'name': 'Poshan Vatika (Nutrition Garden Initiative)',
            'short_name': 'Poshan Vatika Kitchen Garden',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'food_nutrition',
            'beneficiary_types': ['rural_women', 'farmers'],
            'desc': 'Provision of organic seed kits, fruit saplings, and micro-irrigation advice to establish kitchen gardens in backyards of rural households and Anganwadis to combat micronutrient deficiency.',
            'benefit': 'Free organic seed minikits, vegetable seedlings, and guidance',
            'quantum': 'Free Seed & Gardening Kit',
            'type': 'in_kind_and_services',
            'days': 10,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'homemaker', 'daily_wage', 'self_employed'], 'label': 'Rural Household / Homemaker', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['farmer', 'homemaker', 'daily_wage', 'self_employed']},
            'docs': ['Aadhaar Card', 'Anganwadi Registration'],
            'url': 'https://poshanabhiyaan.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'wcd-sakhi-niwas-138',
            'code': 'SAKHI-NIWAS-HOSTEL',
            'name': 'Sakhi Niwas (Working Women Hostel Scheme)',
            'short_name': 'Sakhi Niwas Hostel',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['working_women', 'women'],
            'desc': 'Safe and conveniently located accommodation for working women with daycare facilities for their children (up to 18 years for girls and 5 years for boys) in urban and peri-urban centers.',
            'benefit': 'Subsidized safe boarding, lodging, security, and attached creche',
            'quantum': 'Subsidized Accommodation',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Employed Female Citizen', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'salaried', 'self_employed'], 'label': 'Working in Urban/Semi-Urban Area', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['employed', 'salaried', 'self_employed']},
            'docs': ['Employment Offer Letter / Salary Slip', 'Aadhaar Card', 'ID Card'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'wcd-ksy-empower-139',
            'code': 'KISHORI-SHAKTI',
            'name': 'Kishori Shakti Yojana (KSY)',
            'short_name': 'Kishori Shakti Yojana',
            'ministry': 'Ministry of Women and Child Development',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['adolescent_girls'],
            'desc': 'Community-based holistic development scheme for adolescent girls (11-18 years) focusing on self-development, nutrition awareness, menstrual hygiene, and non-formal functional literacy.',
            'benefit': 'Free health examination kits, sanitary pads, and adolescent literacy camps',
            'quantum': 'Free Health, Hygiene & Training Kits',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Candidate', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 11, 'label': 'Age Between 11 and 18', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 18, 'label': 'Age ≤ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 11, 'age_max': 18},
            'docs': ['Aadhaar Card', 'School ID or Anganwadi Card'],
            'url': 'https://wcd.nic.in',
            'completeness': 'VERIFIED'
        }
    ]
