# scripts/catalog_social_security.py

def get_schemes():
    return [
        {
            'id': 'nsap-ignwps-140',
            'code': 'IGNWPS',
            'name': 'Indira Gandhi National Widow Pension Scheme',
            'short_name': 'IGNWPS Widow Pension',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'pension',
            'beneficiary_types': ['widow', 'bpl'],
            'desc': 'Monthly pension of ₹300 (supplemented up to ₹1,000-₹2,500 by States) to BPL widows aged between 40 and 79 years living below poverty line.',
            'benefit': 'Monthly direct bank pension of ₹300 - ₹1,500 for lifelong sustenance',
            'quantum': '₹300 - ₹1,500 / month',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Widow', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 40, 'label': 'Age ≥ 40 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 79, 'label': 'Age ≤ 79 Years', 'impact': 'critical'},
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Family Status', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 40, 'age_max': 79, 'bpl_required': True},
            'docs': ['Death Certificate of Husband', 'Aadhaar Card', 'BPL Ration Card', 'Bank Passbook'],
            'url': 'https://nsap.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'nsap-nfbs-141',
            'code': 'NFBS',
            'name': 'National Family Benefit Scheme',
            'short_name': 'NFBS Lump Sum Aid',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['bereaved_family', 'bpl'],
            'desc': 'Lump sum cash assistance of ₹20,000 to a BPL household on the death of the primary breadwinner (aged 18 to 59 years).',
            'benefit': 'One-time immediate DBT cash grant of ₹20,000 to the surviving head of household',
            'quantum': '₹20,000 one-time grant',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Household', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 100000, 'label': 'Annual Household Income ≤ ₹1,00,000', 'impact': 'critical'}
            ],
            'flatRules': {'bpl_required': True, 'income_limit': 100000},
            'docs': ['Death Certificate of Primary Breadwinner', 'BPL Card', 'Bank Account Details of Nominee', 'Legal Heir / Family Certificate'],
            'url': 'https://nsap.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-nps-traders-142',
            'code': 'NPS-TRADERS',
            'name': 'National Pension Scheme for Traders and Self-Employed Persons (PM-LVM)',
            'short_name': 'PM Laghu Vyapari Mandhan',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'pension',
            'beneficiary_types': ['shopkeeper', 'retail_trader', 'self_employed'],
            'desc': 'Voluntary contributory pension scheme ensuring ₹3,000 monthly pension on attaining 60 years for shopkeepers, retail traders, and self-employed persons with annual turnover ≤ ₹1.5 Crore.',
            'benefit': 'Guaranteed ₹3,000 monthly pension from age 60 with 50% matching government co-contribution',
            'quantum': '₹3,000 / month guaranteed pension',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'trader'], 'label': 'Trader / Shopkeeper / Self Employed', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Entry Age Between 18 and 40', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 40, 'label': 'Entry Age ≤ 40 Years', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'trader'], 'age_min': 18, 'age_max': 40},
            'docs': ['Aadhaar Card', 'Savings Bank Passbook / Jan Dhan Account', 'GSTIN (if registered)'],
            'url': 'https://maandhan.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'fin-pmvvy-senior-143',
            'code': 'PMVVY',
            'name': 'Pradhan Mantri Vaya Vandana Yojana',
            'short_name': 'PM Vaya Vandana',
            'ministry': 'Ministry of Finance',
            'state': 'All-India',
            'category': 'pension',
            'beneficiary_types': ['senior_citizen'],
            'desc': 'Government-guaranteed pension scheme operated via LIC providing an assured payout rate of 7.40% p.a. payable monthly for 10 years for citizens aged 60+.',
            'benefit': 'Guaranteed monthly pension of ₹1,000 to ₹9,250 for 10 years backed by sovereign guarantee',
            'quantum': '₹1,000 - ₹9,250 / month assured return',
            'type': 'direct_benefit',
            'days': 10,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 60, 'label': 'Senior Citizen (Age 60+)', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 60},
            'docs': ['Aadhaar Card', 'Age Proof Certificate', 'Bank Account Details', 'Purchase Price Cheque'],
            'url': 'https://licindia.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'fin-nps-all-citizens-144',
            'code': 'NPS-ALL-CITIZEN',
            'name': 'National Pension System - All Citizen Model',
            'short_name': 'NPS Tier 1 Citizen Pension',
            'ministry': 'Ministry of Finance',
            'state': 'All-India',
            'category': 'pension',
            'beneficiary_types': ['citizen', 'employed', 'self_employed'],
            'desc': 'Market-linked, low-cost retirement savings vehicle regulated by PFRDA offering tax deduction up to ₹2 Lakh under Sec 80C and Sec 80CCD(1B) with compounded wealth creation.',
            'benefit': 'Lump sum corpus withdrawal (up to 60% tax-free) + lifelong monthly annuity pension',
            'quantum': 'Tax Deduction up to ₹2,00,000 & Monthly Annuity',
            'type': 'direct_benefit',
            'days': 3,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Citizen Aged 18 to 70 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 70, 'label': 'Age ≤ 70 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18, 'age_max': 70},
            'docs': ['Aadhaar Card', 'PAN Card', 'Bank Account Proof', 'Cancelled Cheque'],
            'url': 'https://enps.nsdl.com',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-esic-benefits-145',
            'code': 'ESIC-SCHEME',
            'name': 'Employees\' State Insurance Social Security Scheme',
            'short_name': 'ESIC Healthcare & Cash Benefits',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'insurance',
            'beneficiary_types': ['salaried', 'factory_worker', 'organized_worker'],
            'desc': 'Comprehensive social security cover providing full medical care, sickness cash benefit (70% wages), maternity benefit (100% wages for 26 weeks), and permanent disablement pension.',
            'benefit': '100% free cashless hospitalization for entire family + wage replacement cash benefits',
            'quantum': 'Cashless Super-Speciality Hospitalization & Wage Replacement',
            'type': 'in_kind_and_services',
            'days': 5,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed'], 'label': 'Formal Sector Employee', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 252000, 'label': 'Monthly Wage ≤ ₹21,000 (Annual ≤ ₹2.52 Lakh)', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed'], 'income_limit': 252000},
            'docs': ['Pehchan Card / ESIC E-Pehchan', 'Aadhaar Card', 'Wage Slip'],
            'url': 'https://www.esic.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-epfo-eps95-146',
            'code': 'EPFO-EPS95',
            'name': 'Employees\' Pension Scheme 1995 (EPS-95)',
            'short_name': 'EPFO Minimum Pension',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'pension',
            'beneficiary_types': ['salaried', 'retired', 'organized_worker'],
            'desc': 'Statutory guaranteed pension scheme under EPFO providing superannuation, early pension, widow/children pension, and orphan pension with guaranteed minimum ₹1,000/month.',
            'benefit': 'Lifelong monthly pension + spouse widow pension upon death',
            'quantum': 'Monthly Pension (Minimum ₹1,000 / month)',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 50, 'label': 'Age ≥ 50 for reduced / 58 for regular pension', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 50},
            'docs': ['UAN Number', 'EPFO Scheme Certificate (Form 10C/10D)', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://www.epfindia.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-edli-insurance-147',
            'code': 'EDLI-INSURANCE',
            'name': 'Employees\' Deposit Linked Insurance Scheme (EDLI)',
            'short_name': 'EDLI Life Insurance Cover',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'insurance',
            'beneficiary_types': ['salaried', 'organized_worker', 'nominee'],
            'desc': 'Life insurance benefit provided to the registered nominee of active EPF members dying while in service, offering up to ₹7,00,000 cash benefit without any employee contribution.',
            'benefit': 'Lump sum life insurance payout up to ₹7 Lakh directly credited to family nominee',
            'quantum': 'Up to ₹7,00,000 life insurance claim',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed'], 'label': 'Active EPF Member', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed']},
            'docs': ['Member Death Certificate', 'EPF Form 5IF', 'Nominee Aadhaar & Bank Passbook', 'Cancelled Cheque'],
            'url': 'https://www.epfindia.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-rashtriya-vayoshri-148',
            'code': 'RASHTRIYA-VAYOSHRI',
            'name': 'Rashtriya Vayoshri Yojana (RVY)',
            'short_name': 'Rashtriya Vayoshri Yojana',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'senior_citizens',
            'beneficiary_types': ['senior_citizen', 'bpl'],
            'desc': 'Free distribution of assisted-living physical aids and assisted-living devices (hearing aids, wheelchairs, walkers, spectacles, artificial teeth) for BPL senior citizens aged 60+.',
            'benefit': '100% free high-quality assistive physical devices and mobility aids',
            'quantum': 'Free Assistive Medical Devices (Worth up to ₹25,000)',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 60, 'label': 'Senior Citizen (Age 60+)', 'impact': 'critical'},
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Card / Monthly Pensioner', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 60, 'bpl_required': True},
            'docs': ['Aadhaar Card', 'BPL Card or Monthly Pension Certificate', 'Medical Officer Assessment Certificate'],
            'url': 'https://alimco.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-smile-livelihood-149',
            'code': 'SMILE-SCHEME',
            'name': 'Support for Marginalized Individuals for Livelihood and Enterprise (SMILE)',
            'short_name': 'SMILE Rehabilitation',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'livelihood',
            'beneficiary_types': ['transgender', 'marginalized', 'destitute'],
            'desc': 'Comprehensive rehabilitation for persons engaged in begging and transgender persons, providing skill training, housing, medical coverage, and entrepreneurship loans.',
            'benefit': 'Free skill development, PM-JAY medical card up to ₹5 Lakh, and ₹12,000 stipend during training',
            'quantum': 'Free Skill Training + Medical Insurance + Stipend',
            'type': 'in_kind_and_services',
            'days': 21,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['transgender', 'destitute', 'marginalized', 'sc', 'st', 'obc', 'general'], 'label': 'Vulnerable or Marginalized Individual', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['transgender', 'destitute', 'marginalized', 'sc', 'st', 'obc', 'general']},
            'docs': ['Aadhaar Card or Transgender Certificate / Local Administration Survey Slip'],
            'url': 'https://transgender.dosje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-transgender-portal-150',
            'code': 'TRANSGENDER-ID-CARD',
            'name': 'National Portal for Transgender Persons Certificate & Identity Card',
            'short_name': 'National Transgender ID Card',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['transgender'],
            'desc': 'End-to-end digital issuance of government-recognized Transgender Identity Card and Certificate with zero physical visit required, unlocking welfare entitlements and Ayushman TG Card.',
            'benefit': 'Official Transgender Identity Certificate + Ayushman TG Package with Gender Affirmation Cover',
            'quantum': 'Government Certification & ₹5,00,000 Ayushman TG Health Cover',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'IN', 'value': ['transgender', 'other'], 'label': 'Transgender Individual', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['transgender', 'other']},
            'docs': ['Aadhaar Card', 'Self Affidavit of Identity', 'Recent Photograph'],
            'url': 'https://transgender.dosje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-safai-karamchari-151',
            'code': 'SRMS-SCHEME',
            'name': 'Self Employment Scheme for Rehabilitation of Manual Scavengers (SRMS / NAMASTE)',
            'short_name': 'NAMASTE Sanitation Worker Support',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'livelihood',
            'beneficiary_types': ['sanitation_worker', 'manual_scavenger', 'sc'],
            'desc': 'One-time cash assistance of ₹40,000, skill development training with ₹3,000 monthly stipend, and capital subsidy up to ₹5 Lakh for mechanization equipment (sewer cleaning machines).',
            'benefit': '₹40,000 OTCA cash grant + ₹5,00,000 capital subsidy on sanitation machinery',
            'quantum': '₹40,000 Cash + ₹5,00,000 Capital Subsidy',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['sanitation_worker', 'daily_wage', 'unorganized_worker'], 'label': 'Sanitation Worker / Manual Scavenger Family', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['sanitation_worker', 'daily_wage', 'unorganized_worker']},
            'docs': ['Aadhaar Card', 'Survey Identification Card / Urban Local Body Certificate', 'Bank Passbook'],
            'url': 'https://srms.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-avay-elderly-152',
            'code': 'AVAY-SENIOR-HOMES',
            'name': 'Atal Vayo Abhyuday Yojana (AVAY - Senior Citizen Shelter Homes)',
            'short_name': 'AVAY Senior Citizen Homes',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'senior_citizens',
            'beneficiary_types': ['senior_citizen', 'destitute_elderly'],
            'desc': 'Free residential accommodation, nutritious food, healthcare, clothing, and recreational facilities in state-supported Senior Citizen Homes for destitute elderly with no family support.',
            'benefit': '100% free food, shelter, clothing, and primary health monitoring for elderly',
            'quantum': 'Free Residential Institutional Shelter',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 60, 'label': 'Senior Citizen (Age 60+)', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 60000, 'label': 'Indigent / Annual Income ≤ ₹60,000', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 60, 'income_limit': 60000},
            'docs': ['Aadhaar Card (if available)', 'Medical Fitness Certificate', 'Local Authority Recommendation'],
            'url': 'https://socialjustice.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'food-aay-antyodaya-153',
            'code': 'AAY-RATION',
            'name': 'Antyodaya Anna Yojana (AAY - Heaviest Subsidized Grain)',
            'short_name': 'Antyodaya Anna Yojana (AAY)',
            'ministry': 'Ministry of Consumer Affairs, Food and Public Distribution',
            'state': 'All-India',
            'category': 'food_nutrition',
            'beneficiary_types': ['poorest_of_poor', 'bpl', 'disabled'],
            'desc': 'Provides 35 kg of food grains (wheat and rice) per family per month completely free of cost to the poorest of the poor households under NFSA / PMGKAY.',
            'benefit': '35 kg free grain allocation every month (100% subsidized)',
            'quantum': '35 kg Foodgrains / month (Free)',
            'type': 'in_kind_and_services',
            'days': 15,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'Poorest of Poor / Yellow AAY Card Holder', 'impact': 'critical'}
            ],
            'flatRules': {'bpl_required': True},
            'docs': ['Antyodaya Ration Card', 'Aadhaar Card of Family Head'],
            'url': 'https://nfsa.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'food-onorc-portability-154',
            'code': 'ONORC-PORTABILITY',
            'name': 'One Nation One Ration Card (ONORC)',
            'short_name': 'ONORC Nationwide Portability',
            'ministry': 'Ministry of Consumer Affairs, Food and Public Distribution',
            'state': 'All-India',
            'category': 'food_nutrition',
            'beneficiary_types': ['migrant_worker', 'bpl', 'unorganized_worker'],
            'desc': 'Nationwide portability of NFSA ration cards enabling migrant laborers to lift their food grain quota from any Fair Price Shop (FPS) across India using biometric authentication.',
            'benefit': 'Doorstep interstate portability of monthly foodgrain quota anywhere in India',
            'quantum': 'Universal Inter-State Grain Access',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'Valid NFSA / State Ration Cardholder', 'impact': 'critical'}
            ],
            'flatRules': {'bpl_required': True},
            'docs': ['Ration Card Number', 'Aadhaar Number (Biometric ePoS Authentication)'],
            'url': 'https://nfsa.gov.in/portal/onorc',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-relief-pmnrf-155',
            'code': 'PMNRF-RELIEF',
            'name': 'Prime Minister\'s National Relief Fund (PMNRF)',
            'short_name': 'PMNRF Medical & Distress Relief',
            'ministry': 'Prime Minister\'s Office',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['distressed_citizen', 'cancer_patients', 'disaster_victims'],
            'desc': 'Immediate financial assistance for medical treatments like heart surgeries, kidney transplants, cancer treatment, and relief to families of individuals killed in major natural calamities.',
            'benefit': 'Direct grant up to ₹3,00,000 for hospital medical procedures or casualty relief',
            'quantum': 'Up to ₹3,00,000 grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Household Annual Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 250000},
            'docs': ['Aadhaar Card', 'Hospital Medical Estimate Certificate', 'Income Certificate', 'Two Passport Photographs'],
            'url': 'https://pmnrf.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-elderline-156',
            'code': 'ELDERLINE-14567',
            'name': 'Elderline - National Helpline for Senior Citizens (Toll-Free 14567)',
            'short_name': 'Elderline 14567 Assistance',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'senior_citizens',
            'beneficiary_types': ['senior_citizen'],
            'desc': '24x7 toll-free helpline service across all States offering free tele-counselling, legal dispute resolution, rescue of abandoned elderly, and access to old-age homes.',
            'benefit': 'Free legal advocacy, psychological counselling, and immediate physical rescue',
            'quantum': 'Free 24x7 Emergency Social Protection',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 60, 'label': 'Citizen Aged 60 Years or Older', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 60},
            'docs': ['Aadhaar Card / Self Identity Confirmation'],
            'url': 'https://elderline.dosje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'fin-sukanya-samriddhi-extra-157',
            'code': 'SSY-TOPUP',
            'name': 'Sukanya Samriddhi High-Yield Small Savings Account',
            'short_name': 'Sukanya Samriddhi Sovereign Deposit',
            'ministry': 'Ministry of Finance',
            'state': 'All-India',
            'category': 'financial_inclusion',
            'beneficiary_types': ['girl_child', 'parents'],
            'desc': 'Highest-yielding small savings sovereign scheme (8.2% p.a.) with EEE tax-exempt status under Sec 80C for female children below 10 years of age.',
            'benefit': '8.2% compounded annual tax-free interest for higher education and marriage',
            'quantum': '8.2% Tax-Free Compound Growth',
            'type': 'direct_benefit',
            'days': 3,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Child', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 10, 'label': 'Age ≤ 10 Years at Account Opening', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_max': 10},
            'docs': ['Birth Certificate of Child', 'Parent Aadhaar Card', 'Parent PAN Card'],
            'url': 'https://www.indiapost.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'postal-plia-rural-158',
            'code': 'RPLI-INSURANCE',
            'name': 'Rural Postal Life Insurance (RPLI - Gramin Dak Jeevan Bima)',
            'short_name': 'Rural Postal Life Insurance',
            'ministry': 'Ministry of Communications',
            'state': 'All-India',
            'category': 'insurance',
            'beneficiary_types': ['rural_citizen', 'farmer', 'artisan'],
            'desc': 'Government-backed lowest premium life insurance with highest declared bonus rates for residents of rural areas, offering endowment and whole life policies.',
            'benefit': 'High bonus life cover up to ₹10 Lakh with doorstep premium collection',
            'quantum': 'Up to ₹10,00,000 Life Insurance Sum Assured',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 19, 'label': 'Age Between 19 and 55', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 55, 'label': 'Age ≤ 55 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 19, 'age_max': 55},
            'docs': ['Aadhaar Card', 'Rural Address Proof', 'Age Proof Certificate', 'Medical Examination Report'],
            'url': 'https://postallifeinsurance.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sje-dr-ambedkar-foundation-159',
            'code': 'DAF-INTERCASTE-MARRIAGE',
            'name': 'Dr. Ambedkar Scheme for Social Integration through Inter-Caste Marriages',
            'short_name': 'Ambedkar Inter-Caste Marriage Incentive',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['newlyweds', 'sc'],
            'desc': 'Incentive of ₹2,50,000 to newly married couples where one spouse belongs to Scheduled Caste and the other belongs to a Non-Scheduled Caste.',
            'benefit': '₹2,50,000 incentive paid as fixed deposit and direct bank credit',
            'quantum': '₹2,50,000 incentive grant',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['sc', 'general', 'obc'], 'label': 'Inter-Caste Marriage (SC with Non-SC)', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Legal Age for Marriage', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc', 'general', 'obc'], 'age_min': 18},
            'docs': ['Marriage Registration Certificate under Special Marriage Act', 'SC Caste Certificate of Spouse', 'Joint Bank Account Passbook'],
            'url': 'https://ambedkarfoundation.nic.in',
            'completeness': 'VERIFIED'
        }
    ]
