# scripts/catalog_labour.py

def get_schemes():
    return [
        {
            'id': 'labour-eshram-200',
            'code': 'E-SHRAM',
            'name': 'e-Shram National Database of Unorganised Workers',
            'short_name': 'e-Shram Universal Social Security Card',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'labour_workers',
            'beneficiary_types': ['unorganized_worker', 'migrant_worker', 'daily_wage', 'domestic_worker'],
            'desc': 'National registration granting a 12-digit Universal Account Number (UAN) and ₹2,00,000 accidental death insurance and ₹1,00,000 permanent disability cover under PMSBY.',
            'benefit': 'Free ₹2,00,000 accidental death insurance cover + direct disaster relief transfer linkage',
            'quantum': '₹2,00,000 Accidental Insurance Cover',
            'type': 'insurance',
            'days': 1,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 16, 'label': 'Age Between 16 and 59', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 59, 'label': 'Age ≤ 59 Years', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'artisan', 'farmer', 'self_employed'], 'label': 'Unorganized Sector Worker', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 16, 'age_max': 59, 'occupation': ['daily_wage', 'unorganized_worker', 'artisan', 'farmer', 'self_employed']},
            'docs': ['Aadhaar Card', 'Aadhaar-Linked Active Mobile Number', 'Bank Savings Account Passbook'],
            'url': 'https://eshram.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-mgnrega-guarantee-201',
            'code': 'MGNREGA',
            'name': 'Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)',
            'short_name': 'MGNREGA 100 Days Wage Guarantee',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'employment',
            'beneficiary_types': ['rural_worker', 'daily_wage', 'unskilled_worker'],
            'desc': 'Statutory legal guarantee of 100 days of unskilled manual wage employment in every financial year to adult members of any rural household willing to do public works.',
            'benefit': 'Guaranteed 100 days statutory wage employment (₹240 - ₹374 per day DBT depending on state)',
            'quantum': '100 Days Guaranteed Wage Employment',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Adult Resident (Age ≥ 18)', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'farmer', 'homemaker'], 'label': 'Rural Manual Labourer', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18, 'occupation': ['daily_wage', 'unorganized_worker', 'farmer', 'homemaker']},
            'docs': ['MGNREGA Job Card', 'Aadhaar Card', 'Bank/Post Office Passbook'],
            'url': 'https://nrega.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-bocw-welfare-202',
            'code': 'BOCW-REGISTRATION',
            'name': 'Building and Other Construction Workers Welfare Board Benefits (BOCW)',
            'short_name': 'BOCW Construction Worker Welfare',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'labour_workers',
            'beneficiary_types': ['construction_worker', 'mason', 'painter', 'carpenter'],
            'desc': 'State welfare board registration for construction workers offering free medical assistance, child educational scholarships up to ₹20,000, daughter marriage grant up to ₹51,000.',
            'benefit': '₹51,000 marriage assistance, ₹20,000 education scholarships, and free accidental cover',
            'quantum': 'Comprehensive Board Cash & Welfare Grants',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age Between 18 and 60', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 60, 'label': 'Age ≤ 60 Years', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['construction_worker', 'mason', 'daily_wage', 'artisan'], 'label': 'Construction Worker (Worked 90+ days in past year)', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18, 'age_max': 60, 'occupation': ['construction_worker', 'mason', 'daily_wage', 'artisan']},
            'docs': ['90-Day Work Certificate from Contractor/Engineer/Gram Panchayat', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://labour.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-ddu-gky-skilling-203',
            'code': 'DDU-GKY',
            'name': 'Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)',
            'short_name': 'DDU-GKY Rural Skilling',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['rural_youth', 'unemployed', 'sc', 'st', 'bpl'],
            'desc': 'Placement-linked skill training for rural poor youth (15-35 years) with 100% free residential boarding, food, uniforms, tablet computers, and mandatory 70% placement.',
            'benefit': '100% free residential certified skilling + tablet computer + post-placement support stipend',
            'quantum': 'Free Residential Skilling & Guaranteed Placement',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 15, 'label': 'Age Between 15 and 35 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 35, 'label': 'Age ≤ 35 Years (Up to 45 for SC/ST/Women)', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 15, 'age_max': 35},
            'docs': ['Aadhaar Card', 'BPL Card / MGNREGA Job Card of Family', 'School Leaving Certificate'],
            'url': 'https://ddugky.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-ncs-portal-204',
            'code': 'NCS-CAREER-PORTAL',
            'name': 'National Career Service (NCS Portal Employment Services)',
            'short_name': 'National Career Service (NCS)',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'employment',
            'beneficiary_types': ['jobseeker', 'youth', 'graduate'],
            'desc': 'Digital matchmaking portal connecting jobseekers with verified private and public employers, offering career counselling, job fairs, vocational guidance, and skill courses.',
            'benefit': 'Free job application access, job fair invites, and free career counselling',
            'quantum': 'Free Employment Exchange & Matchmaking Services',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18},
            'docs': ['Aadhaar Card', 'Educational Qualifications / Resume', 'Passport Photograph'],
            'url': 'https://www.ncs.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-naps-apprenticeship-205',
            'code': 'NAPS-APPRENTICE',
            'name': 'National Apprenticeship Promotion Scheme (NAPS)',
            'short_name': 'NAPS Apprenticeship Stipend',
            'ministry': 'Ministry of Skill Development and Entrepreneurship',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['apprentice', 'iti_pass', 'diploma_holder', 'graduate'],
            'desc': 'Direct stipend support of 25% of prescribed stipend up to ₹1,500 per month paid directly by Government of India into apprentice\'s bank account during on-the-job industrial training.',
            'benefit': 'Government DBT stipend up to ₹1,500/month + National Apprenticeship Certificate',
            'quantum': '₹1,500 / month Government DBT Stipend',
            'type': 'direct_benefit',
            'days': 14,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 14, 'label': 'Age ≥ 14 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 14},
            'docs': ['Aadhaar Card', '10th / 12th / ITI / Polytechnic Marksheet', 'Bank Passbook'],
            'url': 'https://www.apprenticeshipindia.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-pm-daksh-206',
            'code': 'PM-DAKSH',
            'name': 'Pradhan Mantri Dakshta Aur Kushalta Sampann Hitgrahi (PM-DAKSH)',
            'short_name': 'PM-DAKSH Skilling Stipend',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['sc', 'obc', 'ebc', 'dnt', 'sanitation_worker'],
            'desc': 'Free up-skilling, re-skilling, short-term and long-term training for SC, OBC, EBC, DNT, and sanitation workers, with 100% course cost paid and stipend up to ₹1,500/month (80% attendance).',
            'benefit': 'Free high-tech training + ₹1,000 - ₹1,500 monthly stipend + placement assistance',
            'quantum': 'Free Skilling + ₹1,500 Monthly Stipend',
            'type': 'in_kind_and_services',
            'days': 21,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age Between 18 and 45 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 45, 'label': 'Age ≤ 45 Years', 'impact': 'critical'},
                {'field': 'citizen.category', 'op': 'IN', 'value': ['sc', 'obc', 'ebc', 'general'], 'label': 'SC / OBC / EBC / Safai Karamchari Target Group', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18, 'age_max': 45, 'category': ['sc', 'obc', 'ebc', 'general']},
            'docs': ['Caste Certificate (for SC/OBC)', 'Income Certificate (for OBC/EBC)', 'Aadhaar Card'],
            'url': 'https://pmdaksh.dosje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-pmkvy-rpl-207',
            'code': 'PMKVY-RPL',
            'name': 'PMKVY Recognition of Prior Learning (RPL Skill Certification)',
            'short_name': 'PMKVY RPL Skill Certification',
            'ministry': 'Ministry of Skill Development and Entrepreneurship',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['unorganized_worker', 'artisan', 'craftsperson'],
            'desc': 'Formal assessment and NSDC skill certification of informal industry workers without formal qualifications, providing ₹500 DBT reward, personal accidental insurance, and digital skill card.',
            'benefit': 'Government Skill Certificate + ₹500 DBT incentive + 3-year free accidental insurance',
            'quantum': '₹500 DBT + Official Skill Certificate',
            'type': 'direct_benefit',
            'days': 10,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years with prior work experience', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18},
            'docs': ['Aadhaar Card', 'Self-Declaration of Work Experience', 'Bank Passbook'],
            'url': 'https://www.pmkvyofficial.org',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-beedi-workers-housing-208',
            'code': 'BEEDI-WORKERS-WELFARE',
            'name': 'Beedi Workers Welfare Fund (Revised Integrated Housing Scheme)',
            'short_name': 'Beedi Workers Housing Subsidy',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['beedi_worker', 'unorganized_worker'],
            'desc': 'Direct subsidy of ₹1,50,000 for construction of a pucca house for registered beedi, iron ore, manganese ore, chrome ore, and limestone workers.',
            'benefit': '₹1,50,000 non-refundable housing subsidy in 3 bank installments',
            'quantum': '₹1,50,000 housing subsidy',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['beedi_worker', 'unorganized_worker', 'daily_wage'], 'label': 'Registered Beedi / Mine Worker', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['beedi_worker', 'unorganized_worker', 'daily_wage']},
            'docs': ['Beedi Worker Identity Card (LWWF Card)', 'Land Patta / Ownership Deed', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://labour.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-bocw-maternity-209',
            'code': 'BOCW-MATERNITY',
            'name': 'BOCW Female Construction Worker Maternity Cash Benefit',
            'short_name': 'BOCW Maternity Assistance',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'women_child',
            'beneficiary_types': ['construction_worker', 'pregnant_women'],
            'desc': 'Direct cash assistance of ₹15,000 to ₹25,000 per delivery (up to two deliveries) for registered female construction workers to compensate for wage loss during childbirth.',
            'benefit': '₹15,000 - ₹25,000 DBT cash benefit for maternal rest and nutrition',
            'quantum': '₹20,000 maternity cash benefit',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Registered Construction Worker', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['construction_worker', 'daily_wage'], 'label': 'BOCW Board Member for ≥ 1 Year', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['construction_worker', 'daily_wage']},
            'docs': ['BOCW Registration Smart Card', 'Child Birth Certificate / Hospital Discharge Slip', 'Bank Passbook'],
            'url': 'https://labour.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-bocw-toolkit-210',
            'code': 'BOCW-TOOLKIT-GRANT',
            'name': 'BOCW Construction Worker Tool-Kit Assistance Scheme',
            'short_name': 'BOCW Tool-Kit Purchase Grant',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'labour_workers',
            'beneficiary_types': ['construction_worker', 'artisan', 'mason'],
            'desc': 'Financial assistance or reimbursement up to ₹10,000 for purchasing trade-specific modern equipment and toolkits (masonry, carpentry, bar bending, painting, plumbing).',
            'benefit': 'Free modern trade toolkit or ₹10,000 reimbursement directly to bank',
            'quantum': '₹10,000 Toolkit Subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['construction_worker', 'mason', 'artisan'], 'label': 'Registered BOCW Construction Artisan', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['construction_worker', 'mason', 'artisan']},
            'docs': ['BOCW Registration Card', 'Toolkit Purchase GST Bill', 'Aadhaar Card'],
            'url': 'https://labour.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-rsetis-rural-211',
            'code': 'RSETI-SCHEME',
            'name': 'Rural Self Employment Training Institutes (RSETI) Free Vocational Courses',
            'short_name': 'RSETI Self-Employment Skilling',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['rural_youth', 'unemployed', 'women'],
            'desc': 'Free short-term residential courses (1 to 6 weeks) in over 60 vocations with 100% free food, hostel, study material, and bank credit credit linkage for self-employment ventures.',
            'benefit': '100% free residential vocational training with fast-tracked bank credit facilitation',
            'quantum': 'Free Residential Training & Fast-Track Mudra Loan Linkage',
            'type': 'in_kind_and_services',
            'days': 15,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age Between 18 and 45', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 45, 'label': 'Age ≤ 45 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18, 'age_max': 45},
            'docs': ['Aadhaar Card', 'School Leaving Certificate', 'Ration Card / BPL Card'],
            'url': 'https://rudseti.org',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-beedi-scholarship-212',
            'code': 'BEEDI-SCHOLARSHIP',
            'name': 'Financial Assistance for Education of Children of Beedi/Cine/Mine Workers',
            'short_name': 'Beedi Worker Child Education Scholarship',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['beedi_worker', 'students'],
            'desc': 'Annual scholarship from ₹1,000 (Class 1) up to ₹25,000 (Professional Degrees like MBBS/BTech) for wards of registered beedi, cine, and non-coal mine workers.',
            'benefit': '₹1,000 to ₹25,000 annual education grant directly transferred to student bank account',
            'quantum': '₹1,000 - ₹25,000 / year scholarship',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Student Child of Registered Worker', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student']},
            'docs': ['Parent Beedi/Mine Worker Identity Card', 'Student School Bonafide Certificate', 'Bank Passbook of Student'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-bocw-daughter-marriage-213',
            'code': 'BOCW-MARRIAGE-AID',
            'name': 'BOCW Daughter Marriage Financial Assistance',
            'short_name': 'BOCW Daughter Marriage Grant',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'social_security',
            'beneficiary_types': ['construction_worker', 'women'],
            'desc': 'Financial grant of ₹31,000 to ₹51,000 for the marriage of up to two adult daughters of registered construction workers who have maintained continuous board membership.',
            'benefit': '₹31,000 - ₹51,000 cash grant for marriage expenses of daughter',
            'quantum': '₹51,000 marriage grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['construction_worker', 'mason', 'daily_wage'], 'label': 'Registered Construction Worker', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['construction_worker', 'mason', 'daily_wage']},
            'docs': ['Daughter Age Proof (≥ 18 Years)', 'Marriage Card / Registration Certificate', 'BOCW Passbook'],
            'url': 'https://labour.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-interstate-migrant-transit-214',
            'code': 'MIGRANT-WORKER-TRANSIT',
            'name': 'Interstate Migrant Worker Transit Assistance Scheme',
            'short_name': 'Interstate Migrant Transit Aid',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'labour_workers',
            'beneficiary_types': ['migrant_worker', 'unorganized_worker'],
            'desc': 'Travel allowance reimbursement, transit housing, and emergency return fare assistance for interstate migrant workers registered under Inter-State Migrant Workmen Act.',
            'benefit': 'Full train/bus fare reimbursement and transit housing facilities during inter-state relocation',
            'quantum': 'Travel Allowance & Transit Shelter',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'construction_worker'], 'label': 'Inter-State Migrant Worker', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['daily_wage', 'unorganized_worker', 'construction_worker']},
            'docs': ['e-Shram Card', 'Travel Journey Tickets', 'Contractor Employment Memo'],
            'url': 'https://labour.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'labour-garib-kalyan-rojgar-215',
            'code': 'GARIB-KALYAN-ROJGAR',
            'name': 'Garib Kalyan Rojgar Abhiyaan (GKRA Rural Infrastructure Employment)',
            'short_name': 'Garib Kalyan Rojgar Abhiyaan',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'employment',
            'beneficiary_types': ['returnee_migrant', 'rural_worker'],
            'desc': 'Massive rural public works campaign focusing on 25 different target infrastructure works (community sanitations, gram panchayat bhawans, optical fibre laying) employing rural returnee migrants.',
            'benefit': 'Immediate wage employment on public infrastructure projects at statutory wage rates',
            'quantum': 'Guaranteed Public Works Wage',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'farmer'], 'label': 'Rural Worker / Returnee Migrant', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['daily_wage', 'unorganized_worker', 'farmer']},
            'docs': ['Aadhaar Card', 'Gram Panchayat Job Enrollment'],
            'url': 'https://rural.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-pmrpy-epf-subvention-216',
            'code': 'PMRPY-EPF-SUBVENTION',
            'name': 'Pradhan Mantri Rojgar Protsahan Yojana (PMRPY Employer EPF Subsidy)',
            'short_name': 'PMRPY EPF Wage Subsidy',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'employment',
            'beneficiary_types': ['salaried', 'employed', 'new_worker'],
            'desc': 'Government pays full employer\'s contribution (12% of wages) towards EPF and EPS for first 3 years for new employees earning up to ₹15,000 per month.',
            'benefit': 'Full 12% employer provident fund & pension contribution paid directly by Central Government',
            'quantum': '12% Employer Contribution Paid by Government',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed'], 'label': 'New Formal Sector Employee', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 180000, 'label': 'Monthly Wage ≤ ₹15,000 (Annual ≤ ₹1.80 Lakh)', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed'], 'income_limit': 180000},
            'docs': ['UAN Number linked with Aadhaar', 'Salary Slip'],
            'url': 'https://pmrpy.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'labour-shram-suvidha-217',
            'code': 'SHRAM-SUVIDHA',
            'name': 'Unified Shram Suvidha Portal Compliance & Labor Inspection Service',
            'short_name': 'Shram Suvidha Labour Portal',
            'ministry': 'Ministry of Labour and Employment',
            'state': 'All-India',
            'category': 'labour_workers',
            'beneficiary_types': ['worker', 'business', 'msme'],
            'desc': 'Single-window transparent platform assigning Labour Identification Number (LIN) ensuring transparent computerised risk-based inspections and wage compliance.',
            'benefit': 'Protection against arbitrary harassment, guaranteed minimum wage enforcement, and online returns',
            'quantum': 'Free Transparent Labour Rights Enforcement',
            'type': 'in_kind_and_services',
            'days': 5,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed', 'business', 'daily_wage'], 'label': 'Worker or Business Employer in Industrial Sector', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed', 'business', 'daily_wage']},
            'docs': ['Labour Identification Number (LIN) or Aadhaar Card'],
            'url': 'https://shramsuvidha.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        }
    ]
