# scripts/catalog_housing.py

def get_schemes():
    return [
        {
            'id': 'housing-pmay-u-blc-160',
            'code': 'PMAY-U-BLC',
            'name': 'PMAY Urban - Beneficiary Led Individual House Construction (BLC)',
            'short_name': 'PMAY-U Individual House Grant',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['urban_poor', 'ews', 'lig'],
            'desc': 'Direct central assistance of ₹1,50,000 per family for construction of new pucca house or enhancement of existing kutcha house on own land in statutory urban areas.',
            'benefit': '₹1,50,000 central grant + ₹1,00,000 state grant in direct bank installments',
            'quantum': '₹2,50,000 grant per house',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'IN', 'value': [True, False], 'label': 'EWS / Low Income Urban Resident', 'impact': 'moderate'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 300000, 'label': 'Annual Household Income ≤ ₹3.0 Lakh for EWS', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 300000},
            'docs': ['Land Ownership Title / Patta', 'Aadhaar Card of Family Head', 'Bank Passbook', 'Building Plan Approval / NOC'],
            'url': 'https://pmaymis.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-pmay-u-ahp-161',
            'code': 'PMAY-U-AHP',
            'name': 'PMAY Urban - Affordable Housing in Partnership (AHP)',
            'short_name': 'PMAY-U Affordable Flats',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['urban_poor', 'ews'],
            'desc': 'Central financial assistance of ₹1,50,000 per EWS house in projects where at least 35% of houses are constructed for EWS category by public/private agencies.',
            'benefit': 'Subsidy up to ₹1,50,000 off purchase price of government approved EWS flat',
            'quantum': '₹1,50,000 price discount subsidy',
            'type': 'capital_subsidy',
            'days': 60,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 300000, 'label': 'Household Income ≤ ₹3 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 300000},
            'docs': ['Aadhaar Card', 'Income Certificate issued by Tehsildar', 'Urban Local Body Allotment Letter'],
            'url': 'https://pmaymis.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-arhc-migrants-162',
            'code': 'ARHC-RENTAL',
            'name': 'Affordable Rental Housing Complexes (ARHCs for Migrants)',
            'short_name': 'ARHC Rental Housing for Migrants',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['migrant_worker', 'urban_poor', 'industrial_worker'],
            'desc': 'Sub-scheme under PMAY-U to provide ease of living to urban migrants/poor in the industrial/non-formal sector through low-cost rental housing close to work places.',
            'benefit': 'Dignified rental accommodation with electricity, water, and sanitation at nominal rent',
            'quantum': 'Subsidized Rental Accommodation',
            'type': 'in_kind_and_services',
            'days': 14,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'employed', 'artisan'], 'label': 'Urban Migrant / Industrial Worker', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['daily_wage', 'unorganized_worker', 'employed', 'artisan']},
            'docs': ['Aadhaar Card', 'Employer Certificate / Trade Union / Street Vendor ID'],
            'url': 'https://arhc.mohua.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-jjm-tapwater-163',
            'code': 'JAL-JEEVAN-MISSION',
            'name': 'Jal Jeevan Mission (Har Ghar Nal Se Jal)',
            'short_name': 'Jal Jeevan Mission',
            'ministry': 'Ministry of Jal Shakti',
            'state': 'All-India',
            'category': 'sanitation',
            'beneficiary_types': ['rural_citizen', 'all_citizens'],
            'desc': 'Universal provision of Functional Household Tap Connection (FHTC) delivering 55 litres of potable water per capita per day to every rural home by the government.',
            'benefit': 'Free treated piped drinking water connection to rural households',
            'quantum': 'Free Household Tap Water Installation',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'daily_wage', 'unorganized_worker', 'self_employed', 'homemaker'], 'label': 'Rural Resident Household', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['farmer', 'daily_wage', 'unorganized_worker', 'self_employed', 'homemaker']},
            'docs': ['Aadhaar Card', 'Gram Panchayat Residence Verification'],
            'url': 'https://jaljeevanmission.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-svamitva-cards-164',
            'code': 'SVAMITVA-SCHEME',
            'name': 'SVAMITVA Scheme (Survey of Villages and Mapping with Improvised Technology)',
            'short_name': 'SVAMITVA Property Card',
            'ministry': 'Ministry of Panchayati Raj',
            'state': 'All-India',
            'category': 'rural_development',
            'beneficiary_types': ['rural_citizen', 'farmer', 'property_owner'],
            'desc': 'Drone survey mapping of rural inhabited areas (Abadi) to issue official legal Property Cards, enabling rural citizens to use home assets as financial collateral for bank loans.',
            'benefit': 'Legal ownership record (Svamitva Card) with clear demarcation of rural property',
            'quantum': 'Legal Ownership Property Card',
            'type': 'in_kind_and_services',
            'days': 60,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'daily_wage', 'artisan', 'salaried'], 'label': 'Owner of Rural Abadi Land', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['farmer', 'self_employed', 'daily_wage', 'artisan', 'salaried']},
            'docs': ['Aadhaar Card', 'Gram Panchayat Tax Receipt / Family Chulha Tax Record'],
            'url': 'https://svamitva.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-day-nulm-suh-165',
            'code': 'DAY-NULM-SUH',
            'name': 'DAY-NULM Scheme of Shelter for Urban Homeless (SUH)',
            'short_name': 'Shelter for Urban Homeless',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['homeless', 'destitute', 'urban_poor'],
            'desc': 'Permanent, 24x7 all-weather shelters equipped with clean drinking water, sanitation, bedding, lockers, first aid, and social welfare linkage for roofless urban individuals.',
            'benefit': 'Free 24x7 shelter, hygienic beds, security, and healthcare linkage',
            'quantum': 'Free Night Shelter Facilities',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['daily_wage', 'unorganized_worker', 'destitute'], 'label': 'Urban Homeless Individual', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['daily_wage', 'unorganized_worker', 'destitute']},
            'docs': ['Identity Card (if available; no person turned away for lack of ID)'],
            'url': 'https://nulm.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-amrut-water-166',
            'code': 'AMRUT-MISSION',
            'name': 'Atal Mission for Rejuvenation and Urban Transformation (AMRUT 2.0)',
            'short_name': 'AMRUT 2.0 Urban Tap & Sewerage',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'sanitation',
            'beneficiary_types': ['urban_poor', 'citizen'],
            'desc': 'Achieving 100% universal coverage of water supply to all households across 4,700 statutory towns and 100% coverage of sewerage and septage management in 500 cities.',
            'benefit': 'Household water and sewerage network connections to urban families',
            'quantum': 'Subsidized Urban Household Connection',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'salaried', 'self_employed', 'daily_wage', 'business'], 'label': 'Resident of Statutory Town', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['employed', 'salaried', 'self_employed', 'daily_wage', 'business']},
            'docs': ['Property Tax Assessment Receipt', 'Aadhaar Card'],
            'url': 'https://amrut.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-pm-janman-house-167',
            'code': 'PM-JANMAN-AWAS',
            'name': 'PM-JANMAN Pucca House Scheme for PVTG Communities',
            'short_name': 'PM-JANMAN Tribal Pucca Awas',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['pvtg_tribal', 'st'],
            'desc': 'Enhanced assistance of ₹2,39,000 (including ₹2.0 Lakh house grant, ₹12,000 toilet grant, and 90 days MGNREGA wages) for Particularly Vulnerable Tribal Groups.',
            'benefit': '100% funded ₹2.39 Lakh pucca dwelling with solar light and water connection',
            'quantum': '₹2,39,000 grant per house',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Particularly Vulnerable Tribal Group (PVTG) / ST', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st']},
            'docs': ['Aadhaar Card', 'PVTG / ST Community Certificate', 'Bank Passbook'],
            'url': 'https://tribal.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-pm-subvention-urban-168',
            'code': 'PM-URBAN-HOUSING-SUBVENTION',
            'name': 'Interest Subvention Scheme for Urban Middle Class & EWS Housing',
            'short_name': 'Urban Housing Interest Subvention',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['middle_class', 'ews', 'lig'],
            'desc': 'Interest subsidy up to ₹1,80,000 on home loans up to ₹50 Lakh for purchasing or constructing first home in urban municipal limits for middle-class families living in rented homes.',
            'benefit': 'Up to ₹1.80 Lakh upfront interest subsidy credited to home loan account',
            'quantum': '₹1,80,000 interest subsidy',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 900000, 'label': 'Household Income ≤ ₹9 Lakh (EWS/LIG/MIG)', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 900000},
            'docs': ['Bank Home Loan Sanction Letter', 'Aadhaar Card', 'First Home Affidavit', 'Income Tax Returns / Form 16'],
            'url': 'https://pmay-urban.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-rural-mason-cert-169',
            'code': 'GRAMIN-RAJMISTRI',
            'name': 'Pradhan Mantri Gramin Rajmistri Training & Certification Scheme',
            'short_name': 'Gramin Rajmistri Certification',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['mason', 'rural_worker', 'artisan'],
            'desc': 'Formal skilling and qualification of rural construction masons with daily wage compensation during 45 days training, enabling certified construction of disaster-resilient PMAY-G houses.',
            'benefit': 'Free government certification, ₹9,000 wage compensation during skilling, and toolkit',
            'quantum': 'Free Skilling + ₹9,000 Stipend + Tool Kit',
            'type': 'in_kind_and_services',
            'days': 20,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'daily_wage', 'unorganized_worker'], 'label': 'Rural Construction Worker / Mason', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'daily_wage', 'unorganized_worker'], 'age_min': 18},
            'docs': ['Aadhaar Card', 'Gram Panchayat Recommendation Letter', 'Bank Passbook'],
            'url': 'https://pmayg.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-sbm-toilet-grant-170',
            'code': 'SBM-G-TOILET-TOPUP',
            'name': 'Swachh Bharat Mission (Grameen) Individual Household Latrine Grant',
            'short_name': 'IHHL Toilet Construction Grant',
            'ministry': 'Ministry of Jal Shakti',
            'state': 'All-India',
            'category': 'sanitation',
            'beneficiary_types': ['rural_citizen', 'bpl', 'sc', 'st'],
            'desc': 'Direct financial incentive of ₹12,000 for construction of Individual Household Latrine (IHHL) for rural households without sanitary toilets.',
            'benefit': '₹12,000 direct bank transfer upon geo-tagged photo verification of completed twin-pit toilet',
            'quantum': '₹12,000 cash grant',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'IN', 'value': [True, False], 'label': 'Rural Household without Sanitary Toilet', 'impact': 'critical'}
            ],
            'flatRules': {},
            'docs': ['Aadhaar Card', 'Bank Passbook', 'Geo-tagged Photograph of Toilet Structure'],
            'url': 'https://sbm.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-rera-protection-171',
            'code': 'RERA-BUYER-PROTECTION',
            'name': 'Real Estate (Regulation and Development) Act Homebuyer Redressal',
            'short_name': 'RERA Homebuyer Protection',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['homebuyer', 'citizen'],
            'desc': 'Statutory judicial mechanism guaranteeing refund with interest (SBI MCLR + 2%) or possession within deadline for real estate flat buyers against errant promoters.',
            'benefit': 'Legal enforcement of delayed possession penalty / full refund with interest',
            'quantum': 'Statutory Interest Refund & Adjudication',
            'type': 'in_kind_and_services',
            'days': 60,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed', 'business', 'self_employed'], 'label': 'Allottee of RERA Registered Housing Project', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed', 'business', 'self_employed']},
            'docs': ['Allotment Letter / Agreement for Sale', 'Payment Receipts', 'Promoter Communications'],
            'url': 'https://mohua.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-smart-cities-infra-172',
            'code': 'SMART-CITIES-INFRA',
            'name': 'Smart Cities Mission Citizen Infrastructure & Services',
            'short_name': 'Smart Cities Citizen Services',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['urban_poor', 'citizen'],
            'desc': 'Integrated Command and Control Centres (ICCC), smart mobility, open public parks, municipal digital service delivery, and public Wi-Fi across 100 lighthouse cities.',
            'benefit': 'Free digital urban civic services, real-time safety surveillance, and e-governance',
            'quantum': 'Municipal Smart Infrastructure Access',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'salaried', 'self_employed', 'student', 'homemaker'], 'label': 'Resident of 100 Designated Smart Cities', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['employed', 'salaried', 'self_employed', 'student', 'homemaker']},
            'docs': ['Municipal Resident Proof'],
            'url': 'https://smartcities.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-solitary-concession-173',
            'code': 'PMAY-SINGLE-WOMEN',
            'name': 'PMAY Priority Ownership for Single & Widow Women',
            'short_name': 'PMAY Female Co-Ownership Mandate',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['women', 'widow', 'single_women'],
            'desc': 'Statutory mandate that all houses sanctioned under PMAY (Urban and Gramin) must be registered in the name of the female head of household or in joint ownership with husband.',
            'benefit': 'Sole or joint legal property registry title favoring women',
            'quantum': 'Mandatory Legal Property Title Registration',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Head of Household / Co-Applicant', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card', 'Family Member Ration Card', 'Income Certificate'],
            'url': 'https://pmaymis.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-pm-devine-ne-174',
            'code': 'PM-DEVINE-INFRA',
            'name': 'Prime Minister\'s Development Initiative for North East Region (PM-DevINE)',
            'short_name': 'PM-DevINE Social Infrastructure',
            'ministry': 'Ministry of Development of North Eastern Region',
            'state': 'North Eastern States',
            'category': 'rural_development',
            'beneficiary_types': ['ne_residents', 'tribal'],
            'desc': '100% central funding for infrastructure and social development projects (healthcare facilities, rural bamboo housing, livelihood centres) in the 8 North-Eastern states.',
            'benefit': 'Community infrastructure grants and sustainable dwelling construction',
            'quantum': '100% Central Government Grant Allocation',
            'type': 'in_kind_and_services',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'artisan', 'daily_wage', 'self_employed'], 'label': 'Resident of 8 North Eastern States', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'artisan', 'daily_wage', 'self_employed']},
            'docs': ['Permanent Resident Certificate of NE State', 'Aadhaar Card'],
            'url': 'https://mdoner.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-vibrant-villages-175',
            'code': 'VIBRANT-VILLAGES',
            'name': 'Vibrant Villages Programme (VVP Border Infrastructure & Housing)',
            'short_name': 'Vibrant Villages Border Housing',
            'ministry': 'Ministry of Home Affairs',
            'state': 'Border Districts',
            'category': 'rural_development',
            'beneficiary_types': ['border_residents', 'rural_citizen'],
            'desc': 'Comprehensive development of selected border villages along northern borders, including 100% all-weather road connectivity, 24x7 solar power, and tourism homestay subsidies.',
            'benefit': 'Free solar rooftop system + homestay upgrade grant up to ₹2,00,000 for border families',
            'quantum': 'Up to ₹2,00,000 Homestay Grant & Solar System',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'artisan', 'homemaker'], 'label': 'Resident of Designated VVP Border Village', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'self_employed', 'artisan', 'homemaker']},
            'docs': ['Aadhaar Card', 'Border Village Domicile Certificate', 'Bank Passbook'],
            'url': 'https://mha.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'housing-ecbc-green-homes-176',
            'code': 'ECO-NIWAS-SAMHITA',
            'name': 'Eco-Niwas Samhita (Energy Conservation Building Code for Homes)',
            'short_name': 'Eco-Niwas Energy Efficient Homes',
            'ministry': 'Ministry of Power',
            'state': 'All-India',
            'category': 'energy',
            'beneficiary_types': ['homebuilder', 'citizen'],
            'desc': 'Bureau of Energy Efficiency technical guidelines and municipal property tax rebates (up to 10%) for residential buildings adhering to thermal comfort and passive cooling standards.',
            'benefit': '5% to 10% rebate on municipal property tax and up to 30% reduction in electricity bills',
            'quantum': '10% Municipal Tax Rebate',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'salaried', 'business', 'self_employed'], 'label': 'Urban Property Owner Adopting ENS Norms', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['employed', 'salaried', 'business', 'self_employed']},
            'docs': ['Approved Green Building Plan', 'BEE Energy Audit Certificate', 'Municipal Tax ID'],
            'url': 'https://beeindia.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'housing-destitute-rehab-177',
            'code': 'URBAN-REHAB-COLONIES',
            'name': 'In-situ Slum Redevelopment (ISSR) Rehabilitation Flat Allotment',
            'short_name': 'In-situ Slum Redevelopment (ISSR)',
            'ministry': 'Ministry of Housing and Urban Affairs',
            'state': 'All-India',
            'category': 'housing',
            'beneficiary_types': ['slum_dweller', 'urban_poor'],
            'desc': 'Rehabilitation of existing slum dwellers using land as a resource with private participation, providing modern multistorey apartment ownership with civic amenities.',
            'benefit': 'Permanent ownership of a modern pucca apartment with water, electricity & sewage',
            'quantum': 'Ownership of Multi-Storey Pucca Flat',
            'type': 'in_kind_and_services',
            'days': 90,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'IN', 'value': [True, False], 'label': 'Surveyed Slum Resident on Cut-off Date', 'impact': 'critical'}
            ],
            'flatRules': {},
            'docs': ['Slum Biometric Survey Slip', 'Aadhaar Card', 'Voter Identity Card at Slum Address'],
            'url': 'https://pmaymis.gov.in',
            'completeness': 'VERIFIED'
        }
    ]
