# scripts/catalog_states.py

def get_schemes():
    return [
        {
            'id': 'state-tn-pudhumai-penn-270',
            'code': 'TN-PUDHUMAI-PENN',
            'name': 'Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn)',
            'short_name': 'TN Pudhumai Penn College Aid',
            'ministry': 'Social Welfare and Women Empowerment Department, Government of Tamil Nadu',
            'gov_level': 'state',
            'state': 'Tamil Nadu',
            'category': 'scholarships',
            'beneficiary_types': ['girl_child', 'student', 'women'],
            'desc': 'Monthly financial grant of ₹1,000 deposited directly into bank accounts of girl students who studied Classes 6 to 12 in Tamil Nadu government schools until completion of graduation or diploma.',
            'benefit': '₹1,000 per month direct bank transfer until completion of undergraduate course',
            'quantum': '₹1,000 / month',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Student', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Studying in Higher Education Course', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student']},
            'docs': ['Government School Transfer Certificate / Bonafide (Class 6-12)', 'College Bonafide Certificate', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://penkalvi.tn.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-tn-magalir-urimai-271',
            'code': 'TN-MAGALIR-URIMAI',
            'name': 'Kalaignar Magalir Urimai Thogai Thittam (Basic Income for Women)',
            'short_name': 'TN Kalaignar Magalir Urimai',
            'ministry': 'Special Programme Implementation Department, Government of Tamil Nadu',
            'gov_level': 'state',
            'state': 'Tamil Nadu',
            'category': 'social_security',
            'beneficiary_types': ['women', 'homemaker', 'bpl'],
            'desc': 'Rights-based monthly financial assistance of ₹1,000 per month directly into bank accounts of over 1.15 crore female heads of eligible households in Tamil Nadu.',
            'benefit': '₹1,000 per month universal livelihood grant for women heads of family',
            'quantum': '₹1,000 / month',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Head of Household', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 21, 'label': 'Age ≥ 21 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Annual Household Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 21, 'income_limit': 250000},
            'docs': ['Smart Ration Card (Family Card)', 'Aadhaar Card', 'Electricity Consumer Number', 'Bank Passbook'],
            'url': 'https://kmut.tn.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-wb-lakshmir-bhandar-272',
            'code': 'WB-LAKSHMIR-BHANDAR',
            'name': 'Lakshmir Bhandar Scheme',
            'short_name': 'WB Lakshmir Bhandar',
            'ministry': 'Department of Women & Child Development and Social Welfare, Government of West Bengal',
            'gov_level': 'state',
            'state': 'West Bengal',
            'category': 'women_child',
            'beneficiary_types': ['women', 'homemaker', 'sc', 'st'],
            'desc': 'Monthly financial assistance of ₹1,200/month for SC/ST women and ₹1,000/month for General/OBC women aged between 25 and 60 years in West Bengal.',
            'benefit': 'Direct monthly bank transfer of ₹1,000 to ₹1,200 to female homemakers',
            'quantum': '₹1,000 - ₹1,200 / month',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Resident of West Bengal', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 25, 'label': 'Age Between 25 and 60 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 60, 'label': 'Age ≤ 60 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 25, 'age_max': 60},
            'docs': ['Swasthya Sathi Card', 'Aadhaar Card', 'SC/ST Certificate (if applicable)', 'Bank Passbook'],
            'url': 'https://socialwelfare.wb.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-wb-kanyashree-273',
            'code': 'WB-KANYASHREE',
            'name': 'Kanyashree Prakalpa (United Nations Awarded Girl Child Scheme)',
            'short_name': 'WB Kanyashree Prakalpa',
            'ministry': 'Department of Women & Child Development, Government of West Bengal',
            'gov_level': 'state',
            'state': 'West Bengal',
            'category': 'women_child',
            'beneficiary_types': ['girl_child', 'student'],
            'desc': 'Annual scholarship of ₹1,000 (K1: ages 13-18 enrolled in Class 8-12) and a one-time grant of ₹25,000 (K2: age 18-19 unmarried girl pursuing education) to incentivize girls\' higher education.',
            'benefit': '₹1,000 annual scholarship + ₹25,000 one-time higher education cash grant',
            'quantum': '₹1,000 / year + ₹25,000 Lump Sum',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Unmarried Girl Child', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Recognized Institution', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 13, 'label': 'Age Between 13 and 19', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 19, 'label': 'Age ≤ 19 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student'], 'age_min': 13, 'age_max': 19},
            'docs': ['Birth Certificate', 'Unmarried Declaration Certificate', 'Institution Bonafide', 'Bank Passbook'],
            'url': 'https://wbkanyashree.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-wb-krishak-bandhu-274',
            'code': 'WB-KRISHAK-BANDHU',
            'name': 'Krishak Bandhu (Natun) Scheme',
            'short_name': 'WB Krishak Bandhu',
            'ministry': 'Department of Agriculture, Government of West Bengal',
            'gov_level': 'state',
            'state': 'West Bengal',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'sharecropper', 'marginal_farmer'],
            'desc': 'Direct financial assistance of ₹10,000/year (minimum ₹4,000 for marginal farmers) in two installments for agricultural inputs, plus ₹2,00,000 lump sum death compensation to bereaved farmer families.',
            'benefit': '₹10,000 annual input grant + ₹2,00,000 life insurance death benefit',
            'quantum': '₹10,000 / year + ₹2,00,000 Life Insurance',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer / Recorded Bhagchasi (Sharecropper)', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['RoR / Khatian (Land Record)', 'Aadhaar Card', 'Voter ID Card', 'Bank Passbook'],
            'url': 'https://krishakbandhu.wb.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-ap-rythu-bharosa-275',
            'code': 'AP-RYTHU-BHAROSA',
            'name': 'YSR Rythu Bharosa - PM KISAN',
            'short_name': 'AP YSR Rythu Bharosa',
            'ministry': 'Department of Agriculture, Government of Andhra Pradesh',
            'gov_level': 'state',
            'state': 'Andhra Pradesh',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'tenant_farmer', 'sc', 'st'],
            'desc': 'Direct financial support of ₹13,500 per farmer family per year (inclusive of ₹6,000 PM-KISAN and ₹7,500 state grant) including tenant farmers belonging to SC, ST, BC, and Minority categories.',
            'benefit': '₹13,500 annual input assistance paid in 3 installments before cropping seasons',
            'quantum': '₹13,500 / year input assistance',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer or Tenant Farmer in Andhra Pradesh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Pattadar Passbook / CCRC Tenant Agreement', 'Aadhaar Card', 'Bank Account Details'],
            'url': 'https://ysrrythubharosa.ap.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-ap-aarogyasri-276',
            'code': 'AP-YSR-AAROGYASRI',
            'name': 'Dr. YSR Aarogyasri Comprehensive Health Scheme',
            'short_name': 'AP Dr. YSR Aarogyasri',
            'ministry': 'Health, Medical & Family Welfare Department, Government of Andhra Pradesh',
            'gov_level': 'state',
            'state': 'Andhra Pradesh',
            'category': 'health',
            'beneficiary_types': ['bpl', 'ews', 'all_families'],
            'desc': 'Universal cashless medical coverage up to ₹25 Lakh per family per year covering 3,257 surgical and medical procedures across empanelled hospitals with post-operative Aarogya Aasara daily wage compensation.',
            'benefit': 'Up to ₹25,00,000 cashless super-speciality hospital treatment + ₹5,000/month post-operative convalescence',
            'quantum': '₹25,00,000 Annual Cashless Hospital Cover',
            'type': 'insurance',
            'days': 1,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 500000, 'label': 'Household Annual Income ≤ ₹5.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 500000},
            'docs': ['Aarogyasri Health Card / Rice Card', 'Aadhaar Card'],
            'url': 'https://aarogyasri.ap.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-ap-vidya-deevena-277',
            'code': 'AP-VIDYA-DEEVENA',
            'name': 'Jagananna Vidya Deevena (Full Fee Reimbursement)',
            'short_name': 'AP Jagananna Vidya Deevena',
            'ministry': 'Higher Education Department, Government of Andhra Pradesh',
            'gov_level': 'state',
            'state': 'Andhra Pradesh',
            'category': 'scholarships',
            'beneficiary_types': ['students', 'bpl', 'sc', 'st', 'obc'],
            'desc': '100% full college tuition fee reimbursement directly credited to mother\'s bank account for students pursuing Polytechnic, ITI, B.Tech, Pharmacy, MBA, and degree courses in Andhra Pradesh.',
            'benefit': '100% full tuition fee payment directly credited to student\'s mother account quarterly',
            'quantum': '100% Full College Tuition Fees',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'College Degree / Polytechnic / Professional Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Annual Household Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 250000},
            'docs': ['Rice Card (Ration Card)', 'College Admission Receipt & Hall Ticket', 'Mother Aadhaar & Bank Passbook'],
            'url': 'https://jnanabhumi.ap.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-mp-ladli-behna-278',
            'code': 'MP-LADLI-BEHNA',
            'name': 'Mukhyamantri Ladli Behna Yojana',
            'short_name': 'MP Ladli Behna Yojana',
            'ministry': 'Women and Child Development Department, Government of Madhya Pradesh',
            'gov_level': 'state',
            'state': 'Madhya Pradesh',
            'category': 'women_child',
            'beneficiary_types': ['women', 'homemaker'],
            'desc': 'Direct bank cash transfer of ₹1,250 per month on the 10th of every month into bank accounts of over 1.29 crore married, widowed, divorced, and abandoned women in Madhya Pradesh.',
            'benefit': '₹1,250 per month DBT transfer for women\'s health, nutrition, and financial independence',
            'quantum': '₹1,250 / month',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Resident of Madhya Pradesh', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 21, 'label': 'Age Between 21 and 60 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 60, 'label': 'Age ≤ 60 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Family Combined Annual Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 21, 'age_max': 60, 'income_limit': 250000},
            'docs': ['Samagra Family & Member ID', 'Aadhaar Card linked to Bank Account (DBT active)'],
            'url': 'https://cmladlibahna.mp.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-mp-ladli-laxmi-279',
            'code': 'MP-LADLI-LAXMI',
            'name': 'Ladli Laxmi Yojana 2.0',
            'short_name': 'MP Ladli Laxmi 2.0',
            'ministry': 'Women and Child Development Department, Government of Madhya Pradesh',
            'gov_level': 'state',
            'state': 'Madhya Pradesh',
            'category': 'women_child',
            'beneficiary_types': ['girl_child', 'student'],
            'desc': 'Cumulative financial security package guaranteeing ₹1,43,000 assurance with milestone payouts on entering Class 6 (₹2,000), Class 9 (₹4,000), Class 11 (₹6,000), Class 12 (₹6,000), and ₹25,000 for college admission, plus final lump sum at age 21.',
            'benefit': 'Total cumulative ₹1,43,000 financial support + full college tuition fees',
            'quantum': '₹1,43,000 Milestone Assured Benefit',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Child Born in Madhya Pradesh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female']},
            'docs': ['Samagra ID', 'Girl Child Birth Certificate', 'Immunization Card', 'Parent Aadhaar Card'],
            'url': 'https://ladlilaxmi.mp.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-odi-kalia-280',
            'code': 'ODI-KALIA',
            'name': 'Krushak Assistance for Livelihood and Income Augmentation (KALIA)',
            'short_name': 'Odisha KALIA Farmer Scheme',
            'ministry': 'Department of Agriculture and Farmers\' Empowerment, Government of Odisha',
            'gov_level': 'state',
            'state': 'Odisha',
            'category': 'agriculture',
            'beneficiary_types': ['small_farmer', 'marginal_farmer', 'landless_labourer'],
            'desc': 'Direct financial assistance of ₹10,000 per year per farm family for cultivation inputs and ₹12,500 livelihood assistance for landless agricultural households for allied activities (goat rearing, duckery, fisheries).',
            'benefit': '₹10,000/year crop input grant or ₹12,500 landless livelihood grant + ₹2 Lakh life insurance',
            'quantum': '₹10,000 / year + ₹2,00,000 Life Insurance',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture', 'daily_wage'], 'label': 'Small/Marginal Farmer or Landless Agricultural Worker', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture', 'daily_wage']},
            'docs': ['Aadhaar Card', 'Ration Card', 'Bank Passbook linked to Aadhaar', 'Land Record (for cultivators)'],
            'url': 'https://kalia.odisha.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-odi-bsky-281',
            'code': 'ODI-BSKY-HEALTH',
            'name': 'Biju Swasthya Kalyan Yojana (BSKY / Gopabandhu Jan Arogya)',
            'short_name': 'Odisha BSKY Health Card',
            'ministry': 'Health & Family Welfare Department, Government of Odisha',
            'gov_level': 'state',
            'state': 'Odisha',
            'category': 'health',
            'beneficiary_types': ['bpl', 'all_families', 'women'],
            'desc': 'Universal cashless hospital coverage up to ₹5 Lakh per family and enhanced cover up to ₹10 Lakh for female family members per annum in over 800 premier empanelled hospitals across India.',
            'benefit': 'Cashless treatment up to ₹5,00,000 (General) and ₹10,00,000 (Female members)',
            'quantum': 'Up to ₹10,00,000 Cashless Health Cover',
            'type': 'insurance',
            'days': 1,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'IN', 'value': [True, False], 'label': 'BSKY Smart Card / NFSA / SFSA Cardholder', 'impact': 'critical'}
            ],
            'flatRules': {},
            'docs': ['BSKY Smart Health Card / Ration Card', 'Aadhaar Card of Patient'],
            'url': 'https://bsky.odisha.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-assam-orunodoi-282',
            'code': 'ASSAM-ORUNODOI',
            'name': 'Orunodoi 2.0 Scheme',
            'short_name': 'Assam Orunodoi 2.0',
            'ministry': 'Finance Department, Government of Assam',
            'gov_level': 'state',
            'state': 'Assam',
            'category': 'women_child',
            'beneficiary_types': ['women', 'bpl', 'widow', 'disabled'],
            'desc': 'Direct monthly financial assistance of ₹1,250 deposited into bank accounts of over 26 lakh female heads of poor and vulnerable families on the 10th of every month.',
            'benefit': '₹1,250 per month DBT for medicines, nutritional food, and household sustenance',
            'quantum': '₹1,250 / month',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Resident of Assam', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 200000, 'label': 'Household Annual Income ≤ ₹2.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'income_limit': 200000},
            'docs': ['Ration Card', 'Aadhaar Card', 'Bank Passbook', 'Gaon Burah / Ward Member Residence Certificate'],
            'url': 'https://finance.assam.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-delhi-farishtey-283',
            'code': 'DELHI-FARISHTEY',
            'name': 'Farishtey Dilli Ke Scheme (Accident Victim Cashless Care)',
            'short_name': 'Delhi Farishtey Scheme',
            'ministry': 'Directorate General of Health Services, Government of NCT of Delhi',
            'gov_level': 'state',
            'state': 'Delhi',
            'category': 'health',
            'beneficiary_types': ['accident_victims', 'all_citizens'],
            'desc': '100% free cashless emergency medical treatment, ICU care, and multiple surgeries in private hospitals for all victims of road accidents occurring in Delhi, plus ₹2,000 cash reward to Good Samaritans.',
            'benefit': '100% free emergency medical treatment & surgeries in private hospitals with zero out-of-pocket cost',
            'quantum': '100% Cashless Emergency Hospitalization',
            'type': 'in_kind_and_services',
            'days': 1,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['employed', 'salaried', 'student', 'daily_wage', 'unorganized_worker', 'self_employed', 'homemaker', 'retired'], 'label': 'Accident Victim inside Delhi Territorial Limits', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['employed', 'salaried', 'student', 'daily_wage', 'unorganized_worker', 'self_employed', 'homemaker', 'retired']},
            'docs': ['Medico-Legal Case (MLC) Certificate from Treating Hospital'],
            'url': 'https://delhi.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-delhi-jai-bhim-284',
            'code': 'DELHI-JAI-BHIM',
            'name': 'Jai Bhim Mukhyamantri Pratibha Vikas Yojana',
            'short_name': 'Delhi Jai Bhim Free Elite Coaching',
            'ministry': 'Department for Welfare of SC/ST/OBC, Government of NCT of Delhi',
            'gov_level': 'state',
            'state': 'Delhi',
            'category': 'scholarships',
            'beneficiary_types': ['sc', 'st', 'obc', 'ews', 'student'],
            'desc': '100% free coaching in premier private institutions for UPSC Civil Services, JEE Advanced, NEET, CLAT, CAT, and Banking exams with ₹2,500 monthly stipend for local students.',
            'benefit': 'Free elite competitive exam coaching (worth up to ₹1.5 Lakh) + ₹2,500/month stipend',
            'quantum': 'Free Elite Coaching + ₹2,500 / month Stipend',
            'type': 'in_kind_and_services',
            'days': 20,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Passed Class 10 & 12 from Delhi School', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student'], 'income_limit': 800000},
            'docs': ['Delhi School 10th/12th Marksheet', 'Caste / EWS Certificate', 'Income Certificate', 'Aadhaar Card'],
            'url': 'https://scstwelfare.delhi.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-har-parivar-pehchan-285',
            'code': 'HAR-PARIVAR-PEHCHAN',
            'name': 'Mukhyamantri Antyodaya Parivar Utthan Yojana (MMAPUY / PPP)',
            'short_name': 'Haryana Parivar Pehchan Utthan',
            'ministry': 'Citizen Resources Information Department, Government of Haryana',
            'gov_level': 'state',
            'state': 'Haryana',
            'category': 'livelihood',
            'beneficiary_types': ['poorest_families', 'bpl'],
            'desc': 'Doorstep livelihood saturation to raise annual income of poorest families with verified annual income < ₹1.0 Lakh to at least ₹1.80 Lakh through subsidized loans, skill packages, and wage jobs.',
            'benefit': 'Up to ₹50,000 capital subsidy on bank self-employment loans + guaranteed skilling',
            'quantum': 'Up to ₹50,000 Subsidy + Livelihood Saturation',
            'type': 'capital_subsidy',
            'days': 21,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 100000, 'label': 'Verified Family Income in PPP ≤ ₹1.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 100000},
            'docs': ['Parivar Pehchan Patra (Family ID)', 'Aadhaar Card', 'Bank Account Details'],
            'url': 'https://meraparivar.haryana.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-har-bhavantar-286',
            'code': 'HAR-BHAVANTAR-BHARPAYEE',
            'name': 'Bhavantar Bharpayee Yojana (Horticulture Price Deficit Payment)',
            'short_name': 'Haryana Bhavantar Bharpayee',
            'ministry': 'Department of Horticulture, Government of Haryana',
            'gov_level': 'state',
            'state': 'Haryana',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'vegetable_grower'],
            'desc': 'Protects farmers cultivating 21 horticultural crops (potato, onion, tomato, cauliflower, carrots, etc.) by compensating the difference between the protected floor price and actual wholesale market price.',
            'benefit': 'Direct DBT compensation of price difference (up to ₹1,000/quintal) directly to bank account',
            'quantum': 'Deficit Price Differential DBT Compensation',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Registered Farmer Cultivating Notified Horticultural Crops', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Meri Fasal Mera Byora Registration Slip', 'Aadhaar Card', 'Mandi J-Form / Sale Slip'],
            'url': 'https://fasal.haryana.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-chh-mahtari-vandan-287',
            'code': 'CHH-MAHTARI-VANDAN',
            'name': 'Mahtari Vandan Yojana (Monthly Financial Assistance to Married Women)',
            'short_name': 'Chhattisgarh Mahtari Vandan',
            'ministry': 'Women and Child Development Department, Government of Chhattisgarh',
            'gov_level': 'state',
            'state': 'Chhattisgarh',
            'category': 'women_child',
            'beneficiary_types': ['women', 'married_women', 'widow'],
            'desc': 'Direct bank cash transfer of ₹1,000 per month (₹12,000 per annum) directly into the bank accounts of over 70 lakh married, widowed, and abandoned women residing in Chhattisgarh.',
            'benefit': '₹1,000 per month direct bank transfer for nutrition and maternal welfare',
            'quantum': '₹1,000 / month (₹12,000 / year)',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Married / Widowed / Deserted Female Citizen', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 21, 'label': 'Age ≥ 21 Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'age_min': 21},
            'docs': ['Aadhaar Card', 'Marriage Certificate / Local Panchayat Panchnama', 'Bank Account linked to Aadhaar (DBT active)'],
            'url': 'https://mahtarivandan.cgstate.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-jh-abua-awas-288',
            'code': 'JH-ABUA-AWAS',
            'name': 'Abua Awas Yojana (Three-Room Pucca House Scheme)',
            'short_name': 'Jharkhand Abua Awas Yojana',
            'ministry': 'Department of Rural Development, Government of Jharkhand',
            'gov_level': 'state',
            'state': 'Jharkhand',
            'category': 'housing',
            'beneficiary_types': ['rural_poor', 'homeless', 'sc', 'st', 'bpl'],
            'desc': 'State-funded housing scheme providing ₹2,00,000 grant in 4 installments + 95 days MGNREGA wages for building a 3-room pucca house with hygienic kitchen for families omitted from PMAY-G.',
            'benefit': '₹2,00,000 grant for 3-room pucca house construction with kitchen',
            'quantum': '₹2,00,000 grant per house',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'IN', 'value': [True, False], 'label': 'Kutcha House Dweller in Jharkhand', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 200000, 'label': 'Family Annual Income ≤ ₹2.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 200000},
            'docs': ['Aapki Yojana Aapki Sarkar Survey Slip', 'Aadhaar Card', 'Ration Card', 'Bank Passbook'],
            'url': 'https://aay.jharkhand.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-uk-nanda-gaura-289',
            'code': 'UK-NANDA-GAURA',
            'name': 'Nanda Gaura Yojana for Girl Children',
            'short_name': 'Uttarakhand Nanda Gaura',
            'ministry': 'Women Empowerment and Child Development Department, Government of Uttarakhand',
            'gov_level': 'state',
            'state': 'Uttarakhand',
            'category': 'women_child',
            'beneficiary_types': ['girl_child', 'student'],
            'desc': 'Direct financial assistance of ₹11,000 on birth of girl child and ₹51,000 upon passing Class 12 and enrolling in higher education for girls belonging to families with income ≤ ₹72,000/year.',
            'benefit': '₹11,000 birth grant + ₹51,000 Class 12 pass higher education incentive',
            'quantum': '₹11,000 Birth Grant + ₹51,000 Higher Education Grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Girl Child / Female Student', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 72000, 'label': 'Family Annual Income ≤ ₹72,000', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'income_limit': 72000},
            'docs': ['Class 12th Marksheet', 'Higher Education Admission Receipt', 'Income Certificate', 'Aadhaar Card'],
            'url': 'https://wecd.uk.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-pun-sehat-bima-290',
            'code': 'PUN-SEHAT-BIMA',
            'name': 'Ayushman Bharat Mukh Mantri Sehat Bima Yojana',
            'short_name': 'Punjab Mukh Mantri Sehat Bima',
            'ministry': 'Department of Health & Family Welfare, Government of Punjab',
            'gov_level': 'state',
            'state': 'Punjab',
            'category': 'health',
            'beneficiary_types': ['all_citizens', 'farmer', 'trader', 'worker'],
            'desc': 'Cashless health insurance cover up to ₹5 Lakh per family per year covering 1,579 medical and surgical procedures across 900+ empanelled government and private hospitals in Punjab.',
            'benefit': '₹5,00,000 cashless secondary and tertiary hospital treatment per family',
            'quantum': '₹5,00,000 Annual Health Insurance Cover',
            'type': 'insurance',
            'days': 1,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'employed', 'salaried', 'self_employed', 'daily_wage', 'business'], 'label': 'Resident of Punjab with Valid J-Form / Smart Ration Card / BOCW Card', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'employed', 'salaried', 'self_employed', 'daily_wage', 'business']},
            'docs': ['Smart Ration Card / J-Form (Farmer) / Labour Card / Excise Card', 'Aadhaar Card'],
            'url': 'https://sha.punjab.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-ker-medisep-291',
            'code': 'KER-MEDISEP',
            'name': 'Medical Insurance for State Employees and Pensioners (MEDISEP)',
            'short_name': 'Kerala MEDISEP Scheme',
            'ministry': 'Finance Department, Government of Kerala',
            'gov_level': 'state',
            'state': 'Kerala',
            'category': 'insurance',
            'beneficiary_types': ['salaried', 'retired', 'government_employee'],
            'desc': 'Comprehensive cashless health insurance providing basic cover of ₹3 Lakh per annum (cumulative ₹9 Lakh for 3 years) plus ₹35 Crore catastrophic illness corpus for Kerala government staff & pensioners.',
            'benefit': 'Cashless treatment up to ₹3,00,000 per year covering 1,920 treatments & surgeries',
            'quantum': '₹3,00,000 Annual Cashless Cover + Catastrophic Benefit',
            'type': 'insurance',
            'days': 3,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['salaried', 'employed', 'retired'], 'label': 'Kerala Government Employee / Pensioner / Family Pensioner', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['salaried', 'employed', 'retired']},
            'docs': ['MEDISEP ID Card / PEN Number / PPO Number', 'Aadhaar Card'],
            'url': 'https://medisep.kerala.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-ker-subhiksha-292',
            'code': 'KER-SUBHIKSHA',
            'name': 'Subhiksha Keralam Integrated Food Security Programme',
            'short_name': 'Kerala Subhiksha Keralam',
            'ministry': 'Department of Agriculture Development and Farmers\' Welfare, Government of Kerala',
            'gov_level': 'state',
            'state': 'Kerala',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'homemaker', 'youth'],
            'desc': 'Statewide drive targeting fallow land cultivation, urban terrace farming, biofloc fish farming, and backyard dairy with 50% capital subsidies up to ₹50,000 for families.',
            'benefit': '50% capital subsidy on organic seed kits, drip irrigation, and biofloc fish ponds',
            'quantum': 'Up to ₹50,000 Capital Subsidy',
            'type': 'capital_subsidy',
            'days': 15,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'homemaker', 'daily_wage'], 'label': 'Resident Farmer / Homemaker Cultivator', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['farmer', 'self_employed', 'homemaker', 'daily_wage']},
            'docs': ['Krishi Bhavan Registration Slip', 'Aadhaar Card', 'Land Tax Receipt'],
            'url': 'https://keralaagriculture.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-assam-pragyan-293',
            'code': 'ASSAM-PRAGYAN-BHARATI',
            'name': 'Pragyan Bharati Higher Education & Free Scooty Scheme',
            'short_name': 'Assam Pragyan Bharati Free Scooty',
            'ministry': 'Higher Education Department, Government of Assam',
            'gov_level': 'state',
            'state': 'Assam',
            'category': 'scholarships',
            'beneficiary_types': ['girl_child', 'student'],
            'desc': 'Distribution of brand new two-wheeler scooties to meritorious girl students securing 60%+ marks (and boy students securing 75%+ marks) in Higher Secondary (Class 12) examinations.',
            'benefit': 'Free petrol or electric two-wheeler scooter with 1-year insurance & registration',
            'quantum': 'Brand New Two-Wheeler Scooter (Worth ~₹85,000)',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Meritorious Female Student in Assam', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Secured 60%+ in AHSEC Class 12 Exams', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student']},
            'docs': ['AHSEC Class 12th Marksheet', 'Admit Card', 'Aadhaar Card', 'College Admission Proof'],
            'url': 'https://highereducation.assam.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'state-chh-kisan-nyay-294',
            'code': 'CHH-KISAN-NYAY',
            'name': 'Rajiv Gandhi Kisan Nyay Yojana (Crop Input Assistance)',
            'short_name': 'Chhattisgarh Kisan Nyay',
            'ministry': 'Department of Agriculture, Government of Chhattisgarh',
            'gov_level': 'state',
            'state': 'Chhattisgarh',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'paddy_grower'],
            'desc': 'Direct agricultural input assistance of ₹9,000 per acre (₹10,000/acre for crop diversification into pulses/oilseeds) deposited in 4 quarterly installments directly into farmers\' bank accounts.',
            'benefit': '₹9,000 - ₹10,000 per acre input subsidy grant transferred directly via DBT',
            'quantum': '₹9,000 - ₹10,000 / acre input grant',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Cultivating Farmer in Chhattisgarh', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Bhuiyan Khasra / B-1 Land Record', 'Kisan Kitab', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://rgkny.cg.nic.in',
            'completeness': 'VERIFIED'
        }
    ]
