# scripts/catalog_agriculture.py

def get_schemes():
    return [
        {
            'id': 'pm-sampada-053',
            'code': 'PM-SAMPADA',
            'name': 'Pradhan Mantri Kisan SAMPADA Yojana',
            'short_name': 'PM SAMPADA',
            'ministry': 'Ministry of Food Processing Industries',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'entrepreneur', 'fpo'],
            'desc': 'Grant-in-aid up to 50% of eligible project cost for creation of modern food processing, cold chain, and value-addition clusters.',
            'benefit': 'Capital subsidy up to 50% (Max ₹5 Crore per project)',
            'quantum': '₹5,00,00,000 subsidy',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'artisan'], 'label': 'Agri-entrepreneur or Farmer Producer Group', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'self_employed', 'artisan']},
            'docs': ['Aadhaar Card', 'Detailed Project Report (DPR)', 'Bank In-Principle Appraisal', 'Land Title Deeds'],
            'url': 'https://mofpi.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'smam-machinery-055',
            'code': 'SMAM',
            'name': 'Sub-Mission on Agricultural Mechanization',
            'short_name': 'SMAM Farm Machinery',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'small_landholder', 'women'],
            'desc': '40% to 50% subsidy on purchase of agricultural tractors, power tillers, rotavators, and harvesters for small and marginal farmers.',
            'benefit': '40% - 50% subsidy on farm machinery (Save up to ₹2.5 Lakh)',
            'quantum': '₹2,50,000 subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer Cultivator', 'impact': 'critical'},
                {'field': 'citizen.land_ownership', 'op': 'IN', 'value': ['below_2_acres', '2_to_5_acres', 'above_5_acres'], 'label': 'Cultivable Land Record', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', '7/12 Land Document', 'Quotation / Proforma Invoice'],
            'url': 'https://agrimachinery.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'ahidf-dairy-057',
            'code': 'AHIDF',
            'name': 'Animal Husbandry Infrastructure Development Fund',
            'short_name': 'AHIDF Dairy Infra',
            'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'dairy_farmer', 'entrepreneur'],
            'desc': '3% interest subvention on commercial bank loans up to 90% project cost for milk processing, meat processing, animal feed plants, and breed multiplication.',
            'benefit': '3% Interest Subvention on Loans up to ₹10 Crore with 2 Year Moratorium',
            'quantum': '3% Interest Subsidy',
            'type': 'concessional_credit',
            'days': 40,
            'rules': [
                {'field': 'citizen.age', 'op': 'BETWEEN', 'value': [21, 65], 'label': 'Age 21-65', 'impact': 'critical'},
                {'field': 'citizen.bank_account', 'op': 'EQ', 'value': True, 'label': 'Active Commercial Bank Account', 'impact': 'critical'}
            ],
            'flatRules': {'min_age': 21, 'max_age': 65, 'bank_account_required': True},
            'docs': ['Aadhaar Card', 'DPR', 'PAN Card', 'Bank Appraisal Note'],
            'url': 'https://ahidf.udyamimitra.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'movcdner-organic-058',
            'code': 'MOVCDNER',
            'name': 'Mission Organic Value Chain Development for North East',
            'short_name': 'MOVCDNER Organic',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'North Eastern States',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'tribal'],
            'desc': 'End-to-end organic farming assistance of ₹25,000/ha for organic inputs, processing, branding, and cold storage in NE states.',
            'benefit': '₹25,000 / hectare grant + Post-harvest marketing linkage',
            'quantum': '₹25,000 / ha',
            'type': 'direct_benefit',
            'days': 35,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer in North Eastern Region', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Domicile / ST Certificate (if applicable)', 'Land Proof'],
            'url': 'https://movcd.dac.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'rkvy-raftaar-059',
            'code': 'RKVY-RAFTAAR',
            'name': 'Rashtriya Krishi Vikas Yojana - RAFTAAR',
            'short_name': 'RKVY RAFTAAR Agripreneur',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'youth', 'entrepreneur'],
            'desc': 'Seed funding grants up to ₹25 Lakh for innovative agricultural and allied sector startups and youth entrepreneurs.',
            'benefit': 'Up to ₹25,00,000 seed capital grant for agri-startups',
            'quantum': '₹25,00,000 grant',
            'type': 'direct_benefit',
            'days': 60,
            'rules': [{'field': 'citizen.age', 'op': 'BETWEEN', 'value': [18, 50], 'label': 'Age 18-50 Years', 'impact': 'critical'}],
            'flatRules': {'min_age': 18, 'max_age': 50},
            'docs': ['Aadhaar Card', 'Agri-Business Prototype / Proposal', 'PAN Card'],
            'url': 'https://rkvy.nic.in',
            'completeness': 'PARTIALLY_VERIFIED'
        },
        {
            'id': 'pm-aasha-procurement-060',
            'code': 'PM-AASHA',
            'name': 'Pradhan Mantri Annadata Aay Sanraksan Abhiyan',
            'short_name': 'PM-AASHA MSP Procurement',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': 'Price Support Scheme (PSS) ensuring government procurement of pulses, oilseeds, and copra at statutory Minimum Support Price (MSP).',
            'benefit': 'Guaranteed MSP procurement payment directly into bank account',
            'quantum': 'Guaranteed MSP Payment',
            'type': 'direct_benefit',
            'days': 10,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer Cultivator', 'impact': 'critical'},
                {'field': 'citizen.bank_account', 'op': 'EQ', 'value': True, 'label': 'DBT Enabled Account', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['farmer', 'agriculture'], 'bank_account_required': True},
            'docs': ['Aadhaar Card', 'Khasra/Girdawari Crop Sowing Certificate', 'Bank Passbook'],
            'url': 'https://agricoop.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sub-mission-seeds-062',
            'code': 'SMSP',
            'name': 'Sub-Mission on Seeds and Planting Material',
            'short_name': 'Certified Seed Subsidy',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': '50% to 60% price subsidy on procurement of high-yielding certified and foundation seeds for cereals, pulses, and oilseeds.',
            'benefit': '50% - 60% price subsidy on certified foundation seeds',
            'quantum': '₹1,500 - ₹4,000 / quintal subsidy',
            'type': 'subsidy',
            'days': 7,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Active Cultivator', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Land Record Copy'],
            'url': 'https://seednet.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'rashtriya-gokul-mission-063',
            'code': 'RGM',
            'name': 'Rashtriya Gokul Mission (Breed Multiplication Farm)',
            'short_name': 'Rashtriya Gokul Mission',
            'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['dairy_farmer', 'entrepreneur'],
            'desc': '50% capital subsidy up to ₹2 Crore for establishing indigenous bovine breed multiplication farms of minimum 200 cattle/buffaloes.',
            'benefit': '50% Capital Subsidy up to ₹2 Crore for Breed Farm Setup',
            'quantum': '₹2,00,00,000 subsidy',
            'type': 'capital_subsidy',
            'days': 60,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed'], 'label': 'Dairy Entrepreneur / Farmer', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'self_employed']},
            'docs': ['Aadhaar Card', 'Bank Sanction Letter', 'Land Records (Min 5 Acres)', 'DPR'],
            'url': 'https://dahd.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'national-livestock-mission-064',
            'code': 'NLM-POULTRY',
            'name': 'National Livestock Mission (Rural Poultry & Sheep/Goat)',
            'short_name': 'NLM Rural Poultry & Goat',
            'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'rural_poor', 'women'],
            'desc': '50% capital subsidy up to ₹25 Lakh for establishing sheep, goat, and poultry parent breeding farms.',
            'benefit': '50% capital subsidy (₹25 Lakh for Sheep/Goat, ₹50 Lakh for Piggery)',
            'quantum': '₹25,00,000 subsidy',
            'type': 'capital_subsidy',
            'days': 40,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age 18+ Years', 'impact': 'critical'}],
            'flatRules': {'min_age': 18},
            'docs': ['Aadhaar Card', 'DPR', 'Land Ownership / Lease Agreement'],
            'url': 'https://nlm.udyamimitra.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'fidi-fisheries-fund-065',
            'code': 'FIDF',
            'name': 'Fisheries and Aquaculture Infrastructure Development Fund',
            'short_name': 'FIDF Fisheries Loan',
            'ministry': 'Ministry of Fisheries, Animal Husbandry and Dairying',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['fishermen', 'entrepreneur'],
            'desc': 'Concessional financing with 3% interest subvention for fishing harbors, deep sea fishing vessels, and cold storage.',
            'benefit': '3% Interest Subvention on Loans up to 80% Project Cost',
            'quantum': '3% Interest Subsidy',
            'type': 'concessional_credit',
            'days': 45,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'other'], 'label': 'Fisheries Entrepreneur / Fish Farmer', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card', 'Fishing License / Vessel Registration', 'DPR'],
            'url': 'https://fidf.in',
            'completeness': 'PARTIALLY_VERIFIED'
        },
        {
            'id': 'pmksy-watershed-066',
            'code': 'WDC-PMKSY',
            'name': 'Watershed Development Component (PMKSY 2.0)',
            'short_name': 'WDC Watershed Farm Pond',
            'ministry': 'Ministry of Rural Development',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'rural_poor'],
            'desc': 'Financial support of ₹12,000 to ₹18,000 per hectare for constructing farm ponds and rain water harvesting structures.',
            'benefit': '100% Grant for construction of community and individual farm ponds',
            'quantum': '₹18,000 / ha equivalent work',
            'type': 'in_kind',
            'days': 30,
            'rules': [
                {'field': 'citizen.area_type', 'op': 'EQ', 'value': 'rural', 'label': 'Rural Inhabitant', 'impact': 'critical'},
                {'field': 'citizen.land_ownership', 'op': 'IN', 'value': ['below_2_acres', '2_to_5_acres', 'above_5_acres'], 'label': 'Agricultural Landholder', 'impact': 'critical'}
            ],
            'flatRules': {'area_type': 'rural'},
            'docs': ['Aadhaar Card', 'Land Record Extract', 'Panchayat Resolution'],
            'url': 'https://dolr.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'national-beekeeping-067',
            'code': 'NBHM',
            'name': 'National Beekeeping and Honey Mission',
            'short_name': 'Honey Mission Subsidy',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'beekeeper', 'youth'],
            'desc': 'Up to 80% subsidy for women and SC/ST beekeepers (50% for general) for honey bee boxes, bee colonies, and extraction units.',
            'benefit': '50% to 80% subsidy on 50 bee boxes with colonies (Save ₹80,000)',
            'quantum': '₹80,000 subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age 18+ Years', 'impact': 'critical'}],
            'flatRules': {'min_age': 18},
            'docs': ['Aadhaar Card', 'Training Certificate in Beekeeping (KVK/ICAR)'],
            'url': 'https://nbhm.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'bamboo-mission-068',
            'code': 'NBM',
            'name': 'National Bamboo Mission (Plantation & Nursery)',
            'short_name': 'National Bamboo Mission',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'tribal', 'artisan'],
            'desc': '50% direct subsidy up to ₹50,000 per hectare for commercial bamboo plantation on non-forest private agricultural lands.',
            'benefit': '₹50,000 / hectare subsidy for 3-year bamboo cultivation',
            'quantum': '₹50,000 / ha',
            'type': 'subsidy',
            'days': 30,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture', 'artisan'], 'label': 'Farmer / Forest Dweller', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture', 'artisan']},
            'docs': ['Aadhaar Card', 'Land Ownership RoR', 'Bank Account'],
            'url': 'https://nbm.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'oil-palm-mission-069',
            'code': 'NMEO-OP',
            'name': 'National Mission on Edible Oils - Oil Palm',
            'short_name': 'Oil Palm Cultivation Grant',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': '₹29,000 per hectare assistance for planting material, intercropping, and assured Viability Price (VP) mechanism.',
            'benefit': '₹29,000 / ha planting subsidy + Guaranteed Viability Price purchase',
            'quantum': '₹29,000 / ha',
            'type': 'direct_benefit',
            'days': 25,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer Cultivator', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Land Record with Assured Irrigation Proof'],
            'url': 'https://nmeo.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'per-drop-micro-irrigation-070',
            'code': 'PDMC',
            'name': 'Per Drop More Crop (Micro Irrigation Drip Component)',
            'short_name': 'Drip Irrigation 55% Subsidy',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'small_landholder'],
            'desc': '55% financial assistance for small/marginal farmers for installation of drip irrigation systems.',
            'benefit': '55% Subsidy on ISI Certified Drip Irrigation Lateral/Filter Kit',
            'quantum': 'Up to ₹45,000 / ha subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Cultivator', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Land 7/12 RoR', 'Borewell / Water Source Proof'],
            'url': 'https://pmksy.gov.in/microirrigation',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'kisan-drone-subsidy-074',
            'code': 'KISAN-DRONE',
            'name': 'Kisan Drone Subsidy Scheme (SMAM Extension)',
            'short_name': 'Kisan Drone Purchase Grant',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'fpo', 'women'],
            'desc': '50% subsidy up to ₹5 Lakh for SC/ST, small/marginal farmers and women for agricultural drone purchase.',
            'benefit': '50% capital subsidy (Save up to ₹5,00,000 on Agri-Drone)',
            'quantum': '₹5,00,000 subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer / FPO Member', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'DGCA Drone Remote Pilot Certificate', 'Land Document'],
            'url': 'https://agrimachinery.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'fpo-formation-scheme-075',
            'code': '10K-FPO',
            'name': 'Formation and Promotion of 10,000 Farmer Producer Organizations',
            'short_name': '10,000 FPO Equity Grant',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'fpo'],
            'desc': 'Matching equity grant up to ₹15 Lakh per FPO and credit guarantee cover up to ₹2 Crore to enhance farmer bargaining power.',
            'benefit': 'Matching equity grant up to ₹2,000 per farmer member (Max ₹15 Lakh)',
            'quantum': '₹15,00,000 equity grant',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Small/Marginal Farmer Member', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'FPO Share Certificate', 'Land RoR'],
            'url': 'https://enam.gov.in/web/fpo-information',
            'completeness': 'PARTIALLY_VERIFIED'
        },
        {
            'id': 'fertilizer-dbt-neem-077',
            'code': 'NEEM-UREA',
            'name': 'Neem Coated Urea Statutory Price Subsidy',
            'short_name': 'Subsidized Neem Coated Urea',
            'ministry': 'Ministry of Chemicals and Fertilizers',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': 'Direct fertilizer subsidy ensuring urea is sold at fixed statutory price of ₹242 per 45 kg bag.',
            'benefit': 'Over 85% price subsidy on essential agricultural fertilizers (Urea & DAP)',
            'quantum': '₹2,000+ subsidy per bag',
            'type': 'subsidy',
            'days': 1,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Cultivator Purchasing via PoS', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card (Biometric PoS Verification)'],
            'url': 'https://urvarak.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'agroforestry-mission-078',
            'code': 'SMAF',
            'name': 'Sub-Mission on Agroforestry (Har Medh Par Ped)',
            'short_name': 'Har Medh Par Ped Agroforestry',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': 'Up to ₹70 per tree incentive over 4 years for planting multipurpose trees on farm boundaries and bunds.',
            'benefit': '₹70 / plant maintenance assistance + Quality saplings supply',
            'quantum': '₹70 / plant subsidy',
            'type': 'direct_benefit',
            'days': 20,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Farmer Cultivator', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Land Record'],
            'url': 'https://agricoop.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'natural-farming-mission-079',
            'code': 'NMNF',
            'name': 'National Mission on Natural Farming (Bhartiya Prakritik Krishi)',
            'short_name': 'Natural Farming Incentive',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': 'Financial assistance of ₹15,000 per hectare for 3 years for adopting zero-chemical natural farming with indigenous bio-inputs.',
            'benefit': '₹15,000 / hectare financial grant over 3 years + Free Bio-Resource Center input kits',
            'quantum': '₹15,000 / ha grant',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Active Cultivator Committing to Zero-Chemical Farming', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Land Record', 'Panchayat Natural Farming Pledge'],
            'url': 'https://naturalfarming.dac.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'micro-food-enterprises-080',
            'code': 'PM-FME',
            'name': 'PM Formalisation of Micro Food Processing Enterprises',
            'short_name': 'PM-FME Micro Enterprise Grant',
            'ministry': 'Ministry of Food Processing Industries',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer', 'self_employed', 'women_shg'],
            'desc': '35% credit-linked capital subsidy up to ₹10 Lakh per unit for upgrading micro food processing units (One District One Product).',
            'benefit': '35% capital subsidy up to ₹10 Lakh + ₹40,000 seed capital per SHG member',
            'quantum': '₹10,00,000 capital subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age 18+ Years', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'self_employed', 'artisan', 'daily_wage'], 'label': 'Micro Food Processing Enterprise Owner', 'impact': 'critical'}
            ],
            'flatRules': {'min_age': 18},
            'docs': ['Aadhaar Card', 'Bank Passbook', 'Enterprise Registration / FSSAI', 'Quotation'],
            'url': 'https://pmfme.mofpi.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'copra-price-support-081',
            'code': 'NAFED-PSS',
            'name': 'Price Support Scheme for Copra, Pulses and Oilseeds',
            'short_name': 'NAFED PSS Direct Procurement',
            'ministry': 'Ministry of Agriculture and Farmers Welfare',
            'state': 'All-India',
            'category': 'agriculture',
            'beneficiary_types': ['farmer'],
            'desc': 'Guaranteed statutory market intervention when fair average quality prices fall below announced Minimum Support Price.',
            'benefit': 'Statutory floor price payment with zero APMC cess deduction',
            'quantum': 'Direct MSP Bank Transfer',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [{'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'agriculture'], 'label': 'Registered Oilseed/Pulse Cultivator', 'impact': 'critical'}],
            'flatRules': {'occupation': ['farmer', 'agriculture']},
            'docs': ['Aadhaar Card', 'Sowing Proof', 'Bank Passbook'],
            'url': 'https://nafed-india.com',
            'completeness': 'VERIFIED'
        }
    ]
