# scripts/catalog_msme.py

def get_schemes():
    return [
        {
            'id': 'msme-cgtmse-guarantee-180',
            'code': 'CGTMSE',
            'name': 'Credit Guarantee Scheme for Micro & Small Enterprises (CGTMSE)',
            'short_name': 'CGTMSE Collateral-Free Loans',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['entrepreneur', 'business_owner', 'msme'],
            'desc': 'Collateral-free credit facility up to ₹5 Crore for new and existing Micro and Small Enterprises, with guarantee coverage up to 85% provided by the sovereign trust.',
            'benefit': 'Bank loans up to ₹5,00,00,000 without requiring third-party collateral or mortgage',
            'quantum': 'Up to ₹5 Crore Collateral-Free Credit Guarantee',
            'type': 'concessional_credit',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'entrepreneur'], 'label': 'MSME Entrepreneur / Business Owner', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'PAN of Enterprise', 'Project Report', 'Bank Account Statement'],
            'url': 'https://www.cgtmse.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-zed-cert-181',
            'code': 'MSME-ZED',
            'name': 'MSME Sustainable (ZED) Certification Scheme',
            'short_name': 'ZED Green Certification Subsidy',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme_manufacturer', 'business'],
            'desc': 'Financial support up to 80% (Micro), 60% (Small), and 50% (Medium) on the cost of Zero Defect Zero Effect certification, testing, and handholding.',
            'benefit': 'Up to 80% subsidy on certification fees + ₹5 Lakh handholding grant + 0.5% interest rebate',
            'quantum': 'Up to 80% Subsidy + ₹5,00,000 Handholding',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'entrepreneur'], 'label': 'Manufacturing MSME with Udyam Registration', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Pollution Control Board NOC (if applicable)', 'GSTIN'],
            'url': 'https://zed.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-sfurti-clusters-182',
            'code': 'SFURTI',
            'name': 'Scheme of Fund for Regeneration of Traditional Industries (SFURTI)',
            'short_name': 'SFURTI Artisan Clusters',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['artisan', 'craftsperson', 'rural_women'],
            'desc': 'Cluster development grants up to ₹2.5 Crore (Regular Clusters: 500 artisans) and ₹5 Crore (Major Clusters: 500+ artisans) for setting up Common Facility Centres (CFC) and modern toolkits.',
            'benefit': 'Grant up to ₹5 Crore for shared raw material banks, packaging, and export linkages',
            'quantum': 'Up to ₹5,00,00,000 Cluster Development Grant',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'craftsperson', 'weaver', 'self_employed'], 'label': 'Traditional Artisan / Craftsperson', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'craftsperson', 'weaver', 'self_employed']},
            'docs': ['Artisan Identity Card / Pehchan Card', 'Aadhaar Card', 'SHG / Cluster Membership Proof'],
            'url': 'https://sfurti.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-aspire-innovation-183',
            'code': 'ASPIRE-INCUBATION',
            'name': 'A Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship (ASPIRE)',
            'short_name': 'ASPIRE Rural Livelihood Incubators',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'entrepreneurship',
            'beneficiary_types': ['entrepreneur', 'rural_youth', 'innovator'],
            'desc': 'Financial support of up to ₹1 Crore for setting up Livelihood Business Incubators (LBI) and up to ₹1 Crore for Technology Business Incubators in agro-rural sectors.',
            'benefit': 'Free incubation, prototyping equipment access, and seed funding for rural startups',
            'quantum': 'Free Incubation & Up to ₹1 Crore Facility Grant',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['entrepreneur', 'self_employed', 'student'], 'label': 'Rural Agri-Business Innovator', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['entrepreneur', 'self_employed', 'student']},
            'docs': ['Udyam Registration / DPIIT Startup Recognition', 'Project Pitch Deck', 'Aadhaar Card'],
            'url': 'https://aspire.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-samadhaan-delayed-184',
            'code': 'MSME-SAMADHAAN',
            'name': 'MSME SAMADHAAN (Delayed Payments Monitoring System)',
            'short_name': 'MSME Samadhaan Payment Recovery',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme_supplier', 'business'],
            'desc': 'Statutory recovery mechanism mandating compound interest with monthly rests at 3 times the RBI bank rate on buyers defaulting beyond 45 days on MSE payments.',
            'benefit': 'Legal recovery of unpaid commercial dues with 3x bank rate compound interest',
            'quantum': 'Statutory Claim Adjudication & 3x Penalty Interest',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'entrepreneur'], 'label': 'Micro or Small Enterprise Supplier', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Invoices with Acceptance Proof', 'Purchase Order Copy'],
            'url': 'https://samadhaan.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-sambandh-procurement-185',
            'code': 'MSME-SAMBANDH',
            'name': 'Public Procurement Policy Monitoring Portal (MSME SAMBANDH)',
            'short_name': 'MSME Sambandh 25% Procurement Quota',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme', 'sc_st_msme', 'women_msme'],
            'desc': 'Mandates every Central Ministry, Department, and CPSU to procure minimum 25% of annual purchases from MSEs, with 4% earmarked for SC/ST and 3% for Women MSEs.',
            'benefit': 'Tender fee waiver, EMD exemption, and 25% reserved government public buying',
            'quantum': 'EMD Exemption & 25% Market Reservation',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'entrepreneur'], 'label': 'Registered Micro/Small Enterprise', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'GeM Portal Vendor Registration'],
            'url': 'https://sambandh.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-innovative-grant-186',
            'code': 'MSME-INNOVATIVE',
            'name': 'MSME Innovative Scheme (Incubation, Design & IPR Grants)',
            'short_name': 'MSME Innovative Idea Grant',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'entrepreneurship',
            'beneficiary_types': ['innovator', 'student', 'entrepreneur'],
            'desc': 'Financial grant of up to ₹15 Lakh per approved idea for developing prototypes, up to ₹1 Crore for procurement of plant/machinery, and design grants up to ₹40 Lakh.',
            'benefit': 'Up to ₹15 Lakh seed grant for turning innovative prototype into commercial product',
            'quantum': '₹15,00,000 prototype development grant',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['student', 'entrepreneur', 'self_employed', 'employed'], 'label': 'Individual Innovator or Registered MSME', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['student', 'entrepreneur', 'self_employed', 'employed']},
            'docs': ['Idea Proposal Concept Note', 'Aadhaar Card', 'Host Institute Verification'],
            'url': 'https://innovative.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-ipr-reimbursement-187',
            'code': 'MSME-IPR-REIMBURSEMENT',
            'name': 'Support for Intellectual Property Rights (IPR) Reimbursement',
            'short_name': 'MSME Patent & Trademark Subsidy',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['entrepreneur', 'msme'],
            'desc': 'Reimbursement of government fees and attorney expenses up to ₹1 Lakh for Indian Patent, ₹5 Lakh for Foreign Patent, ₹10,000 for Trademark, and ₹2 Lakh for GI registration.',
            'benefit': 'Reimbursement up to ₹5,00,000 on domestic and international patent filings',
            'quantum': 'Up to ₹5,00,000 IPR reimbursement',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'entrepreneur'], 'label': 'Udyam Registered Enterprise', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Grant of Patent / Registration Certificate', 'Fee Receipts'],
            'url': 'https://innovative.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'dpiit-startup-seed-188',
            'code': 'STARTUP-SEED-FUND',
            'name': 'Startup India Seed Fund Scheme (SISFS)',
            'short_name': 'Startup India Seed Fund',
            'ministry': 'Ministry of Commerce and Industry',
            'state': 'All-India',
            'category': 'entrepreneurship',
            'beneficiary_types': ['startup_founder', 'innovator'],
            'desc': 'Financial assistance up to ₹20 Lakh as grant for validation of Proof of Concept, prototype development, and product trials; and up to ₹50 Lakh as debt/convertible debenture.',
            'benefit': 'Grant up to ₹20 Lakh + Convertible Debt up to ₹50 Lakh through certified incubators',
            'quantum': 'Up to ₹50,00,000 Seed Capital',
            'type': 'capital_subsidy',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['entrepreneur', 'self_employed', 'student'], 'label': 'DPIIT-Recognised Startup Founder', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['entrepreneur', 'self_employed', 'student']},
            'docs': ['DPIIT Startup Recognition Certificate', 'Pitch Deck & Business Plan', 'Incorporation Certificate'],
            'url': 'https://seedfund.startupindia.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-udyam-assist-189',
            'code': 'UDYAM-ASSIST',
            'name': 'Udyam Assist Platform (UAP for Informal Micro Enterprises)',
            'short_name': 'Udyam Assist Informal Micro Priority',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'financial_inclusion',
            'beneficiary_types': ['street_vendor', 'artisan', 'informal_worker'],
            'desc': 'Brings Informal Micro Enterprises (IMEs) lacking GSTIN into formal priority sector lending fold, issuing an authenticated Udyam Assist Certificate to access priority credit.',
            'benefit': 'Direct eligibility for Priority Sector Lending (PSL) benefits without requiring GSTIN',
            'quantum': 'Priority Sector Lending Collateral-Free Loans',
            'type': 'in_kind_and_services',
            'days': 3,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['street_vendor', 'artisan', 'self_employed', 'daily_wage'], 'label': 'Informal Nano/Micro Entrepreneur', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['street_vendor', 'artisan', 'self_employed', 'daily_wage']},
            'docs': ['Aadhaar Card', 'Bank Account Details'],
            'url': 'https://udyamassist.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-esdp-training-190',
            'code': 'MSME-ESDP',
            'name': 'Entrepreneurship and Skill Development Programme (ESDP)',
            'short_name': 'MSME ESDP Skilling Courses',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['youth', 'women', 'unemployed'],
            'desc': 'Motivational campaigns, entrepreneurship awareness programmes, and 6-week technical skill development training courses conducted across MSME-Development Institutes free of cost.',
            'benefit': 'Free specialized industry skill training with government certification & bank loan linkage',
            'quantum': 'Free 6-Week Practical Industry Training',
            'type': 'in_kind_and_services',
            'days': 14,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18},
            'docs': ['Aadhaar Card', 'Highest Education Certificate', 'Passport Photograph'],
            'url': 'https://msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-champions-portal-191',
            'code': 'CHAMPIONS-PORTAL',
            'name': 'CHAMPIONS Portal (Creation and Harmonious Application of Modern Processes)',
            'short_name': 'MSME CHAMPIONS Control Room',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme_owner', 'entrepreneur'],
            'desc': 'AI-driven unified single-window platform for MSMEs to resolve regulatory hurdles, seek technology guidance, obtain raw materials, and capture export opportunities.',
            'benefit': 'Guaranteed 7-day time-bound grievance resolution and business mentoring',
            'quantum': 'Free Single-Window MSME Mentoring & Redressal',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'entrepreneur'], 'label': 'MSME Proprietor or Partner', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'entrepreneur']},
            'docs': ['Udyam Registration Number', 'Grievance / Query Documentation'],
            'url': 'https://champions.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-lean-manufacturing-192',
            'code': 'MSME-LEAN',
            'name': 'MSME Competitive (Lean) Manufacturing Scheme',
            'short_name': 'MSME Lean Subsidy',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme_manufacturer'],
            'desc': '90% government financial assistance on the implementation cost of Lean manufacturing tools and techniques (5S, Kaizen, Kanban, TPM) by accredited consultants.',
            'benefit': '90% reimbursement of consultant and implementation fees (up to ₹21.6 Lakh per cluster)',
            'quantum': '90% Government Cost Contribution',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'entrepreneur'], 'label': 'Manufacturing MSME with Udyam Certificate', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Plant Location Details', 'Lean Consultant Agreement'],
            'url': 'https://lean.msme.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-coir-udyami-193',
            'code': 'COIR-UDYAMI',
            'name': 'Coir Udyami Yojana (CUY Credit Linked Subsidy)',
            'short_name': 'Coir Udyami Subsidy',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['artisan', 'coir_worker', 'entrepreneur'],
            'desc': 'Credit-linked capital subsidy of 25% of project cost (up to ₹10 Lakh) with bank loan of 55% and 5% beneficiary contribution for setting up coir processing units.',
            'benefit': '25% direct capital subsidy up to ₹2.50 Lakh on coir enterprise machinery',
            'quantum': '₹2,50,000 capital subsidy',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'self_employed', 'entrepreneur'], 'label': 'Coir Artisan / Entrepreneur', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'self_employed', 'entrepreneur']},
            'docs': ['Aadhaar Card', 'Project Feasibility Report', 'Coir Board Training Certificate', 'Bank Sanction Letter'],
            'url': 'https://coirboard.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'textiles-samarth-scheme-194',
            'code': 'SAMARTH-TEXTILES',
            'name': 'SAMARTH - Scheme for Capacity Building in Textile Sector',
            'short_name': 'SAMARTH Textile Skilling',
            'ministry': 'Ministry of Textiles',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['weaver', 'women', 'unemployed'],
            'desc': 'Demand-driven, placement-oriented skilling programme for 10 lakh individuals in organized textile and traditional sectors (handloom, handicraft, sericulture, jute) with wage employment.',
            'benefit': 'Free accredited skilling, biometric attendance stipend, and guaranteed placement',
            'quantum': 'Free Skilling & Guaranteed Placement Mandate',
            'type': 'in_kind_and_services',
            'days': 21,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 18},
            'docs': ['Aadhaar Card', 'Bank Account Passbook', 'Education Proof'],
            'url': 'https://samarth-textiles.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'textiles-nhdp-weavers-195',
            'code': 'NHDP-HANDLOOM',
            'name': 'National Handloom Development Programme (NHDP)',
            'short_name': 'NHDP Handloom Weaver Grant',
            'ministry': 'Ministry of Textiles',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['weaver', 'handloom_artisan'],
            'desc': 'Financial grant up to ₹40,000 for upgraded handloom frames, jacquards, and dobby accessories; subsidized raw yarn passbooks with 15% freight concession; and solar lighting units.',
            'benefit': 'Up to ₹40,000 equipment subsidy + 15% subsidized yarn supply',
            'quantum': '₹40,000 Loom Upgrade Grant & Subsidized Yarn',
            'type': 'capital_subsidy',
            'days': 20,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'weaver', 'craftsperson'], 'label': 'Handloom Weaver with Weaver Identity Card', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'weaver', 'craftsperson']},
            'docs': ['Weaver Identity Card (Pehchan ID)', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://handlooms.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'textiles-hastkala-sahayog-196',
            'code': 'HASTKALA-SAHAYOG',
            'name': 'Hastkala Sahayog Shivir (Artisan Welfare Convergence)',
            'short_name': 'Hastkala Sahayog Toolkits',
            'ministry': 'Ministry of Textiles',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['artisan', 'craftsperson'],
            'desc': 'On-the-spot distribution of modern upgraded toolkit equipment, credit sanction under Mudra/Stand-Up India, and issue of Pehchan Identity Cards across handicraft clusters.',
            'benefit': 'Free modern toolkits worth up to ₹10,000 + spot credit processing',
            'quantum': 'Free Upgraded Toolkit & Pehchan Card',
            'type': 'in_kind_and_services',
            'days': 7,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'craftsperson', 'weaver'], 'label': 'Handicraft Artisan', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'craftsperson', 'weaver']},
            'docs': ['Aadhaar Card', 'Proof of Craft Practice', 'Passport Photograph'],
            'url': 'https://handicrafts.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'commerce-gem-portal-197',
            'code': 'GEM-SELLER',
            'name': 'Government e-Marketplace (GeM) Direct Public Procurement Seller Scheme',
            'short_name': 'GeM National Marketplace Onboarding',
            'ministry': 'Ministry of Commerce and Industry',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['artisan', 'women_shg', 'msme', 'business'],
            'desc': '100% free direct onboarding onto GeM portal with zero transaction fee for micro sellers, accessing over ₹3 lakh crore in annual Central & State government tenders.',
            'benefit': 'Direct access to government procurement contracts without middle agents',
            'quantum': 'Direct Sovereign Procurement Contract Access',
            'type': 'in_kind_and_services',
            'days': 3,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'self_employed', 'artisan', 'entrepreneur'], 'label': 'Supplier / Manufacturer / Service Provider', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'self_employed', 'artisan', 'entrepreneur']},
            'docs': ['PAN Card', 'Udyam Registration Certificate', 'Bank Account Verification'],
            'url': 'https://gem.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'msme-ramp-worldbank-198',
            'code': 'RAMP-MSME',
            'name': 'Raising and Accelerating MSME Performance (RAMP Programme)',
            'short_name': 'RAMP MSME Competitiveness',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme', 'entrepreneur'],
            'desc': 'World Bank-supported ₹6,000 crore initiative upgrading state-level MSME policy implementation, market integration, green tech adoption, and digital supply chains.',
            'benefit': 'Direct institutional technical grants, green transition subsidies, and market access',
            'quantum': 'Subsidized Green Technology Upgradation',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'entrepreneur'], 'label': 'Udyam Registered MSME Enterprise', 'impact': 'moderate'}
            ],
            'flatRules': {'occupation': ['business', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Audited Financial Statements'],
            'url': 'https://ramp.msme.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'msme-international-exhibition-199',
            'code': 'IC-SCHEME-MSME',
            'name': 'International Cooperation (IC) Scheme for MSME Export Delegation',
            'short_name': 'MSME International Exhibition Subsidy',
            'ministry': 'Ministry of Micro, Small and Medium Enterprises',
            'state': 'All-India',
            'category': 'msme',
            'beneficiary_types': ['msme_exporter', 'business'],
            'desc': '100% economy airfare reimbursement (up to ₹1.5 Lakh) and 100% booth rental stall subsidy (up to ₹3 Lakh) for MSMEs participating in international trade fairs abroad.',
            'benefit': 'Airfare & stall booth rental subsidy up to ₹4.5 Lakh for global trade shows',
            'quantum': 'Up to ₹4,50,000 Export Exhibition Grant',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['business', 'entrepreneur'], 'label': 'Export-Oriented Registered MSME', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['business', 'entrepreneur']},
            'docs': ['Udyam Registration Certificate', 'Import Export Code (IEC)', 'Passport Copy', 'Fair Participation Invoice'],
            'url': 'https://ic.msme.gov.in',
            'completeness': 'VERIFIED'
        }
    ]
