# scripts/catalog_tribal.py

def get_schemes():
    return [
        {
            'id': 'tribal-pms-st-220',
            'code': 'PMS-ST',
            'name': 'Post Matric Scholarship for ST Students',
            'short_name': 'Post Matric Scholarship for ST',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'tribal_welfare',
            'beneficiary_types': ['st', 'student'],
            'desc': '100% financial assistance covering full non-refundable compulsory course tuition fees plus monthly maintenance allowance up to ₹1,200/month for Scheduled Tribe students studying at post-matriculation levels.',
            'benefit': 'Full tuition fee reimbursement + monthly maintenance allowance up to ₹14,400 / year',
            'quantum': '100% Tuition Fees + ₹14,400 Maintenance Allowance',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe (ST) Student', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Pursuing Recognized Post-Matric Course', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Parental Annual Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st'], 'occupation': ['student'], 'income_limit': 250000},
            'docs': ['ST Caste Certificate', 'Income Certificate', 'College Fee Receipt & Bonafide Certificate', 'Marksheet of Previous Exam'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-emrs-schools-221',
            'code': 'EMRS-SCHOOLS',
            'name': 'Eklavya Model Residential Schools (EMRS)',
            'short_name': 'EMRS Tribal CBSE Boarding Schools',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'education',
            'beneficiary_types': ['st', 'children', 'students'],
            'desc': '100% free quality CBSE residential education (Classes 6 to 12) including boarding, lodging, uniforms, textbooks, computers, and medical care for remote tribal children.',
            'benefit': 'Completely free CBSE residential schooling, boarding, sports, and competitive exam coaching',
            'quantum': '100% Free Quality Residential Boarding School',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe (ST) Child', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 10, 'label': 'Age Between 10 and 18 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 18, 'label': 'Age ≤ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st'], 'age_min': 10, 'age_max': 18},
            'docs': ['ST Caste Certificate', 'Class 5th Pass Marksheet (for Class 6 entry)', 'Aadhaar Card'],
            'url': 'https://emrs.tribal.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-van-dhan-222',
            'code': 'VAN-DHAN-YOJANA',
            'name': 'Pradhan Mantri Van Dhan Yojana (PMVDY)',
            'short_name': 'Van Dhan Tribal Forest Clusters',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'tribal_welfare',
            'beneficiary_types': ['tribal_gatherer', 'st', 'women_shg'],
            'desc': 'Establishes Van Dhan Vikas Kendras (VDVK) of 300 tribal forest gatherers with ₹15 Lakh working capital grant for value addition, packaging, and marketing of Minor Forest Produce.',
            'benefit': 'Working capital grant up to ₹15 Lakh per Kendra + modern processing equipment & market linkages',
            'quantum': '₹15,00,000 Cluster Working Capital Grant',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe Forest Produce Gatherer', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['farmer', 'artisan', 'daily_wage', 'unorganized_worker'], 'label': 'Forest Gatherer / Tribal SHG Member', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st'], 'occupation': ['farmer', 'artisan', 'daily_wage', 'unorganized_worker']},
            'docs': ['ST Certificate', 'Aadhaar Card', 'Van Dhan SHG Group Passbook'],
            'url': 'https://trifed.tribal.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-msp-mfp-223',
            'code': 'MSP-FOR-MFP',
            'name': 'Mechanism for Marketing of Minor Forest Produce (MSP for MFP)',
            'short_name': 'MSP for Minor Forest Produce',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'tribal_welfare',
            'beneficiary_types': ['tribal_gatherer', 'st'],
            'desc': 'Minimum Support Price guarantee for 87 items of Minor Forest Produce (tendu leaves, mahua flowers, lac, tamarind, honey, sal seeds) safeguarding tribal gatherers against exploitation.',
            'benefit': 'Guaranteed floor price purchase across state procurement depots with direct DBT payment',
            'quantum': 'Guaranteed Sovereign MSP Procurement',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe Forest Dweller', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st']},
            'docs': ['Tribal Identity Proof / Gram Sabha Certificate', 'Aadhaar Card', 'Bank Passbook'],
            'url': 'https://trifed.tribal.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-nf-higher-edu-224',
            'code': 'NFST-FELLOWSHIP',
            'name': 'National Fellowship and Scholarship for Higher Education of ST Students',
            'short_name': 'National Fellowship for ST (MPhil/PhD)',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['st', 'research_scholar'],
            'desc': 'Full funding for ST students pursuing MPhil and PhD courses (JRF: ₹37,000/month, SRF: ₹42,000/month) plus annual contingency grant of ₹10,000-₹20,500 and HRA.',
            'benefit': '₹37,000 - ₹42,000 monthly fellowship stipend + contingency grant for up to 5 years',
            'quantum': 'Up to ₹42,000 / month + Contingency',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe (ST) Scholar', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Regular MPhil / PhD Course', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st'], 'occupation': ['student']},
            'docs': ['ST Certificate', 'Post Graduation Marksheet (Minimum 55%)', 'University PhD Admission Letter', 'Bank Passbook'],
            'url': 'https://fellowship.tribal.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-overseas-st-225',
            'code': 'NOS-ST',
            'name': 'National Overseas Scholarship for ST Candidates',
            'short_name': 'National Overseas Scholarship (ST)',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['st', 'student'],
            'desc': '100% financial assistance covering full tuition fees, annual maintenance allowance ($15,400 USD / £9,900 GBP), contingency, medical insurance, and economy return airfare for foreign Masters and PhD degrees.',
            'benefit': '100% foreign university tuition + ~$15,400 annual living allowance + international airfare',
            'quantum': 'Full Foreign Tuition + Living Allowance',
            'type': 'direct_benefit',
            'days': 60,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Scheduled Tribe (ST) Student', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 35, 'label': 'Age Below 35 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 600000, 'label': 'Parental Annual Income ≤ ₹6.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st'], 'age_max': 35, 'income_limit': 600000},
            'docs': ['ST Caste Certificate', 'Foreign University Unconditional Offer Letter', 'IELTS / TOEFL Score Card', 'Income Certificate'],
            'url': 'https://overseas.tribal.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sc-pm-ajay-226',
            'code': 'PM-AJAY',
            'name': 'Pradhan Mantri Anusuchit Jaati Abhyuday Yojana (PM-AJAY)',
            'short_name': 'PM-AJAY SC Development Scheme',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'sc_welfare',
            'beneficiary_types': ['sc', 'bpl'],
            'desc': 'Merger of 3 schemes (Adarsh Gram, SCA to SCSP, Babu Jagjivan Ram Chhatrawas) providing grant-in-aid up to ₹50,000 or 50% project cost for SC income-generating livelihoods and village infrastructure.',
            'benefit': 'Up to ₹50,000 capital subsidy per beneficiary for setting up self-employment ventures',
            'quantum': '₹50,000 Capital Subsidy Grant',
            'type': 'capital_subsidy',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'sc', 'label': 'Scheduled Caste (SC) Beneficiary', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Annual Household Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'income_limit': 250000},
            'docs': ['SC Caste Certificate', 'Income Certificate', 'Project Livelihood Proposal', 'Bank Passbook'],
            'url': 'https://pmajay.dosje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sc-pre-matric-227',
            'code': 'PRE-MATRIC-SC',
            'name': 'Pre-Matric Scholarship Scheme for SC Students (Classes 9 & 10)',
            'short_name': 'Pre-Matric SC Scholarship',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'sc_welfare',
            'beneficiary_types': ['sc', 'student'],
            'desc': 'Financial assistance of ₹3,500/year for day scholars and ₹7,000/year for hostellers for SC students studying in Classes 9 and 10 to curb school dropout rates.',
            'benefit': 'Annual scholarship of ₹3,500 to ₹7,000 directly credited to student account',
            'quantum': '₹3,500 - ₹7,000 / year',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'sc', 'label': 'Scheduled Caste (SC) Student', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Class 9 or 10', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 250000, 'label': 'Annual Household Income ≤ ₹2.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'occupation': ['student'], 'income_limit': 250000},
            'docs': ['SC Caste Certificate', 'Income Certificate', 'School Enrollment Certificate', 'Bank Passbook'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sc-top-class-edu-228',
            'code': 'TOP-CLASS-SC',
            'name': 'Top Class Education Scheme for SC Students',
            'short_name': 'Top Class SC Scholarship (IIT/IIM/AIIMS)',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['sc', 'student'],
            'desc': '100% full tuition fee payment up to ₹2 Lakh p.a. (private) / full fee (govt), ₹86,000 annual living expenses, ₹86,000 computer grant, and ₹3,000 book allowance for SC students in premier institutes (IITs, NITs, IIMs, NLUs, AIIMS).',
            'benefit': '100% tuition fees + ₹86,000 annual living allowance + ₹86,000 laptop grant',
            'quantum': 'Full Premier Institute Tuition + ₹86,000 Living Allowance',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'sc', 'label': 'Scheduled Caste (SC) Candidate', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Admitted in Notified Premier Institution', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'occupation': ['student'], 'income_limit': 800000},
            'docs': ['SC Caste Certificate', 'Income Certificate', 'Institution Admission Fee Receipt', 'Institute Allotment Letter'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'sc-nos-overseas-229',
            'code': 'NOS-SC',
            'name': 'National Overseas Scholarship for SC Candidates',
            'short_name': 'National Overseas Scholarship (SC)',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['sc', 'student'],
            'desc': 'Sovereign fellowship funding 125 SC scholars annually for pursuing Masters and PhD in top 500 QS-ranked global universities, covering 100% tuition, airfare, and living allowance.',
            'benefit': '100% foreign university tuition + $15,400 USD annual living allowance + international airfare',
            'quantum': '100% Foreign Tuition & Living Allowance',
            'type': 'direct_benefit',
            'days': 60,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'sc', 'label': 'Scheduled Caste (SC) Candidate', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 35, 'label': 'Age ≤ 35 Years', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Income ≤ ₹8.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['sc'], 'age_max': 35, 'income_limit': 800000},
            'docs': ['SC Caste Certificate', 'Foreign University Admission Letter (Top 500 QS)', 'Bachelors/Masters Marksheets (≥ 60%)', 'Income Certificate'],
            'url': 'https://nosmsje.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'obc-shreyas-fellowship-230',
            'code': 'SHREYAS-OBC',
            'name': 'SHREYAS - National Fellowship for Other Backward Classes (NFOBC)',
            'short_name': 'National Fellowship for OBC (MPhil/PhD)',
            'ministry': 'Ministry of Social Justice and Empowerment',
            'state': 'All-India',
            'category': 'scholarships',
            'beneficiary_types': ['obc', 'research_scholar'],
            'desc': '1,000 annual fellowships for OBC students pursuing regular MPhil and PhD courses in recognized universities (JRF: ₹37,000/month, SRF: ₹42,000/month plus contingency & HRA).',
            'benefit': '₹37,000 - ₹42,000 monthly fellowship stipend + contingency grant for 5 years',
            'quantum': 'Up to ₹42,000 / month Fellowship',
            'type': 'direct_benefit',
            'days': 45,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'obc', 'label': 'OBC (Non-Creamy Layer) Candidate', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Regular MPhil / PhD Course', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Family Annual Income ≤ ₹8.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['obc'], 'occupation': ['student'], 'income_limit': 800000},
            'docs': ['OBC Non-Creamy Layer Certificate', 'UGC-NET / CSIR-NET Score Card', 'PhD Enrollment Certificate', 'Income Certificate'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'minority-begum-hazrat-231',
            'code': 'BEGUM-HAZRAT-MAHAL',
            'name': 'Begum Hazrat Mahal National Scholarship for Minority Girls',
            'short_name': 'Begum Hazrat Mahal Minority Girls Scholarship',
            'ministry': 'Ministry of Minority Affairs',
            'state': 'All-India',
            'category': 'minority_welfare',
            'beneficiary_types': ['minority', 'girl_child', 'student'],
            'desc': 'Direct scholarship of ₹5,000 (Classes 9-10) and ₹6,000 (Classes 11-12) for meritorious girl students belonging to 6 notified minority communities (Muslim, Christian, Sikh, Buddhist, Jain, Parsi).',
            'benefit': '₹5,000 - ₹6,000 annual scholarship credited directly to girl student bank account',
            'quantum': '₹5,000 - ₹6,000 / year',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Minority Student', 'impact': 'critical'},
                {'field': 'citizen.occupation', 'op': 'EQ', 'value': 'student', 'label': 'Enrolled in Class 9, 10, 11, or 12', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 200000, 'label': 'Parental Annual Income ≤ ₹2.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'occupation': ['student'], 'income_limit': 200000},
            'docs': ['Minority Self-Declaration Certificate', 'Previous Year Marksheet (Minimum 50%)', 'Income Certificate', 'School Verification Form'],
            'url': 'https://scholarships.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'minority-nai-udaan-232',
            'code': 'NAI-UDAAN',
            'name': 'Nai Udaan - Financial Support for Minority Candidates Clearing Prelims',
            'short_name': 'Nai Udaan UPSC / PSC Prelims Incentive',
            'ministry': 'Ministry of Minority Affairs',
            'state': 'All-India',
            'category': 'minority_welfare',
            'beneficiary_types': ['minority', 'aspirant', 'youth'],
            'desc': 'Direct financial assistance of ₹1,00,000 for clearing UPSC Civil Services Prelims and ₹50,000 for clearing State PSC Group-A/B Prelims for youth from 6 notified minority communities.',
            'benefit': '₹1,00,000 cash grant for UPSC Mains preparation / ₹50,000 for State PSC Mains',
            'quantum': 'Up to ₹1,00,000 lump sum preparation grant',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.category', 'op': 'IN', 'value': ['minority', 'general', 'obc', 'sc', 'st'], 'label': 'Member of 6 Notified Minority Communities', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 800000, 'label': 'Total Annual Family Income ≤ ₹8.0 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['minority', 'general', 'obc', 'sc', 'st'], 'income_limit': 800000},
            'docs': ['Preliminary Exam Admit Card & Result Gazette Roll No', 'Minority Community Certificate', 'Income Certificate', 'Bank Passbook'],
            'url': 'https://minorityaffairs.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'minority-pm-vikas-233',
            'code': 'PM-VIKAS-MINORITY',
            'name': 'Pradhan Mantri Virasat Ka Samvardhan (PM VIKAS)',
            'short_name': 'PM VIKAS Artisan Convergence',
            'ministry': 'Ministry of Minority Affairs',
            'state': 'All-India',
            'category': 'artisan_crafts',
            'beneficiary_types': ['minority_artisan', 'craftsperson', 'women'],
            'desc': 'Convergence of 5 erstwhile schemes (Hunar Haat, USTTAD, Hamari Dharohar, Nai Roshni, Nai Manzil) providing end-to-end artisan skilling, modern design workshops, master trainer stipends, and international trade linkages.',
            'benefit': 'Free master artisan certification, daily training stipend, and zero-fee exhibition stalls at Hunar Haat',
            'quantum': 'Free Skilling + Training Stipend + Exhibition Stall',
            'type': 'in_kind_and_services',
            'days': 21,
            'rules': [
                {'field': 'citizen.occupation', 'op': 'IN', 'value': ['artisan', 'craftsperson', 'weaver', 'self_employed'], 'label': 'Traditional Artisan / Craftsperson from Minority/Artisan Family', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 18, 'label': 'Age ≥ 18 Years', 'impact': 'critical'}
            ],
            'flatRules': {'occupation': ['artisan', 'craftsperson', 'weaver', 'self_employed'], 'age_min': 18},
            'docs': ['Aadhaar Card', 'Minority Community / Artisan Self-Declaration', 'Bank Passbook'],
            'url': 'https://minorityaffairs.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'minority-seekho-kamao-234',
            'code': 'SEEKHO-AUR-KAMAO',
            'name': 'Seekho Aur Kamao (Learn & Earn - Skilling for Minorities)',
            'short_name': 'Seekho Aur Kamao Skilling',
            'ministry': 'Ministry of Minority Affairs',
            'state': 'All-India',
            'category': 'skill_development',
            'beneficiary_types': ['minority', 'youth', 'unemployed'],
            'desc': 'Employment-linked skill training for minority youth (14-35 years) with modern modular courses, monthly stipend of ₹1,500 during training, and guaranteed minimum 75% placement.',
            'benefit': 'Free skill certification + ₹1,500/month training stipend + guaranteed wage placement',
            'quantum': 'Free Skilling + ₹1,500 / month Stipend',
            'type': 'in_kind_and_services',
            'days': 20,
            'rules': [
                {'field': 'citizen.age', 'op': 'GTE', 'value': 14, 'label': 'Age Between 14 and 35 Years', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'LTE', 'value': 35, 'label': 'Age ≤ 35 Years', 'impact': 'critical'}
            ],
            'flatRules': {'age_min': 14, 'age_max': 35},
            'docs': ['Aadhaar Card', 'School Marksheet', 'Minority Community Certificate'],
            'url': 'https://minorityaffairs.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tribal-pvtg-mission-235',
            'code': 'PM-JANMAN-MISSION',
            'name': 'Pradhan Mantri Janjati Adivasi Nyaya Maha Abhiyan (PM-JANMAN 11 Interventions)',
            'short_name': 'PM-JANMAN Tribal Mission',
            'ministry': 'Ministry of Tribal Affairs',
            'state': 'All-India',
            'category': 'tribal_welfare',
            'beneficiary_types': ['pvtg_tribal', 'st'],
            'desc': 'Comprehensive ₹24,000 crore mission covering 75 Particularly Vulnerable Tribal Groups across 18 states with 11 critical interventions: pucca housing, piped water, road connectivity, mobile medical units, and solar electrification.',
            'benefit': 'Guaranteed saturation of all 11 basic services (housing, electricity, water, roads, health) directly in PVTG habitations',
            'quantum': '100% Saturation Package of 11 Basic Services',
            'type': 'in_kind_and_services',
            'days': 30,
            'rules': [
                {'field': 'citizen.category', 'op': 'EQ', 'value': 'st', 'label': 'Identified PVTG Community Resident', 'impact': 'critical'}
            ],
            'flatRules': {'category': ['st']},
            'docs': ['PVTG Tribe Certificate / Gram Sabha Certification', 'Aadhaar Card'],
            'url': 'https://tribal.nic.in',
            'completeness': 'VERIFIED'
        }
    ]
