# scripts/catalog_healthcare.py

def get_schemes():
    return [
        {
            'id': 'pm-abhim-082',
            'code': 'PM-ABHIM',
            'name': 'PM Ayushman Bharat Health Infrastructure Mission',
            'short_name': 'PM-ABHIM Free Lab Tests',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen'],
            'desc': 'Free 134 essential diagnostic tests at Ayushman Arogya Mandirs and District Integrated Public Health Labs.',
            'benefit': '134 Free Pathological, Radiological & Biochemical Clinical Tests',
            'quantum': 'Free Diagnostic Care (Saves ₹3,000 - ₹15,000/yr)',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'All Citizens', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card / ABHA Health ID'],
            'url': 'https://ab-hwc.nhp.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pm-dialysis-083',
            'code': 'PMNDP',
            'name': 'Pradhan Mantri National Dialysis Programme',
            'short_name': 'PM National Dialysis',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['bpl', 'citizen', 'patient'],
            'desc': '100% free Hemodialysis and Peritoneal Dialysis for BPL and Ayushman Bharat beneficiaries at all District Hospitals.',
            'benefit': '100% Free Dialysis Sessions (Saves ₹2,000 - ₹3,000 per session / ~₹2.5 Lakh annually)',
            'quantum': 'Free Haemodialysis',
            'type': 'in_kind',
            'days': 3,
            'rules': [{'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Cardholder or Ayushman Cardholder', 'impact': 'critical'}],
            'flatRules': {'bpl_required': True},
            'docs': ['Aadhaar Card', 'BPL Ration Card / PMJAY Card', 'Nephrologist Prescription'],
            'url': 'https://nhm.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'janani-suraksha-084',
            'code': 'JSY-MATERNAL',
            'name': 'Janani Suraksha Yojana Institutional Delivery Cash Incentive',
            'short_name': 'Janani Suraksha Yojana',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['pregnant_women', 'mothers'],
            'desc': 'Cash assistance of ₹1,400 (Rural) and ₹1,000 (Urban) for institutional delivery in public and accredited health centres.',
            'benefit': '₹1,400 DBT upon institutional child delivery + Free ambulance transport',
            'quantum': '₹1,400 DBT',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [
                {'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Female Beneficiary', 'impact': 'critical'},
                {'field': 'citizen.age', 'op': 'GTE', 'value': 19, 'label': 'Age 19+ Years', 'impact': 'critical'}
            ],
            'flatRules': {'gender': ['female'], 'min_age': 19},
            'docs': ['Aadhaar Card', 'MCP Card', 'Hospital Discharge Summary', 'Bank Passbook'],
            'url': 'https://nhm.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'jssk-cashless-085',
            'code': 'JSSK',
            'name': 'Janani Shishu Suraksha Karyakram Zero-Expense Guarantee',
            'short_name': 'JSSK Cashless Delivery',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['pregnant_women', 'infants'],
            'desc': 'Completely zero out-of-pocket expenses for delivery (including C-section), free drugs, diagnostics, blood transfusion, and diet for 30 days post delivery and sick infants.',
            'benefit': '100% Free Drugs, Consumables, C-Section, Blood Transfusion & Diet',
            'quantum': 'Complete Cashless Care (Saves ₹10,000 - ₹50,000)',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Pregnant Woman or Sick Infant', 'impact': 'critical'}],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card', 'MCP Card'],
            'url': 'https://nhm.gov.in/index1.php?lang=1&level=2&sublinkid=841&lid=309',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'rbsk-screening-086',
            'code': 'RBSK-CHILD',
            'name': 'Rashtriya Bal Swasthya Karyakram Child Health Screening',
            'short_name': 'RBSK Child Screening & Surgery',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['children', 'students'],
            'desc': 'Free screening and surgical treatment for 30 health conditions (Birth defects, Deficiencies, Diseases, Developmental delays) for children 0-18 years.',
            'benefit': '100% Free Tertiary Medical Treatment & Surgeries (Congenital heart defect, Clubfoot, Cleft lip)',
            'quantum': 'Free Tertiary Surgeries',
            'type': 'in_kind',
            'days': 14,
            'rules': [{'field': 'citizen.age', 'op': 'LTE', 'value': 18, 'label': 'Child Age 0 to 18 Years', 'impact': 'critical'}],
            'flatRules': {'max_age': 18},
            'docs': ['Aadhaar Card of Child/Parent', 'School / Anganwadi Screening Card'],
            'url': 'https://rbsk.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'pmsma-antenatal-087',
            'code': 'PMSMA',
            'name': 'Pradhan Mantri Surakshit Matritva Abhiyan (9th of Month Antenatal Care)',
            'short_name': 'PMSMA Fixed-Day Antenatal Care',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['pregnant_women'],
            'desc': 'Guaranteed, comprehensive and quality antenatal care, including ultrasound and specialist examination, free of cost on the 9th of every month.',
            'benefit': 'Free Specialist Obstetrician Consultation + Ultrasound + Blood Panel',
            'quantum': 'Free Clinical Examination',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.gender', 'op': 'EQ', 'value': 'female', 'label': 'Pregnant Woman in 2nd/3rd Trimester', 'impact': 'critical'}],
            'flatRules': {'gender': ['female']},
            'docs': ['Aadhaar Card', 'Mother and Child Protection (MCP) Card'],
            'url': 'https://pmsma.nhp.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'mission-indradhanush-088',
            'code': 'IMI-5',
            'name': 'Intensified Mission Indradhanush (Universal Immunization)',
            'short_name': 'Mission Indradhanush Vaccines',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['children', 'pregnant_women'],
            'desc': '100% free immunization covering 12 life-threatening vaccine-preventable diseases (Polio, Measles-Rubella, Hepatitis B, Rotavirus, Pneumococcal).',
            'benefit': 'Free WHO-Prequalified 12 Vaccine Regimen + Digital U-WIN Tracking',
            'quantum': 'Free Complete Immunization',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'LTE', 'value': 5, 'label': 'Child under 5 years or Pregnant Woman', 'impact': 'critical'}],
            'flatRules': {'max_age': 5},
            'docs': ['Aadhaar Card of Parent', 'Immunization Card / U-WIN ID'],
            'url': 'https://uwin.mohfw.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'nikshay-poshan-089',
            'code': 'NIKSHAY-POSHAN',
            'name': 'Ni-kshay Poshan Yojana (TB Nutritional Support DBT)',
            'short_name': 'Ni-kshay Poshan TB DBT',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['tb_patients', 'citizen'],
            'desc': 'Direct Benefit Transfer of ₹500 per month for every TB patient throughout the duration of anti-tubercular treatment.',
            'benefit': '₹500 / month direct bank transfer for nutritional food during treatment',
            'quantum': '₹500 / month',
            'type': 'direct_benefit',
            'days': 7,
            'rules': [{'field': 'citizen.bank_account', 'op': 'EQ', 'value': True, 'label': 'Aadhaar-Linked Bank Account', 'impact': 'critical'}],
            'flatRules': {'bank_account_required': True},
            'docs': ['Aadhaar Card', 'Ni-kshay ID from Public Health Center', 'Bank Passbook'],
            'url': 'https://nikshay.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'janaushadhi-medicines-090',
            'code': 'PMBJP',
            'name': 'Pradhan Mantri Bhartiya Janaushadhi Pariyojana',
            'short_name': 'Janaushadhi Generic Medicines (50-90% Discount)',
            'ministry': 'Ministry of Chemicals and Fertilizers',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen'],
            'desc': 'Provides 2,047 high quality generic medicines and 300 surgical devices at 50% to 90% lesser price than branded equivalents.',
            'benefit': '50% to 90% lower medicine bills + ₹1 Oxo-biodegradable sanitary napkins',
            'quantum': 'Up to 90% Medicine Discount',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'Open to All Indian Citizens', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Doctor Prescription (Optional for OTC)'],
            'url': 'https://janaushadhi.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'rashtriya-arogya-nidhi-091',
            'code': 'RAN-CANCER',
            'name': 'Rashtriya Arogya Nidhi (Financial Aid for Life-Threatening Diseases)',
            'short_name': 'Rashtriya Arogya Nidhi Grant',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['bpl', 'cancer_patients', 'chronic_patients'],
            'desc': 'One-time financial assistance up to ₹15 Lakh for BPL patients suffering from major life-threatening diseases receiving treatment at super-speciality government hospitals.',
            'benefit': 'Grant up to ₹15,00,000 directly transferred to Treating Super-Speciality Hospital',
            'quantum': '₹15,00,000 medical grant',
            'type': 'direct_benefit',
            'days': 21,
            'rules': [
                {'field': 'citizen.bpl_card', 'op': 'EQ', 'value': True, 'label': 'BPL Ration Cardholder', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 120000, 'label': 'Annual Household Income < ₹1.2 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'bpl_required': True, 'income_limit': 120000},
            'docs': ['Aadhaar Card', 'BPL Card / Income Certificate', 'Hospital Treatment Estimate Letter'],
            'url': 'https://mohfw.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'hmdg-medical-relief-092',
            'code': 'HMDG',
            'name': 'Health Minister\'s Discretionary Grant',
            'short_name': 'Health Minister Discretionary Aid',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen', 'poor'],
            'desc': 'Financial assistance up to ₹1,25,000 for poor patients suffering from critical illnesses who are not covered under any other health scheme.',
            'benefit': 'Financial grant up to ₹1,25,000 for hospitalization and surgical interventions',
            'quantum': '₹1,25,000 grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 150000, 'label': 'Annual Family Income < ₹1.5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'income_limit': 150000},
            'docs': ['Aadhaar Card', 'Income Certificate', 'Medical Estimate from Govt Hospital'],
            'url': 'https://mohfw.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'rare-diseases-policy-093',
            'code': 'NPRD-RARE',
            'name': 'National Policy for Rare Diseases Financial Support',
            'short_name': 'Rare Diseases ₹50 Lakh Grant',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['rare_disease_patients', 'children'],
            'desc': 'Direct financial assistance up to ₹50 Lakh per patient for treatment of specified rare diseases (Group 1, 2 & 3) at designated Centre of Excellence (CoE) hospitals.',
            'benefit': '100% Free Rare Disease Treatment / Enzyme Replacement Therapy up to ₹50 Lakh',
            'quantum': '₹50,00,000 treatment cover',
            'type': 'in_kind',
            'days': 30,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'Citizen Diagnosed with Group 1/2/3 Rare Disease', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card', 'Medical Board Rare Disease Diagnostic Report', 'CoE Hospital Recommendation'],
            'url': 'https://rarediseases.mohfw.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'tele-manas-mental-094',
            'code': 'TELE-MANAS',
            'name': 'National Tele Mental Health Programme (Tele-MANAS 14416)',
            'short_name': 'Tele-MANAS 24x7 Mental Health Helpline',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen', 'youth', 'students'],
            'desc': 'Free 24x7 toll-free mental health counselling and psychological tele-consultation in 20 languages by trained psychologists and psychiatrists.',
            'benefit': 'Free 24x7 Confidential Psychological Support & Hospital Referral',
            'quantum': 'Free Tele-Counselling',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 12, 'label': 'All Individuals', 'impact': 'moderate'}],
            'flatRules': {},
            'docs': [],
            'url': 'https://telemanas.mohfw.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'viral-hepatitis-control-095',
            'code': 'NVHCP',
            'name': 'National Viral Hepatitis Control Program',
            'short_name': 'Free Hepatitis B & C Treatment',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen', 'patient'],
            'desc': '100% free viral load diagnosis and complete direct-acting antiviral (DAA) treatment regimen for Hepatitis B and Hepatitis C.',
            'benefit': 'Free 12-week complete cure oral regimen for Hepatitis C (Saves ₹25,000 - ₹50,000)',
            'quantum': 'Free Antiviral Medicine Course',
            'type': 'in_kind',
            'days': 5,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'All Citizens with Positive Screening', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card', 'Viral Load Lab Test Report'],
            'url': 'https://nvhcp.mohfw.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'leprosy-eradication-096',
            'code': 'NLEP-MD',
            'name': 'National Leprosy Eradication Programme (Disability Compensation)',
            'short_name': 'NLEP Reconstructive Surgery Grant',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['leprosy_cured', 'disability'],
            'desc': 'Free Multidrug Therapy (MDT), reconstructive surgery, and financial compensation of ₹12,000 for wage loss during reconstructive surgery.',
            'benefit': 'Free Reconstructive Surgery + ₹12,000 Wage Loss Cash Support',
            'quantum': '₹12,000 cash grant + Free surgery',
            'type': 'direct_benefit',
            'days': 15,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 16, 'label': 'Person Affected by Leprosy Disability', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card', 'NLEP Treatment Card', 'Bank Passbook'],
            'url': 'https://nlep.nic.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'blindness-control-097',
            'code': 'NPCBVI',
            'name': 'National Programme for Control of Blindness & Visual Impairment',
            'short_name': 'Free Cataract IOL Surgery',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['senior', 'citizen'],
            'desc': '100% free cataract surgery with Intraocular Lens (IOL) implantation and free spectacles for school children and senior citizens.',
            'benefit': '100% Free SICS/Phaco Cataract Surgery with Foldable IOL + Free Glasses',
            'quantum': 'Free Surgical Care (Saves ₹15,000 - ₹35,000)',
            'type': 'in_kind',
            'days': 7,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 50, 'label': 'Age 50+ Years (or school children screened)', 'impact': 'moderate'}],
            'flatRules': {'min_age': 50},
            'docs': ['Aadhaar Card', 'Ophthalmic Screening Slip'],
            'url': 'https://npcbvi.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'abdm-health-account-098',
            'code': 'ABDM-ABHA',
            'name': 'Ayushman Bharat Digital Mission (ABHA Digital Health Card)',
            'short_name': 'ABHA 14-Digit Health ID',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen'],
            'desc': 'Unique 14-digit digital health ID linked to Aadhaar enabling interoperable, paperless health records and fast OPD registration.',
            'benefit': 'Instant paperless hospital registration via Scan & Share QR code',
            'quantum': 'Free Digital Health Account',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'All Citizens', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card with Mobile OTP'],
            'url': 'https://healthid.abdm.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'oral-health-programme-099',
            'code': 'NOHP-DENTAL',
            'name': 'National Oral Health Programme (Community Dental Care)',
            'short_name': 'Free District Hospital Dental Care',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen'],
            'desc': 'Free dental check-up, ultrasonic scaling, tooth extraction, and restorative fillings at all District and Sub-District hospitals.',
            'benefit': '100% Free Dental Fillings, Cleaning & Surgical Extractions',
            'quantum': 'Free Dental Treatment',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'All Citizens', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card / Hospital OPD Slip'],
            'url': 'https://dghs.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'emergency-ambulance-100',
            'code': 'EMTS-108',
            'name': 'National Ambulance Service (108 Emergency / 102 Maternal Transfer)',
            'short_name': 'Toll-Free 108 Emergency Ambulance',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen'],
            'desc': '24x7 toll-free GPS-tracked emergency response with Basic Life Support (BLS) and Advanced Life Support (ALS) ambulances.',
            'benefit': 'Zero-cost emergency hospital transport with on-board paramedic resuscitation',
            'quantum': 'Free Emergency Service',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'All Citizens in Emergency', 'impact': 'moderate'}],
            'flatRules': {},
            'docs': [],
            'url': 'https://nhm.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        },
        {
            'id': 'npcdcs-lifestyle-screening-101',
            'code': 'NP-NCD',
            'name': 'National Programme for Prevention of Non-Communicable Diseases',
            'short_name': 'Free Diabetes & Hypertension Clinic',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['senior', 'citizen'],
            'desc': 'Universal population-based screening of citizens aged 30+ for hypertension, diabetes, oral, breast, and cervical cancers with free monthly medicines.',
            'benefit': 'Free Monthly Metformin/Amlodipine Medicine Supply + Cancer Screening',
            'quantum': 'Free Medicine Refills (Saves ₹1,000 - ₹2,500/month)',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 30, 'label': 'Age 30+ Years', 'impact': 'critical'}],
            'flatRules': {'min_age': 30},
            'docs': ['Aadhaar Card / NCD Card'],
            'url': 'https://ncd.nhp.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'thalassemia-bal-sewa-102',
            'code': 'TBSY',
            'name': 'Thalassemia Bal Sewa Yojana (Bone Marrow Transplant Grant)',
            'short_name': 'Thalassemia BMT ₹10 Lakh Grant',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['children', 'patient'],
            'desc': 'Financial support up to ₹10 Lakh for curative allogeneic Bone Marrow Transplantation (BMT) for eligible children with Thalassemia and Aplastic Anemia.',
            'benefit': 'Grant up to ₹10,00,000 for curative Bone Marrow Transplant at empanelled hospital',
            'quantum': '₹10,00,000 BMT grant',
            'type': 'direct_benefit',
            'days': 30,
            'rules': [
                {'field': 'citizen.age', 'op': 'LTE', 'value': 12, 'label': 'Child under 12 years of age', 'impact': 'critical'},
                {'field': 'household.income_annual', 'op': 'LTE', 'value': 500000, 'label': 'Family Annual Income ≤ ₹5 Lakh', 'impact': 'critical'}
            ],
            'flatRules': {'max_age': 12, 'income_limit': 500000},
            'docs': ['Aadhaar Card', 'Income Certificate', 'HLA Typing Report', 'Empanelled Hospital Estimate'],
            'url': 'https://ccl.gov.in',
            'completeness': 'VERIFIED'
        },
        {
            'id': 'burns-management-103',
            'code': 'NPBM',
            'name': 'National Programme for Prevention and Management of Burn Injuries',
            'short_name': 'Burn Injury Critical Care',
            'ministry': 'Ministry of Health and Family Welfare',
            'state': 'All-India',
            'category': 'health',
            'beneficiary_types': ['citizen', 'women'],
            'desc': 'Specialized acute burn care, dressing, and skin grafting treatment at dedicated Medical College Burn Units free of cost for vulnerable citizens.',
            'benefit': '100% Free Specialized Burn ICU Care & Skin Grafting',
            'quantum': 'Free Critical Care',
            'type': 'in_kind',
            'days': 1,
            'rules': [{'field': 'citizen.age', 'op': 'GTE', 'value': 0, 'label': 'Burn Injury Patients', 'impact': 'critical'}],
            'flatRules': {},
            'docs': ['Aadhaar Card / Hospital Admission Record'],
            'url': 'https://dghs.gov.in',
            'completeness': 'INFORMATIONAL_ONLY'
        }
    ]
