import React, { createContext, useContext, useState, useEffect } from 'react';
import { passportTranslations } from './passportTranslations';

const LanguageContext = createContext(null);

export const translations = {
  en: {
    // Nav Groups
    groupHome: 'HOME',
    groupMyWelfare: 'MY WELFARE',
    groupDiscover: 'DISCOVER',
    groupMyJourney: 'MY JOURNEY',
    groupAssist: 'ASSIST',
    groupAccount: 'ACCOUNT',

    // Mobile Bottom Nav
    navHome: 'Home',
    navEntitlements: 'Entitlements',
    navLocker: 'Locker',
    navTracker: 'Tracker',
    navMenu: 'Menu',

    // Core Citizen Navigation
    dashboard: 'Dashboard',
    welfarePassport: 'Welfare Passport',
    household: 'Household Graph',
    documentVault: 'Document Vault',
    benefitsWallet: 'Benefits Wallet',
    schemesCatalogue: 'Schemes Catalogue',
    aiRecommendations: 'Smart Recommendations',
    compareSchemes: 'Compare Schemes',
    applyProcess: 'Application Hub',
    trackStatus: 'Track Status',
    notifications: 'Notifications',
    askSaarthi: 'Ask Saarthi AI',
    settings: 'Settings',
    accountSettings: 'Account Settings',
    searchOrJump: 'Search schemes, benefits...',
    language: 'Language',
    signOut: 'Sign Out',
    verifiedCitizen: 'Verified Citizen Passport',

    // Explorer & Search
    exploreCatalogues: 'Explore Welfare Catalogues',
    exploreDesc: 'Discover official Central & State schemes with deterministic eligibility breakdowns and verified government sources.',
    naturalLanguageSearch: 'NATURAL LANGUAGE INTENT SEARCH',
    searchPlaceholder: 'Search by scheme name, ministry, keyword, or type your situation...',
    samplePromptsTitle: 'Sample Queries',
    filterByState: 'Filter by State',
    allStates: 'All States (All-India + State Schemes)',
    allCatalogues: 'All Catalogues',
    schemesFound: 'Schemes Available',
    clearFilters: 'Clear Filters',
    viewDetails: 'View Details',
    applyNow: 'Apply on Portal',
    bookmarkScheme: 'Save Scheme',
    savedSchemes: 'Saved Schemes',
    matchScore: 'Match Score',

    // Categories
    catAll: 'All Catalogues',
    catAgriculture: '🌾 Agriculture & Farmers',
    catHealthcare: '🏥 Health & PMJAY',
    catEducation: '🎓 Education & Scholarships',
    catSocialSecurity: '🛡️ Social Security & Pension',
    catSkillTraining: '🔨 Skilling & MSME',
    catHousing: '🏠 Housing & Sanitation',
    catCredit: '💳 Credit & Financial Inclusion',
    catWomenChild: '👩 Women & Child Welfare',
    catCampusPilot: '🎓 Campus Welfare Pilot',

    // Statuses
    eligible: 'Eligible',
    nearlyEligible: 'Near-Miss Advisory',
    missingInfo: 'Missing Info',
    ineligible: 'Ineligible',
    partiallyVerified: 'Partially Verified',
    informationalOnly: 'Informational Only',

    // Details & Dossier
    viewDossier: 'Official Dossier',
    downloadCertificate: 'Download Passport Dossier',
    verified: 'Verified',
    actionRequired: 'Action Required',
    decisionReference: 'Decision Reference ID',
    annualIncome: 'Annual Income',
    statutoryBenefit: 'Statutory Benefit'
  },
  hi: {
    groupHome: 'होम',
    groupMyWelfare: 'मेरा कल्याण',
    groupDiscover: 'खोजें',
    groupMyJourney: 'मेरी यात्रा',
    groupAssist: 'सहायता',
    groupAccount: 'खाता',

    navHome: 'होम',
    navEntitlements: 'योजनाएं',
    navLocker: 'लॉकर',
    navTracker: 'ट्रैकर',
    navMenu: 'मेनू',

    dashboard: 'डैशबोर्ड',
    welfarePassport: 'कल्याण पासपोर्ट',
    household: 'परिवार सदस्य',
    documentVault: 'दस्तावेज़ लॉकर',
    benefitsWallet: 'लाभ वॉलेट',
    schemesCatalogue: 'योजना कैटलॉग',
    aiRecommendations: 'पात्र योजनाएं',
    compareSchemes: 'योजना तुलना',
    applyProcess: 'आवेदन प्रक्रिया',
    trackStatus: 'आवेदन स्थिति',
    notifications: 'सूचनाएं',
    askSaarthi: 'सारथी AI से पूछें',
    settings: 'सेटिंग्स',
    accountSettings: 'खाता सेटिंग्स',
    searchOrJump: 'योजनाएं या लाभ खोजें...',
    language: 'भाषा',
    signOut: 'लॉग आउट',
    verifiedCitizen: 'सत्यापित नागरिक पासपोर्ट',

    exploreCatalogues: 'कल्याणकारी योजनाएं खोजें',
    exploreDesc: 'सत्यापित सरकारी स्रोतों और पात्रता नियमों के साथ केंद्र और राज्य की योजनाएं खोजें।',
    naturalLanguageSearch: 'प्राकृतिक भाषा खोज',
    searchPlaceholder: 'योजना का नाम, मंत्रालय, कीवर्ड या अपनी स्थिति लिखें...',
    samplePromptsTitle: 'नमूना खोज',
    filterByState: 'राज्य अनुसार फ़िल्टर',
    allStates: 'सभी राज्य (अखिल भारतीय + राज्य योजनाएं)',
    allCatalogues: 'सभी श्रेणियां',
    schemesFound: 'योजनाएं उपलब्ध',
    clearFilters: 'फ़िल्टर हटाएं',
    viewDetails: 'विवरण देखें',
    applyNow: 'पोर्टल पर आवेदन करें',
    bookmarkScheme: 'सहेजें',
    savedSchemes: 'सहेजी गई योजनाएं',
    matchScore: 'पात्रता स्कोर',

    catAll: 'सभी श्रेणियां',
    catAgriculture: '🌾 कृषि एवं किसान',
    catHealthcare: '🏥 स्वास्थ्य एवं आयुष्मान',
    catEducation: '🎓 शिक्षा एवं छात्रवृत्ति',
    catSocialSecurity: '🛡️ सामाजिक सुरक्षा व पेंशन',
    catSkillTraining: '🔨 कौशल विकास व एमएसएमई',
    catHousing: '🏠 आवास एवं स्वच्छता',
    catCredit: '💳 ऋण व वित्तीय समावेशन',
    catWomenChild: '👩 महिला एवं बाल विकास',

    eligible: 'पात्र',
    nearlyEligible: 'निकटतम पात्रता',
    missingInfo: 'अपूर्ण जानकारी',
    ineligible: 'अपात्र',
    partiallyVerified: 'आंशिक सत्यापित',
    informationalOnly: 'केवल जानकारी हेतु',

    viewDossier: 'आधिकारिक डोजियर',
    downloadCertificate: 'पासपोर्ट डोजियर डाउनलोड करें',
    verified: 'सत्यापित',
    actionRequired: 'कार्रवाई आवश्यक',
    decisionReference: 'निर्णय संदर्भ संख्या',
    annualIncome: 'वार्षिक आय',
    statutoryBenefit: 'कानूनी लाभ'
  },
  gu: {
    groupHome: 'હોમ',
    groupMyWelfare: 'મારું કલ્યાણ',
    groupDiscover: 'શોધો',
    groupMyJourney: 'મારી યાત્રા',
    groupAssist: 'સહાય',
    groupAccount: 'ખાતું',

    navHome: 'હોમ',
    navEntitlements: 'યોજનાઓ',
    navLocker: 'લોકર',
    navTracker: 'ટ્રેકર',
    navMenu: 'મેનુ',

    dashboard: 'ડેશબોર્ડ',
    welfarePassport: 'કલ્યાણ પાસપોર્ટ',
    household: 'કુટુંબ સભ્યો',
    documentVault: 'દસ્તાવેજ લોકર',
    benefitsWallet: 'લાભ વોલેટ',
    schemesCatalogue: 'યોજના સૂચિ',
    aiRecommendations: 'લાયક યોજનાઓ',
    compareSchemes: 'યોજના સરખામણી',
    applyProcess: 'અરજી પ્રક્રિયા',
    trackStatus: 'અરજી સ્થિતિ',
    notifications: 'સૂચનાઓ',
    askSaarthi: 'સારથી AI ને પૂછો',
    settings: 'સેટિંગ્સ',
    accountSettings: 'ખાતા સેટિંગ્સ',
    searchOrJump: 'યોજનાઓ અથવા લાભ શોધો...',
    language: 'ભાષા',
    signOut: 'લૉગ આઉટ',
    verifiedCitizen: 'ચકાસાયેલ નાગરિક પાસપોર્ટ',

    exploreCatalogues: 'કલ્યાણકારી યોજનાઓ શોધો',
    exploreDesc: 'સત્તાવાર સરકારી સ્ત્રોતો અને યોગ્યતા માપદંડો સાથે કેન્દ્ર અને રાજ્ય સરકારની યોજનાઓ શોધો.',
    naturalLanguageSearch: 'સરળ ભાષા શોધ',
    searchPlaceholder: 'યોજનાનું નામ, મંત્રાલય, કીવર્ડ અથવા તમારી વિગત લખો...',
    samplePromptsTitle: 'નમૂના પ્રશ્નો',
    filterByState: 'રાજ્ય મુજબ ફિલ્ટર',
    allStates: 'બધા રાજ્યો (સમગ્ર ભારત + રાજ્ય યોજનાઓ)',
    allCatalogues: 'બધી કેટેગરી',
    schemesFound: 'યોજનાઓ ઉપલબ્ધ',
    clearFilters: 'ફિલ્ટર દૂર કરો',
    viewDetails: 'વિગત જુઓ',
    applyNow: 'પોર્ટલ પર અરજી કરો',
    bookmarkScheme: 'સાચવો',
    savedSchemes: 'સાચવેલી યોજનાઓ',
    matchScore: 'લાયકાત સ્કોર',

    catAll: 'બધી યોજનાઓ',
    catAgriculture: '🌾 ખેતી અને ખેડૂત',
    catHealthcare: '🏥 આરોગ્ય અને આયુષ્માન',
    catEducation: '🎓 શિક્ષણ અને શિષ્યવૃત્તિ',
    catSocialSecurity: '🛡️ સામાજિક સુરક્ષા અને પેન્શન',
    catSkillTraining: '🔨 કૌશલ્ય તાલીમ અને MSME',
    catHousing: '🏠 આવાસ અને સ્વચ્છતા',
    catCredit: '💳 ધિરાણ અને સહાય',
    catWomenChild: '👩 મહિલા અને બાળ કલ્યાણ',

    eligible: 'લાયક',
    nearlyEligible: 'નજીવી અપૂર્ણતા',
    missingInfo: 'અધૂરી માહિતી',
    ineligible: 'અલાયક',
    partiallyVerified: 'અંશતઃ ચકાસાયેલ',
    informationalOnly: 'માત્ર માહિતી માટે',

    viewDossier: 'સત્તાવાર ડોઝિયર',
    downloadCertificate: 'પાસપોર્ટ ડોઝિયર ડાઉનલોડ કરો',
    verified: 'ચકાસાયેલ',
    actionRequired: 'કાર્યવાહી જરૂરી',
    decisionReference: 'નિર્ણય સંદર્ભ ક્રમાંક',
    annualIncome: 'વાર્ષિક આવક',
    statutoryBenefit: 'કાયદાકીય સહાય'
  },
  mr: {
    groupHome: 'मुख्यपृष्ठ',
    groupMyWelfare: 'माझे कल्याण',
    groupDiscover: 'शोधा',
    groupMyJourney: 'माझा प्रवास',
    groupAssist: 'मदत',
    groupAccount: 'खाते',

    navHome: 'मुख्य',
    navEntitlements: 'योजना',
    navLocker: 'लॉकर',
    navTracker: 'ट्रॅकर',
    navMenu: 'मेनू',

    dashboard: 'डॅशबोर्ड',
    welfarePassport: 'कल्याण पासपोर्ट',
    household: 'कुटुंब सदस्य',
    documentVault: 'कागदपत्र लॉकर',
    benefitsWallet: 'लाभ पाकीट',
    schemesCatalogue: 'योजना यादी',
    aiRecommendations: 'पात्र योजना',
    compareSchemes: 'योजना तुलना',
    applyProcess: 'अर्ज प्रक्रिया',
    trackStatus: 'अर्ज स्थिती',
    notifications: 'सूचना',
    askSaarthi: 'सारथी AI ला विचारा',
    settings: 'सेटिंग्ज',
    accountSettings: 'खाते सेटिंग्ज',
    searchOrJump: 'योजना किंवा लाभ शोधा...',
    language: 'भाषा',
    signOut: 'बाहेर पडा',
    verifiedCitizen: 'प्रमाणित नागरिक पासपोर्ट',

    exploreCatalogues: 'कल्याणकारी योजना शोधा',
    exploreDesc: 'शासकीय स्रोत आणि पात्रता नियमांसह केंद्र व राज्य शासनाच्या योजना शोधा.',
    naturalLanguageSearch: 'नैसर्गिक भाषा शोध',
    searchPlaceholder: 'योजनेचे नाव, मंत्रालय, कीवर्ड किंवा आपली माहिती लिहा...',
    samplePromptsTitle: 'नमुना शोध',
    filterByState: 'राज्यानुसार फिल्टर',
    allStates: 'सर्व राज्ये (अखिल भारतीय + राज्य योजना)',
    allCatalogues: 'सर्व वर्गवारी',
    schemesFound: 'योजना उपलब्ध',
    clearFilters: 'फिल्टर हटवा',
    viewDetails: 'तपशील पहा',
    applyNow: 'पोर्टलवर अर्ज करा',
    bookmarkScheme: 'जतन करा',
    savedSchemes: 'जतन केलेल्या योजना',
    matchScore: 'पात्रता गुण',

    catAll: 'सर्व वर्गवारी',
    catAgriculture: '🌾 शेती आणि शेतकरी',
    catHealthcare: '🏥 आरोग्य आणि आयुष्मान',
    catEducation: '🎓 शिक्षण आणि शिष्यवृत्ती',
    catSocialSecurity: '🛡️ सामाजिक सुरक्षा व पेन्शन',
    catSkillTraining: '🔨 कौशल्य विकास व MSME',
    catHousing: '🏠 गृहनिर्माण व स्वच्छता',
    catCredit: '💳 कर्ज व आर्थिक समावेशन',
    catWomenChild: '👩 महिला व बाल विकास',

    eligible: 'पात्र',
    nearlyEligible: 'जवळपास पात्र',
    missingInfo: 'अपूर्ण माहिती',
    ineligible: 'अपात्र',
    partiallyVerified: 'अंशतः पडताळलेले',
    informationalOnly: 'फक्त माहितीसाठी',

    viewDossier: 'अधिकृत डॉसियर',
    downloadCertificate: 'पासपोर्ट डॉसियर डाउनलोड करा',
    verified: 'पडताळणी पूर्ण',
    actionRequired: 'कृती आवश्यक',
    decisionReference: 'निर्णय संदर्भ क्रमांक',
    annualIncome: 'वार्षिक उत्पन्न',
    statutoryBenefit: 'वैधानिक लाभ'
  },
  bn: {
    groupHome: 'হোম',
    groupMyWelfare: 'আমার কল্যাণ',
    groupDiscover: 'অনুসন্ধান',
    groupMyJourney: 'আমার যাত্রা',
    groupAssist: 'সহায়তা',
    groupAccount: 'অ্যাকাউন্ট',

    navHome: 'হোম',
    navEntitlements: 'যোজনা',
    navLocker: 'লকার',
    navTracker: 'ট্র্যাকার',
    navMenu: 'মেনু',

    dashboard: 'ড্যাশবোর্ড',
    welfarePassport: 'ওয়েলফেয়ার পাসপোর্ট',
    household: 'পরিবারের সদস্য',
    documentVault: 'নথিপত্র লকার',
    benefitsWallet: 'সুবিধা ওয়ালেট',
    schemesCatalogue: 'যোজনা ক্যাটালগ',
    aiRecommendations: 'যোগ্য যোজনা',
    compareSchemes: 'যোজনা তুলনা',
    applyProcess: 'আবেদন প্রক্রিয়া',
    trackStatus: 'আবেদন স্থিতি',
    notifications: 'বিজ্ঞপ্তি',
    askSaarthi: 'সারথি AI-কে জিজ্ঞাসা করুন',
    settings: 'সেটিংস',
    accountSettings: 'অ্যাকাউন্ট সেটিংস',
    searchOrJump: 'যোজনা বা সুবিধা খুঁজুন...',
    language: 'ভাষা',
    signOut: 'লগ আউট',
    verifiedCitizen: 'যাচাইকৃত নাগরিক পাসপোর্ট',

    exploreCatalogues: 'কল্যাণমূলক যোজনা খুঁজুন',
    exploreDesc: 'সরকারি সূত্র এবং যোগ্যতা বিশ্লেষণ সহ কেন্দ্রীয় ও রাজ্য যোজনা জানুন।',
    naturalLanguageSearch: 'সহজ ভাষায় অনুসন্ধান',
    searchPlaceholder: 'যোজনার নাম, বিভাগ বা নিজের তথ্য লিখুন...',
    samplePromptsTitle: 'নমুনা অনুসন্ধান',
    filterByState: 'রাজ্য অনুসারে ফিল্টার',
    allStates: 'সমস্ত রাজ্য (সর্বভারতীয় + রাজ্য যোজনা)',
    allCatalogues: 'সমস্ত বিভাগ',
    schemesFound: 'যোজনা উপলব্ধ',
    clearFilters: 'ফিল্টার সরান',
    viewDetails: 'বিস্তারিত দেখুন',
    applyNow: 'পোর্টালে আবেদন করুন',
    bookmarkScheme: 'সংরক্ষণ করুন',
    savedSchemes: 'সংরক্ষিত যোজনা',
    matchScore: 'যোগ্যতা স্কোর',

    catAll: 'সমস্ত বিভাগ',
    catAgriculture: '🌾 কৃষি ও কৃষক',
    catHealthcare: '🏥 স্বাস্থ্য ও আয়ুষ্মান',
    catEducation: '🎓 শিক্ষা ও বৃত্তি',
    catSocialSecurity: '🛡️ সামাজিক সুরক্ষা ও পেনশন',
    catSkillTraining: '🔨 দক্ষতা প্রশিক্ষণ ও MSME',
    catHousing: '🏠 আবাসন ও স্যানিটেশন',
    catCredit: '💳 ঋণ ও আর্থিক অন্তর্ভুক্তি',
    catWomenChild: '👩 নারী ও শিশু কল্যাণ',

    eligible: 'যোগ্য',
    nearlyEligible: 'প্রায় যোগ্য',
    missingInfo: 'অনুপস্থিত তথ্য',
    ineligible: 'অযোগ্য',
    partiallyVerified: 'আংশিক যাচাইকৃত',
    informationalOnly: 'কেবল তথ্যের জন্য',

    viewDossier: 'অফিসিয়াল ডসিয়ার',
    downloadCertificate: 'পাসপোর্ট ডসিয়ার ডাউনলোড করুন',
    verified: 'যাচাইকৃত',
    actionRequired: 'পদক্ষেপ প্রয়োজন',
    decisionReference: 'সিদ্ধান্ত রেফারেন্স আইডি',
    annualIncome: 'বার্ষিক আয়',
    statutoryBenefit: 'আইনগত সুবিধা'
  },
  te: {
    groupHome: 'హోమ్',
    groupMyWelfare: 'నా సంక్షేమం',
    groupDiscover: 'అన్వేషించండి',
    groupMyJourney: 'నా ప్రయాణం',
    groupAssist: 'సహాయం',
    groupAccount: 'ఖాతా',

    navHome: 'హోమ్',
    navEntitlements: 'పథకాలు',
    navLocker: 'లాకర్',
    navTracker: 'ట్రాకర్',
    navMenu: 'మెనూ',

    dashboard: 'డ్యాష్‌బోర్డ్',
    welfarePassport: 'సంక్షేమ పాస్‌పోర్ట్',
    household: 'కుటుంబ సభ్యులు',
    documentVault: 'పత్రాల లాకర్',
    benefitsWallet: 'ప్రయోజనాల వాలెట్',
    schemesCatalogue: 'పథకాల కేటలాగ్',
    aiRecommendations: 'అర్హతగల పథకాలు',
    compareSchemes: 'పథకాల పోలిక',
    applyProcess: 'దరఖాస్తు కేంద్రం',
    trackStatus: 'దరఖాస్తు స్థితి',
    notifications: 'నోటిఫికేషన్‌లు',
    askSaarthi: 'సారథి AI ని అడగండి',
    settings: 'సెట్టింగ్‌లు',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    searchOrJump: 'పథకాలు లేదా ప్రయోజనాలను శోధించండి...',
    language: 'భాష',
    signOut: 'లాగ్ అవుట్',
    verifiedCitizen: 'ధృవీకరించబడిన పౌర పాస్‌పోర్ట్',

    exploreCatalogues: 'సంక్షేమ పథకాలను అన్వేషించండి',
    exploreDesc: 'ధృవీకరించబడిన ప్రభుత్వ వనరులు మరియు అర్హత నియమాలతో కేంద్ర, రాష్ట్ర పథకాలను కనుగొనండి.',
    naturalLanguageSearch: 'సహజ భాషా శోధన',
    searchPlaceholder: 'పథకం పేరు, మంత్రిత్వ శాఖ లేదా మీ వివరాలు రాయండి...',
    samplePromptsTitle: 'నమూనా శోధనలు',
    filterByState: 'రాష్ట్రాల వారీగా ఫిల్టర్',
    allStates: 'అన్ని రాష్ట్రాలు (అఖిల భారత + రాష్ట్ర పథకాలు)',
    allCatalogues: 'అన్ని వర్గాలు',
    schemesFound: 'అందుబాటులో ఉన్న పథకాలు',
    clearFilters: 'ఫిల్టర్లను క్లియర్ చేయండి',
    viewDetails: 'వివరాలు చూడండి',
    applyNow: 'పోర్టల్‌లో దరఖాస్తు చేయండి',
    bookmarkScheme: 'సేవ్ చేయండి',
    savedSchemes: 'సేవ్ చేసిన పథకాలు',
    matchScore: 'అర్హత స్కోరు',

    catAll: 'అన్ని వర్గాలు',
    catAgriculture: '🌾 వ్యవసాయం & రైతులు',
    catHealthcare: '🏥 ఆరోగ్యం & ఆయుష్మాన్',
    catEducation: '🎓 విద్య & స్కాలర్‌షిప్‌లు',
    catSocialSecurity: '🛡️ సామాజిక భద్రత & పింఛను',
    catSkillTraining: '🔨 నైపుణ్య శిక్షణ & MSME',
    catHousing: '🏠 గృహనిర్మాణం & పారిశుధ్యం',
    catCredit: '💳 రుణాలు & ఆర్థిక చేరిక',
    catWomenChild: '👩 మహిళా & శిశు సంక్షేమం',

    eligible: 'అర్హులు',
    nearlyEligible: 'దాదాపు అర్హులు',
    missingInfo: 'అసంపూర్ణ సమాచారం',
    ineligible: 'అనర్హులు',
    partiallyVerified: 'పాక్షికంగా ధృవీకరించబడింది',
    informationalOnly: 'సమాచారం కోసం మాత్రమే',

    viewDossier: 'అధికారిక డాసియర్',
    downloadCertificate: 'పాస్‌పోర్ట్ డాసియర్ డౌన్‌లోడ్ చేయండి',
    verified: 'ధృవీకరించబడింది',
    actionRequired: 'చర్య అవసరం',
    decisionReference: 'నిర్ణయ సూచన ఐడి',
    annualIncome: 'వార్షిక ఆదాయం',
    statutoryBenefit: 'చట్టబద్ధమైన ప్రయోజనం'
  },
  ta: {
    groupHome: 'முகப்பு',
    groupMyWelfare: 'எனது நலத்திட்டம்',
    groupDiscover: 'கண்டறியவும்',
    groupMyJourney: 'எனது பயணம்',
    groupAssist: 'உதவி',
    groupAccount: 'கணக்கு',

    navHome: 'முகப்பு',
    navEntitlements: 'திட்டங்கள்',
    navLocker: 'ஆவணப் பெட்டகம்',
    navTracker: 'நிலை காண்க',
    navMenu: 'மெனு',

    dashboard: 'டாஷ்போர்டு',
    welfarePassport: 'நலத்திட்ட கடவுச்சீட்டு',
    household: 'குடும்ப உறுப்பினர்கள்',
    documentVault: 'ஆவணப் பெட்டகம்',
    benefitsWallet: 'பயன்கள் பணப்பை',
    schemesCatalogue: 'திட்டங்கள் பட்டியல்',
    aiRecommendations: 'தகுதியான திட்டங்கள்',
    compareSchemes: 'திட்டங்களை ஒப்பிடுக',
    applyProcess: 'விண்ணப்ப மையம்',
    trackStatus: 'விண்ணப்ப நிலை',
    notifications: 'அறிவிப்புகள்',
    askSaarthi: 'சாரதி AI-யிடம் கேளுங்கள்',
    settings: 'அமைப்புகள்',
    accountSettings: 'கணக்கு அமைப்புகள்',
    searchOrJump: 'திட்டங்கள் அல்லது பயன்களைத் தேடுங்கள்...',
    language: 'மொழி',
    signOut: 'வெளியேறு',
    verifiedCitizen: 'சரிபார்க்கப்பட்ட குடிமக்கள் பாஸ்போர்ட்',

    exploreCatalogues: 'நலத்திட்டங்களை ஆராயுங்கள்',
    exploreDesc: 'அரசு ஆதாரங்கள் மற்றும் தகுதி விதிகளுடன் மத்திய, மாநில நலத்திட்டங்களைக் கண்டறியுங்கள்.',
    naturalLanguageSearch: 'எளிய மொழி தேடல்',
    searchPlaceholder: 'திட்டத்தின் பெயர், துறை அல்லது உங்கள் விவரங்களை உள்ளிடவும்...',
    samplePromptsTitle: 'மாதிரி தேடல்கள்',
    filterByState: 'மாநில வாரியாக வடிகட்டவும்',
    allStates: 'அனைத்து மாநிலங்கள் (அகில இந்திய + மாநிலத் திட்டங்கள்)',
    allCatalogues: 'அனைத்துப் பிரிவுகள்',
    schemesFound: 'கிடைக்கும் திட்டங்கள்',
    clearFilters: 'வடிகட்டிகளை அழிக்கவும்',
    viewDetails: 'விவரங்களைக் காண்க',
    applyNow: 'இணையதளத்தில் விண்ணப்பிக்கவும்',
    bookmarkScheme: 'சேமிக்க',
    savedSchemes: 'சேமிக்கப்பட்ட திட்டங்கள்',
    matchScore: 'தகுதி மதிப்பீடு',

    catAll: 'அனைத்துப் பிரிவுகள்',
    catAgriculture: '🌾 விவசாயம் & விவசாயிகள்',
    catHealthcare: '🏥 சுகாதாரம் & ஆயுஷ்மான்',
    catEducation: '🎓 கல்வி & கல்வி உதவித்தொகை',
    catSocialSecurity: '🛡️ சமூகப் பாதுகாப்பு & ஓய்வூதியம்',
    catSkillTraining: '🔨 திறன் மேம்பாடு & MSME',
    catHousing: '🏠 வீட்டுவசதி & சுகாதாரம்',
    catCredit: '💳 கடன் & நிதி உள்ளடக்கம்',
    catWomenChild: '👩 பெண்கள் மற்றும் குழந்தைகள் நலம்',

    eligible: 'தகுதியானது',
    nearlyEligible: 'கிட்டத்தட்ட தகுதியானது',
    missingInfo: 'விவரங்கள் தேவை',
    ineligible: 'தகுதியற்றது',
    partiallyVerified: 'பகுதியளவு சரிபார்க்கப்பட்டது',
    informationalOnly: 'தகவல் மட்டுமே',

    viewDossier: 'அதிகாரப்பூர்வ ஆவணம்',
    downloadCertificate: 'பாஸ்போர்ட் ஆவணத்தைப் பதிவிறக்கவும்',
    verified: 'சரிபார்க்கப்பட்டது',
    actionRequired: 'நடவடிக்கை தேவை',
    decisionReference: 'முடிவு குறிப்பு எண்',
    annualIncome: 'ஆண்டு வருமானம்',
    statutoryBenefit: 'சட்டபூர்வ நன்மை'
  },
  kn: {
    groupHome: 'ಮುಖಪುಟ',
    groupMyWelfare: 'ನನ್ನ ಕಲ್ಯಾಣ',
    groupDiscover: 'ಹುಡುಕಿ',
    groupMyJourney: 'ನನ್ನ ಪ್ರಯಾಣ',
    groupAssist: 'ಸಹಾಯ',
    groupAccount: 'ಖಾತೆ',

    navHome: 'ಮುಖಪುಟ',
    navEntitlements: 'ಯೋಜನೆಗಳು',
    navLocker: 'ದಾಖಲೆ ಲಾಕರ್',
    navTracker: 'ಸ್ಥಿತಿ ನೋಡಿ',
    navMenu: 'ಮೆನು',

    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    welfarePassport: 'ಕಲ್ಯಾಣ ಪಾಸ್‌ಪೋರ್ಟ್',
    household: 'ಕುಟುಂಬ ಸದಸ್ಯರು',
    documentVault: 'ದಾಖಲೆ ವಾಲ್ಟ್',
    benefitsWallet: 'ಸೌಲಭ್ಯ ವಾಲೆಟ್',
    schemesCatalogue: 'ಯೋಜನೆಗಳ ಪಟ್ಟಿ',
    aiRecommendations: 'ಅರ್ಹ ಯೋಜನೆಗಳು',
    compareSchemes: 'ಯೋಜನೆಗಳ ಹೋಲಿಕೆ',
    applyProcess: 'ಅರ್ಜಿ ಕೇಂದ್ರ',
    trackStatus: 'ಅರ್ಜಿ ಸ್ಥಿತಿ',
    notifications: 'ಸೂಚನೆಗಳು',
    askSaarthi: 'ಸಾರಥಿ AI ಗೆ ಕೇಳಿ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    searchOrJump: 'ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ...',
    language: 'ಭಾಷೆ',
    signOut: 'ನಿರ್ಗಮಿಸಿ',
    verifiedCitizen: 'ದೃಢೀಕೃತ ನಾಗರಿಕ ಪಾಸ್‌ಪೋರ್ಟ್',

    exploreCatalogues: 'ಕಲ್ಯಾಣ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    exploreDesc: 'ಸರ್ಕಾರಿ ಮೂಲಗಳು ಮತ್ತು ಅರ್ಹತಾ ಮಾನದಂಡಗಳೊಂದಿಗೆ ಕೇಂದ್ರ ಮತ್ತು ರಾಜ್ಯ ಯೋಜನೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ.',
    naturalLanguageSearch: 'ಸಹಜ ಭಾಷಾ ಹುಡುಕಾಟ',
    searchPlaceholder: 'ಯೋಜನೆಯ ಹೆಸರು, ಇಲಾಖೆ ಅಥವಾ ನಿಮ್ಮ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ...',
    samplePromptsTitle: 'ಮಾದರಿ ಹುಡುಕಾಟಗಳು',
    filterByState: 'ರಾಜ್ಯವಾರು ಫಿಲ್ಟರ್',
    allStates: 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು (ಅಖಿಲ ಭಾರತ + ರಾಜ್ಯ ಯೋಜನೆಗಳು)',
    allCatalogues: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    schemesFound: 'ಲಭ್ಯವಿರುವ ಯೋಜನೆಗಳು',
    clearFilters: 'ಫಿಲ್ಟರ್ ತೆಗೆಯಿರಿ',
    viewDetails: 'ವಿವರ ನೋಡಿ',
    applyNow: 'ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    bookmarkScheme: 'ಉಳಿಸಿ',
    savedSchemes: 'ಉಳಿಸಿದ ಯೋಜನೆಗಳು',
    matchScore: 'ಅರ್ಹತಾ ಸ್ಕೋರ್',

    catAll: 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
    catAgriculture: '🌾 ಕೃಷಿ ಮತ್ತು ರೈತರು',
    catHealthcare: '🏥 ಆರೋಗ್ಯ ಮತ್ತು ಆಯುಷ್ಮಾನ್',
    catEducation: '🎓 ಶಿಕ್ಷಣ ಮತ್ತು ವಿದ್ಯಾರ್ಥಿವೇತನ',
    catSocialSecurity: '🛡️ ಸಾಮಾಜಿಕ ಭದ್ರತೆ ಮತ್ತು ಪಿಂಚಣಿ',
    catSkillTraining: '🔨 ಕೌಶಲ್ಯ ತರಬೇತಿ ಮತ್ತು MSME',
    catHousing: '🏠 ವಸತಿ ಮತ್ತು ನೈರ್ಮಲ್ಯ',
    catCredit: '💳 ಸಾಲ ಮತ್ತು ಆರ್ಥಿಕ ಸೇರ್ಪಡೆ',
    catWomenChild: '👩 ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ ಕಲ್ಯಾಣ',

    eligible: 'ಅರ್ಹರು',
    nearlyEligible: 'ಬಹುತೇಕ ಅರ್ಹರು',
    missingInfo: 'ಅಪೂರ್ಣ ಮಾಹಿತಿ',
    ineligible: 'ಅನರ್ಹರು',
    partiallyVerified: 'ಭಾಗಶಃ ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    informationalOnly: 'ಮಾಹಿತಿಗಾಗಿ ಮಾತ್ರ',

    viewDossier: 'ಅಧಿಕೃತ ಕಡತ',
    downloadCertificate: 'ಪಾಸ್‌ಪೋರ್ಟ್ ಕಡತ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    verified: 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    actionRequired: 'ಕ್ರಮ ಅಗತ್ಯವಿದೆ',
    decisionReference: 'ನಿರ್ಧಾರ ಉಲ್ಲೇಖ ಐಡಿ',
    annualIncome: 'ವಾರ್ಷಿಕ ಆದಾಯ',
    statutoryBenefit: 'ಶಾಸನಬದ್ಧ ಸೌಲಭ್ಯ'
  },
  ml: {
    groupHome: 'ഹോം',
    groupMyWelfare: 'എന്റെ ക്ഷേമം',
    groupDiscover: 'കണ്ടെത്തുക',
    groupMyJourney: 'എന്റെ യാത്ര',
    groupAssist: 'സഹായം',
    groupAccount: 'അക്കൗണ്ട്',

    navHome: 'ഹോം',
    navEntitlements: 'പദ്ധതികൾ',
    navLocker: 'ലോക്കർ',
    navTracker: 'ട്രാക്കർ',
    navMenu: 'മെനു',

    dashboard: 'ഡാഷ്‌ബോർഡ്',
    welfarePassport: 'ക്ഷേമ പാസ്‌പോർട്ട്',
    household: 'കുടുംബാംഗങ്ങൾ',
    documentVault: 'ഡോക്യുമെന്റ് ലോക്കർ',
    benefitsWallet: 'ആനുകൂല്യ വാലറ്റ്',
    schemesCatalogue: 'പദ്ധതികളുടെ പട്ടിക',
    aiRecommendations: 'അർഹമായ പദ്ധതികൾ',
    compareSchemes: 'പദ്ധതി താരതമ്യം',
    applyProcess: 'അപേക്ഷാ കേന്ദ്രം',
    trackStatus: 'അപേക്ഷാ നില',
    notifications: 'അറിയിപ്പുകൾ',
    askSaarthi: 'സാരഥി AI-യോട് ചോദിക്കുക',
    settings: 'ക്രമീകരണങ്ങൾ',
    accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ',
    searchOrJump: 'പദ്ധതികൾ തിരയുക...',
    language: 'ഭാഷ',
    signOut: 'ലോഗ് ഔട്ട്',
    verifiedCitizen: 'സാക്ഷ്യപ്പെടുത്തിയ പൗര പാസ്‌പോർട്ട്',

    exploreCatalogues: 'ക്ഷേമ പദ്ധതികൾ കണ്ടെത്തുക',
    exploreDesc: 'ഔദ്യോഗിക സർക്കാർ സ്രോതസ്സുകളോടെ കേന്ദ്ര, സംസ്ഥാന പദ്ധതികൾ അറിയുക.',
    naturalLanguageSearch: 'സ്വാഭാവിക ഭാഷാ തിരച്ചിൽ',
    searchPlaceholder: 'പദ്ധതിയുടെ പേര്, വകുപ്പ് അല്ലെങ്കിൽ നിങ്ങളുടെ വിവരങ്ങൾ നൽകുക...',
    samplePromptsTitle: 'മാതൃകാ ചോദ്യങ്ങൾ',
    filterByState: 'സംസ്ഥാനം അനുസരിച്ച് ഫിൽട്ടർ ചെയ്യുക',
    allStates: 'എല്ലാ സംസ്ഥാനങ്ങളും (അഖിലേന്ത്യാ + സംസ്ഥാന പദ്ധതികൾ)',
    allCatalogues: 'എല്ലാ വിഭാഗങ്ങളും',
    schemesFound: 'ലഭ്യമായ പദ്ധതികൾ',
    clearFilters: 'ഫിൽട്ടറുകൾ നീക്കുക',
    viewDetails: 'വിശദാംശങ്ങൾ കാണുക',
    applyNow: 'പോർട്ടലിൽ അപേക്ഷിക്കുക',
    bookmarkScheme: 'സൂക്ഷിക്കുക',
    savedSchemes: 'സൂക്ഷിച്ച പദ്ധതികൾ',
    matchScore: 'അർഹതാ സ്കോർ',

    catAll: 'എല്ലാ വിഭാഗങ്ങളും',
    catAgriculture: '🌾 കൃഷിയും കർഷകരും',
    catHealthcare: '🏥 ആരോഗ്യവും ആയുഷ്മാനും',
    catEducation: '🎓 വിദ്യാഭ്യാസവും സ്കോളർഷിപ്പും',
    catSocialSecurity: '🛡️ സാമൂഹിക സുരക്ഷയും പെൻഷനും',
    catSkillTraining: '🔨 തൊഴിൽ പരിശീലനവും MSME യും',
    catHousing: '🏠 ഭവനനിർമ്മാണവും ശുചിത്വവും',
    catCredit: '💳 വായ്പയും ധനകാര്യവും',
    catWomenChild: '👩 വനിതാ-ശിശു ക്ഷേമം',

    eligible: 'അർഹതയുണ്ട്',
    nearlyEligible: 'ഏറെക്കുറെ അർഹതയുണ്ട്',
    missingInfo: 'വിവരങ്ങൾ അപൂർണ്ണം',
    ineligible: 'അർഹതയില്ല',
    partiallyVerified: 'ഭാഗികമായി പരിശോധിച്ചു',
    informationalOnly: 'വിവരങ്ങൾക്ക് മാത്രം',

    viewDossier: 'ഔദ്യോഗിക ഡോസിയർ',
    downloadCertificate: 'പാസ്‌പോർട്ട് ഡോസിയർ ഡൗൺലോഡ് ചെയ്യുക',
    verified: 'പരിശോധിച്ചുറപ്പിച്ചു',
    actionRequired: 'നടപടി ആവശ്യമാണ്',
    decisionReference: 'തീരുമാന റഫറൻസ് ഐഡി',
    annualIncome: 'വാർഷിക വരുമാനം',
    statutoryBenefit: 'നിയമപരമായ ആനുകൂല്യം'
  },
  pa: {
    groupHome: 'ਮੁੱਖ ਪੰਨਾ',
    groupMyWelfare: 'ਮੇਰੀ ਭਲਾਈ',
    groupDiscover: 'ਖੋਜੋ',
    groupMyJourney: 'ਮੇਰਾ ਸਫ਼ਰ',
    groupAssist: 'ਸਹਾਇਤਾ',
    groupAccount: 'ਖਾਤਾ',

    navHome: 'ਮੁੱਖ',
    navEntitlements: 'ਸਕੀਮਾਂ',
    navLocker: 'ਲਾਕਰ',
    navTracker: 'ਟਰੈਕਰ',
    navMenu: 'ਮੀਨੂ',

    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    welfarePassport: 'ਵੈਲਫੇਅਰ ਪਾਸਪੋਰਟ',
    household: 'ਪਰਿਵਾਰਕ ਮੈਂਬਰ',
    documentVault: 'ਦਸਤਾਵੇਜ਼ ਲਾਕਰ',
    benefitsWallet: 'ਲਾਭ ਵਾਲੇਟ',
    schemesCatalogue: 'ਸਕੀਮਾਂ ਦੀ ਸੂਚੀ',
    aiRecommendations: 'ਯੋਗ ਸਕੀਮਾਂ',
    compareSchemes: 'ਸਕੀਮ ਤੁਲਨਾ',
    applyProcess: 'ਅਰਜ਼ੀ ਪ੍ਰਕਿਰਿਆ',
    trackStatus: 'ਅਰਜ਼ੀ ਦੀ ਸਥਿਤੀ',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    askSaarthi: 'ਸਾਰਥੀ AI ਨੂੰ ਪੁੱਛੋ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    accountSettings: 'ਖਾਤਾ ਸੈਟਿੰਗਾਂ',
    searchOrJump: 'ਸਕੀਮਾਂ ਜਾਂ ਲਾਭ ਲੱਭੋ...',
    language: 'ਭਾਸ਼ਾ',
    signOut: 'ਲਾਗ ਆਊਟ',
    verifiedCitizen: 'ਤਸਦੀਕਸ਼ੁਦਾ ਨਾਗਰਿਕ ਪਾਸਪੋਰਟ',

    exploreCatalogues: 'ਭਲਾਈ ਸਕੀਮਾਂ ਦੀ ਖੋਜ ਕਰੋ',
    exploreDesc: 'ਸਰਕਾਰੀ ਸਰੋਤਾਂ ਅਤੇ ਯੋਗਤਾ ਨਿਯਮਾਂ ਨਾਲ ਕੇਂਦਰ ਅਤੇ ਰਾਜ ਸਰਕਾਰ ਦੀਆਂ ਸਕੀਮਾਂ ਜਾਣੋ।',
    naturalLanguageSearch: 'ਸਰਲ ਭਾਸ਼ਾ ਖੋਜ',
    searchPlaceholder: 'ਸਕੀਮ ਦਾ ਨਾਮ, ਵਿਭਾਗ ਜਾਂ ਆਪਣੀ ਜਾਣਕਾਰੀ ਲਿਖੋ...',
    samplePromptsTitle: 'ਨਮੂਨਾ ਖੋਜ',
    filterByState: 'ਰਾਜ ਅਨੁਸਾਰ ਫਿਲਟਰ',
    allStates: 'ਸਾਰੇ ਰਾਜ (ਸਰਬ ਭਾਰਤ + ਰਾਜ ਸਕੀਮਾਂ)',
    allCatalogues: 'ਸਾਰੀਆਂ ਸ਼੍ਰੇਣੀਆਂ',
    schemesFound: 'ਉਪਲਬਧ ਸਕੀਮਾਂ',
    clearFilters: 'ਫਿਲਟਰ ਹਟਾਓ',
    viewDetails: 'ਵੇਰਵੇ ਦੇਖੋ',
    applyNow: 'ਪੋਰਟਲ ਤੇ ਅਪਲਾਈ ਕਰੋ',
    bookmarkScheme: 'ਸੰਭਾਲੋ',
    savedSchemes: 'ਸੰਭਾਲੀਆਂ ਸਕੀਮਾਂ',
    matchScore: 'ਯੋਗਤਾ ਸਕੋਰ',

    catAll: 'ਸਾਰੀਆਂ ਸਕੀਮਾਂ',
    catAgriculture: '🌾 ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ',
    catHealthcare: '🏥 ਸਿਹਤ ਅਤੇ ਆਯੁਸ਼ਮਾਨ',
    catEducation: '🎓 ਸਿੱਖਿਆ ਅਤੇ ਵਜ਼ੀਫ਼ੇ',
    catSocialSecurity: '🛡️ ਸਮਾਜਿਕ ਸੁਰੱਖਿਆ ਤੇ ਪੈਨਸ਼ਨ',
    catSkillTraining: '🔨 ਹੁਨਰ ਸਿਖਲਾਈ ਤੇ MSME',
    catHousing: '🏠 ਰਿਹਾਇਸ਼ ਤੇ ਸਵੱਛਤਾ',
    catCredit: '💳 ਕਰਜ਼ਾ ਤੇ ਵਿੱਤੀ ਸਹਾਇਤਾ',
    catWomenChild: '👩 ਮਹਿਲਾ ਤੇ ਬਾਲ ਵਿਕਾਸ',

    eligible: 'ਯੋਗ',
    nearlyEligible: 'ਲਗਭਗ ਯੋਗ',
    missingInfo: 'ਅਧੂਰੀ ਜਾਣਕਾਰੀ',
    ineligible: 'ਅਯੋਗ',
    partiallyVerified: 'ਅੰਸ਼ਕ ਤਸਦੀਕ',
    informationalOnly: 'ਸਿਰਫ਼ ਜਾਣਕਾਰੀ ਲਈ',

    viewDossier: 'ਅਧਿਕਾਰਤ ਡੌਜ਼ੀਅਰ',
    downloadCertificate: 'ਪਾਸਪੋਰਟ ਡੌਜ਼ੀਅਰ ਡਾਊਨਲੋਡ ਕਰੋ',
    verified: 'ਤਸਦੀਕਸ਼ੁਦਾ',
    actionRequired: 'ਕਾਰਵਾਈ ਦੀ ਲੋੜ ਹੈ',
    decisionReference: 'ਫੈਸਲਾ ਹਵਾਲਾ ਨੰਬਰ',
    annualIncome: 'ਸਾਲਾਨਾ ਆਮਦਨ',
    statutoryBenefit: 'ਕਾਨੂੰਨੀ ਲਾਭ'
  },
  or: {
    groupHome: 'ମୂଳପୃଷ୍ଠା',
    groupMyWelfare: 'ମୋର କଲ୍ୟାଣ',
    groupDiscover: 'ସନ୍ଧାନ',
    groupMyJourney: 'ମୋର ଯାତ୍ରା',
    groupAssist: 'ସହାୟତା',
    groupAccount: 'ଖାତା',

    navHome: 'ମୂଳପୃଷ୍ଠା',
    navEntitlements: 'ଯୋଜନା',
    navLocker: 'ଲକର',
    navTracker: 'ଟ୍ରାକର',
    navMenu: 'ମେନୁ',

    dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    welfarePassport: 'କଲ୍ୟାଣ ପାସପୋର୍ଟ',
    household: 'ପରିବାର ସଦସ୍ୟ',
    documentVault: 'ଦସ୍ତାବିଜ ଲକର',
    benefitsWallet: 'ଲାଭ ୱାଲେଟ',
    schemesCatalogue: 'ଯୋଜନା ତାଲିକା',
    aiRecommendations: 'ଯୋଗ୍ୟ ଯୋଜନା',
    compareSchemes: 'ଯୋଜନା ତୁଳନା',
    applyProcess: 'ଆବେଦନ କେନ୍ଦ୍ର',
    trackStatus: 'ଆବେଦନ ସ୍ଥିତି',
    notifications: 'ବିଜ୍ଞପ୍ତି',
    askSaarthi: 'ସାରଥୀ AI କୁ ପଚାରନ୍ତୁ',
    settings: 'ସେଟିଂସ',
    accountSettings: 'ଖାତା ସେଟିଂସ',
    searchOrJump: 'ଯୋଜନା ସନ୍ଧାନ କରନ୍ତୁ...',
    language: 'ଭାଷା',
    signOut: 'ଲଗ ଆଉଟ',
    verifiedCitizen: 'ପ୍ରମାଣିତ ନାଗରିକ ପାସପୋର୍ଟ',

    exploreCatalogues: 'କଲ୍ୟାଣ ଯୋଜନା ଅନୁସନ୍ଧାନ କରନ୍ତୁ',
    exploreDesc: 'ସରକାରୀ ତଥ୍ୟ ଏବଂ ଯୋଗ୍ୟତା ନିୟମ ସହିତ କେନ୍ଦ୍ର ଓ ରାଜ୍ୟ ଯୋଜନା ଜାଣନ୍ତୁ।',
    naturalLanguageSearch: 'ସରଳ ଭାଷା ସନ୍ଧାନ',
    searchPlaceholder: 'ଯୋଜନାର ନାମ, ବିଭାଗ କିମ୍ବା ଆପଣଙ୍କ ବିବରଣୀ ଲେଖନ୍ତୁ...',
    samplePromptsTitle: 'ନମୁନା ସନ୍ଧାନ',
    filterByState: 'ରାଜ୍ୟ ଅନୁସାରେ ଫିଲ୍ଟର',
    allStates: 'ସମସ୍ତ ରାଜ୍ୟ (ସର୍ବଭାରତୀୟ + ରାଜ୍ୟ ଯୋଜନା)',
    allCatalogues: 'ସମସ୍ତ ବର୍ଗ',
    schemesFound: 'ଉପଲବ୍ଧ ଯୋଜନା',
    clearFilters: 'ଫିଲ୍ଟର ହଟାନ୍ତୁ',
    viewDetails: 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    applyNow: 'ପୋର୍ଟାଲରେ ଆବେଦନ କରନ୍ତୁ',
    bookmarkScheme: 'ସାଇତନ୍ତୁ',
    savedSchemes: 'ସାଇତା ଯୋଜନା',
    matchScore: 'ଯୋଗ୍ୟତା ସ୍କୋର',

    catAll: 'ସମସ୍ତ ବର୍ଗ',
    catAgriculture: '🌾 କୃଷି ଓ କୃଷକ',
    catHealthcare: '🏥 ସ୍ୱାସ୍ଥ୍ୟ ଓ ଆୟୁଷ୍ମାନ',
    catEducation: '🎓 ଶିକ୍ଷା ଓ ବୃତ୍ତି',
    catSocialSecurity: '🛡️ ସାମାଜିକ ସୁରକ୍ଷା ଓ ପେନସନ',
    catSkillTraining: '🔨 ଦକ୍ଷତା ବିକାଶ ଓ MSME',
    catHousing: '🏠 ଆବାସ ଓ ପରିମଳ',
    catCredit: '💳 ଋଣ ଓ ଆର୍ଥିକ ଅନ୍ତର୍ଭୁକ୍ତିକରଣ',
    catWomenChild: '👩 ମହିଳା ଓ ଶିଶୁ କଲ୍ୟାଣ',

    eligible: 'ଯୋଗ୍ୟ',
    nearlyEligible: 'ପାଖାପାଖି ଯୋଗ୍ୟ',
    missingInfo: 'ଅଧୁରା ତଥ୍ୟ',
    ineligible: 'ଅଯୋଗ୍ୟ',
    partiallyVerified: 'ଆଂଶିକ ଯାଞ୍ଚ ହୋଇଛି',
    informationalOnly: 'କେବଳ ସୂଚନା ପାଇଁ',

    viewDossier: 'ଅଫିସିଆଲ ଡସିଅର',
    downloadCertificate: 'ପାସପୋର୍ଟ ଡସିଅର ଡାଉନଲୋଡ କରନ୍ତୁ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି',
    actionRequired: 'ପଦକ୍ଷେପ ଆବଶ୍ୟକ',
    decisionReference: 'ନିଷ୍ପତ୍ତି ରେଫରେନ୍ସ ଆଇଡି',
    annualIncome: 'ବାର୍ଷିକ ଆୟ',
    statutoryBenefit: 'ଆଇନଗତ ଲାଭ'
  }
};

export const supportedLanguages = [
  { code: 'en', label: 'English', native: 'English' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી' },
  { code: 'mr', label: 'Marathi', native: 'मराठी' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'Malayalam', native: 'മലയാളം' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ' },
  { code: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ' }
];

export function LanguageProvider({ children }) {
  const [currentLang, setCurrentLang] = useState(() => {
    return localStorage.getItem('saarthi_language') || 'en';
  });

  useEffect(() => {
    localStorage.setItem('saarthi_language', currentLang);
  }, [currentLang]);

  const t = (key) => {
    return translations[currentLang]?.[key] || 
           passportTranslations[currentLang]?.[key] || 
           translations['en']?.[key] || 
           passportTranslations['en']?.[key] || 
           key;
  };

  const changeLanguage = (code) => {
    if (translations[code] || passportTranslations[code]) {
      setCurrentLang(code);
    }
  };

  return (
    <LanguageContext.Provider value={{ currentLang, setLanguage: changeLanguage, t, supportedLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    return {
      currentLang: 'en',
      setLanguage: () => {},
      t: (key) => translations.en[key] || passportTranslations.en[key] || key,
      supportedLanguages
    };
  }
  return context;
}
